### ISSUE TITLE
FR - Detect unused annotation processors

### ISSUE THREAD

**Issue by ZacSweers** [autonomousapps/dependency-analysis-android-gradle-plugin#102]
**Is your feature request related to a problem? Please describe.**

Currently, annotation processors are not accounted. for. It would be neat if the plugin could detect if there are processors that are not running that could be removed.

**Describe the solution you'd like**

So in annotation processors, there is a `getSupportedAnnotations()` method in each processor. The processor could be looked up by its service file, and then during bytecode analysis look for usages of the annotations those processors declare. If all the the processors from a given artifact are _not_ applicable, then that processor could be removed.

Some processors expect/require `init()` to be called first before any other methods, so it may not work for every processor. You can also read a `@SupportedAnnotations` annotation off of processor classes.

**Comment by ZacSweers** [comment]
Note also that `*` is a valid "supported" annotation, which basically means that processor processes _everything_ and should be assumed not safe to remove.

**Comment by autonomousapps** [comment]
Do you have any hints on how best to invoke annotation processors I find in a build? With the goal of calling `getSupportedAnnotation()`. Also, if an AP has the `@SupportedAnnotation` annotation, would it still have that method available? (i.e., do I need to be prepared to read from both places)

I can find the path to the jar and read `META-INF/services/javax.annotation.processing.Processor` and from there find the class file, but....
