### ISSUE TITLE
Plugin adviced to add "org.jetbrains.kotlin:kotlin-stdlib" dependency to api

### ISSUE THREAD

**Issue by sboishtyan** [autonomousapps/dependency-analysis-android-gradle-plugin#111]
**Plugin version**
0.38

**Gradle version**
6.2

**Android Gradle Plugin (AGP) version**
3.6.2

**Describe the bug**
We have multimodule project and all modules use `kotlin plugin`. And we don't have explicit dependency on "org.jetbrains.kotlin:kotlin-stdlib", but I think plugin added it for us.
I see in my advice.json a many of 

```
"dependency": {
        "identifier": "org.jetbrains.kotlin:kotlin-stdlib",
        "resolvedVersion": "1.3.72",
        "configurationName": "implementation"
      },
      "fromConfiguration": "implementation",
      "toConfiguration": "api"
    }
```

**To Reproduce**
If it's not expected behavior I can give a link to the sample project.

**Expected behavior**
We don't see advice about "org.jetbrains.kotlin:kotlin-stdlib" if we don't have an explicit declaration.
Or maybe we have a way to disable that advice

**Comment by autonomousapps** [comment]
You can suppress that advice like so:
```groovy
// root project
dependencyAnalysis {
  issues {
    onAny {
      warn("org.jetbrains.kotlin:kotlin-stdlib")
    }
  }
}
```
it looks a little counter-intuitive (I have plans to improve the DSL), but for now, what this will do is instruct the plugin not to tell you about the kotlin-stdlib dependency.
