### ISSUE TITLE
FR: Check if Jetifier can be removed

### ISSUE THREAD

**Issue by mzgreen** [autonomousapps/dependency-analysis-android-gradle-plugin#117]
Add a check if Jetifier is needed and if it is then report which dependencies still require it.

**Comment by autonomousapps** [comment]
Interesting idea. Is jetifier only required if there are dependencies on the classpath that use the old android.support packages?

**Comment by mzgreen** [comment]
Yes but it seems that it checks not only code (Java/Kotlin) but also xml, pom and proguard files 
https://developer.android.com/studio/command-line/jetifier#usage_notes

**Comment by stephanenicolas** [comment]
It would be interesting to have a check that detects a lib requires jetification. It would help to clean a project and remove jetifier.

**Comment by autonomousapps** [comment]
This is not necessarily a good issue for a first-time contributor, but if anyone wants to take a crack at it, look at the task that writes output to `intermediates/all-declared-dependencies.json`. This output includes a `classes` field that is a `List<String>` of all classes supplied by the dependency. Here's a partial example of the prettified output:

```json
{
    "dependency": {
      "identifier": "androidx.activity:activity",
      "resolvedVersion": "1.0.0-rc01"
    },
    "isTransitive": true,
    "isCompileOnlyAnnotations": false,
    "classes": [
      "androidx.activity.Cancellable",
      "androidx.activity.ComponentActivity",
      "androidx.activity.ComponentActivity$1",
      "androidx.activity.ComponentActivity$2",
      "androidx.activity.ComponentActivity$3",
      "androidx.activity.ComponentActivity$NonConfigurationInstances",
```
One can imagine inspecting this output for classes that start with `android.support`.

There's also a file `intermediates/android-res-by-res-usage.json` that produces
```json
[{"dependency":{"identifier":"androidx.appcompat:appcompat","resolvedVersion":"1.1.0-rc01"},"lines":[{"type":"style","value":"Theme_AppCompat_Light_DarkActionBar"},{"type":"style","value":"ThemeOverlay_AppCompat_Dark_ActionBar"},{"type":"style","value":"ThemeOverlay_AppCompat_Light"}]}]
```
which may provide some clues on looking for resource usages of the old support libraries.

Furthermore, it would be possible to look at proguard files, but there is as yet no prior art in the plugin for this. It's on the "eventual" roadmap.

**Comment by ZacSweers** [comment]
A plugin for this already exists, I don't think it's worth duplicating https://github.com/plnice/can-i-drop-jetifier
