### ISSUE TITLE
FR: Apply changes to build.gradle files

### ISSUE THREAD

**Issue by changusmc** [autonomousapps/dependency-analysis-android-gradle-plugin#121]
It would be great if the plugin could somehow make in-place updates from the suggestions to the `build.gradle` files.

**Comment by ZacSweers** [comment]
This is a dupe for #15 I think

**Comment by autonomousapps** [comment]
I agree. Going to close this for now. Please see https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/15 for details.
