### ISSUE TITLE
Add a filter for unusedProcsAdvice

### ISSUE THREAD

**Issue by stephanenicolas** [autonomousapps/dependency-analysis-android-gradle-plugin#126]

**Comment by Paladinium** [comment]
We would like to fail the build on unused dependencies:

`dependencyAnalysis {
	issues {
		onUnusedDependencies { fail("org.projectlombok:lombok") }
		onUsedTransitiveDependencies { ignore() }
		onIncorrectConfiguration { ignore() }
	}
}`

Even though we added an exception, the build still fails:

> Unused annotation processors that should be removed:
> - implementation("org.projectlombok:lombok:1.18.12")

@stephanenicolas I assume your change would provide a solution for this, right?

**Comment by autonomousapps** [comment]
@Paladinium thanks for the comment. Yes, the change @stephanenicolas is working on should resolve this. It will add a new block to the `issues {}` block, name tbd.

**Comment by Paladinium** [comment]
Thanks, @autonomousapps . I highly appreciate your and @stephanenicolas work and I am looking forward to seeing it in the next release!

**Comment by autonomousapps** [comment]
This is now resolved. https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/pull/143
