### ISSUE TITLE
Fail early if used on an incompatible version set

### ISSUE THREAD

**Issue by satyarths** [autonomousapps/dependency-analysis-android-gradle-plugin#133]
**Is your feature request related to a problem? Please describe.**
The errors caused when using the plugin with unsupported versions is not very intuitive. They often point to missing classes in Gradle,AGP or other dependencies of this plugin. 

**Describe the solution you'd like**
We could have a supported version check at the plugin initialization which would fail fast if the it is below the supported versions.

**Describe alternatives you've considered**
The current approach involves explicitly mentioning the supported versions on the read me and while creating an Issue. However IMO it would save both you and the library user effort if these versions were more explicitly enforced on the codebase :) 

**Additional context**
I'd be happy to help in adding this if you're open to contributions.

**Comment by autonomousapps** [comment]
Please be more explicit. Which incompatible version of which thing did you
experience? I already have a version check for AGP and emit a warning if
it's outside of the known good range.

**Comment by satyarths** [comment]
Sorry about that, 
I stumbled on the issue while trying to use it with 3.6.2 and also Gradle 6.0  .   I rechecked this with the versions mentioned on the ReadMe, the issues and just digging through source code to identify the errors. 
Eg: 
- While using on a Gradle version lower than < 6.1 leads to #116 . 
This could be a non-issue too. In that case , please go ahead and close the issue 👍

**Comment by autonomousapps** [comment]
A check for min gradle version (6.1 currently) would not be bad. If you want to contribute that, I welcome it. You can look at the existing check for AGP version in `DependencyAnalysisPlugin`. In this case however, it should throw a `GradleException` rather than simply printing a warning.

**Comment by satyarths** [comment]
Sounds good. 
After going through the code for AGPVersion, I had a question. 
Would you want to create a wrapper for GradleVersion, or can we use the one that Gradle provides


In case of the AGP version check. I see that it states that it would work for versions greater than 3.5.3, however it does not work for 3.6.2. (This fact is  also mentioned in the doc). Do you think this should also be addressed by the check for AGP Version

**Comment by autonomousapps** [comment]
You can use GradleVersion directly.

It does work for 3.6.2. My policy is simply to only test for the latest
patch release for each minor version.
