### ISSUE TITLE
Add more metadata to build scans

### ISSUE THREAD

**Issue by autonomousapps** [autonomousapps/dependency-analysis-android-gradle-plugin#138]
Use env vars present during Github Actions: https://help.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables

Here's a sample workflow URL: https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/pull/137/checks?check_run_id=631365883, which clearly could be built from available information and attached to the scan.

**Comment by pavlospt** [comment]
Would it be possible to add more info on what you want to achieve? I can help on this ticket I think but I am unclear of the end goal :smile: !

**Comment by autonomousapps** [comment]
This is more of a "nice to have" than anything else. I think one thing I'd like is a link on the build scan to the github action url that triggered it. You can look up the build scan / gradle enterprise plugin docs to see how to add links to scans, and then look at the env vars made available by default by github, and put the two together! :)
