### ISSUE TITLE
Runtime retained annotations and their class arguments are not taken into account 

### ISSUE THREAD

**Issue by stephanenicolas** [autonomousapps/dependency-analysis-android-gradle-plugin#142]
Using Dagger, we have a class that is annotated using `@Module`: 

```
//in FooModule.java
@Module( includes = BarModule.class } 
class FooModule {}
```

the plugin detect that the module `:bar` which contains `BarModule` as unused (0.40-SNAPSHOT).

`@Module` has a runtime retention policy in dagger.

When looking at the bte code of `FooModule`, the annotation `@Module` and its arguments are only visible in the constant pool.

**Comment by autonomousapps** [comment]
I'm pretty sure `@Module` _is_ taken into account, but it's possible that the argument is missed somehow. Will look into it. Thanks for the report.

**Comment by autonomousapps** [comment]
I cannot reproduce this. See https://github.com/autonomousapps/dependency-analysis-dagger-issue. Help me fix the reproducer to show your issue.

**Comment by stephanenicolas** [comment]
@autonomousapps I close the issue has it seem to have got solved by rebasing on master.
Thx a lot for setting up the other project, it helped me to realize that there was no issue .
