### ISSUE TITLE
JavaDoc references are not considered to be usages

### ISSUE THREAD

**Issue by Paladinium** [autonomousapps/dependency-analysis-android-gradle-plugin#147]
**Plugin version**
0.41.0

**Gradle version**
6.3

**Android Gradle Plugin (AGP) version**
None

**Describe the bug**
Unused dependencies are detected if a module references classes from a dependency **only via JavaDoc**. E.g.:

```
import com.my.other.DependencyClass;
/**
 * Using JavaDoc's link, e.g. {@link DependencyClass}, is not detected as reference.
 */
public class MyJavaClass {}
```

**Expected behavior**
JavaDoc links should be detected as class usages.

**Comment by autonomousapps** [comment]
It's highly unlikely I will attempt to detect usage in javadoc. It would require significant effort to parse that source, for minimal gain. What's the use-case for this? Why are you referencing a class you don't actually use in a javadoc?

**Comment by autonomousapps** [comment]
As I mentioned in the related issue, this might actually be fixed as a side effect, assuming the javadoc usages are imported (vs using fully-qualified references in the javadoc). I'm going to close this for now. Feel free to reopen if you wish to discuss a specific use-case.

**Comment by Paladinium** [comment]
I save you the details about the use-cases since the solution you found in #148 also works for that. Thanks!
