### ISSUE TITLE
Generic references are not considered to be usages

### ISSUE THREAD

**Issue by Paladinium** [autonomousapps/dependency-analysis-android-gradle-plugin#148]
**Plugin version**
0.41.0

**Gradle version**
6.3

**Android Gradle Plugin (AGP) version**
None

**Describe the bug**
Unused dependencies are detected if a module references classes from a dependency **only via generics**. E.g.:

```
import com.my.other.DependencyClass;
import java.util.Optional;

public interface MyJavaClass {
     Optional<DependencyClass> getMyDependency();
}
```

**Expected behavior**
Types used in generics should be detected as class usages.

**Potential workaround**
A workaround would be possible if #147 was fixed because the class appearing in the generic could be mentioned in JavaDoc.

**Comment by autonomousapps** [comment]
Thanks for this bug report. I will take a look!

**Comment by autonomousapps** [comment]
I have a resolution for this, which leans on some prior art. Basically I look at dependencies that have been imported. So if I see `import com.my.other.DependencyClass;` in proj-a, and proj-a depends on proj-b, which contributes `com.my.other.DependencyClass`, then it will no longer report proj-b as unused by proj-a.

It's a bit of a broad brush, but to get deeper I think I'd need to expand my source-parsing to explicitly looking for generics. I would like to do that, but it will take time to update the grammar.

As an aside, this might also fix your javadoc issue, if the types referenced in your doc are imported (vs. using fully-qualified names in the doc).

**Comment by Paladinium** [comment]
Excellent, @autonomousapps, thanks a lot. Any chance you could publish a new release v0.42.0?

**Comment by autonomousapps** [comment]
It'll happen soon.
