### ISSUE TITLE
Dependency not detected when only Constants are used

### ISSUE THREAD

**Issue by Naitbit** [autonomousapps/dependency-analysis-android-gradle-plugin#149]
**Plugin version** 0.41.0

**Gradle version**  6.3

**Android Gradle Plugin (AGP) version** 3.6.3

**Describe the bug**
Dependency is displayed as unused if only constants are references.

**To Reproduce**
1. Create project with constants, fe:
const val CONST_A = "AAAA"
const val CONST_B = "BBBB"
2. add it as a dependency to different project and use constants
3. Run plugin

**Expected behavior**
Plugin does not list module as `Unused dependencies`

**Additional context**
I'm not sure if it is possible to fix, as compiler will likely inline constants so the are only visible from source code, not from bytecode.
If that is the case maybe it should be mentioned in Compatibilities & Limitations.

**Comment by autonomousapps** [comment]
The plugin does make a best effort to detect constant usage. For Java projects, it parses the constant pool. For Java and Kotlin projects, it parses source code for import statements and connects them to constants it detects when analyzing the bytecode of upstream/supplier projects. So, this should work. Can you elaborate on how your project is adding these constants? Is it referencing them by fully-qualified class name, or does it import them?

**Comment by Naitbit** [comment]
In all cases constants were imported.
It was also Kotlin code calling Kotlin code.

**Comment by autonomousapps** [comment]
Can you try the latest 0.41.1-SNAPSHOT and tell me if you still see this? I honestly don't think you should see it even in 0.41.0, but 🤷 

Instructions for snapshot usage at https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/wiki/Adding-to-your-project#with-plugins-block-and-the-maven-central

**Comment by autonomousapps** [comment]
@Naitbit any more information on this?

**Comment by Naitbit** [comment]
Just tried with `0.43.0-SNAPSHOT` Still got 
```
Unused dependencies which should be removed:
implementation(project(":utils:java:links"))
```
where `":utils:java:links` is  `id 'kotlin'` subproject and suggestion was made for `com.android.library`

all of the links were `const val` `Strings`

Got the same case between two `com.android.library` projects
for `const val CONSTANT = 1`

**Comment by autonomousapps** [comment]
Thank you! I have been able to reproduce this and have a provisional fix. This should be able to go out in the next release.

**Comment by autonomousapps** [comment]
Resolved by https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/pull/180
