### ISSUE TITLE
FR - Post-processing hook

### ISSUE THREAD

**Issue by ZacSweers** [autonomousapps/dependency-analysis-android-gradle-plugin#15]
Alternative to #14. This could be a generic hook to handle parsed data and allow the consumer to perform custom operations in reaction to it. This could be used for verification, patching, or other stuff.

Some custom ones could be available as batteries-included options for generic build.gradle file modifications.

**Comment by autonomousapps** [comment]
I think the best way to do post-processing, without waiting for it to somehow be baked in, is to use the public task APIs that are already available, and configure them. For example, you could hook into the root level `AdviceAggregateReportTask` and flatMap its outputs into your custom gradle task, which can read the file outputs into the public model classes (`BuildHealth`, `Advice`, `PluginAdvice`, and `Dependency`), and then do whatever. If this is true, than a way to resolve this ticket would be to write some documentation on how to do that.

That said, if the goal is to rewrite gradle scripts based on the output of gradle tasks, I'm not sure how well that works. I don't know if anything physically prevents it, but it seems "wrong" :tm: 

A (perhaps) ideal way to achieve this goal would be through an IDE plugin. That, however, is a whole 'nother project I don't have time for right now :)

**Comment by ZacSweers** [comment]
Sounds good to me! I think a batteries-included sample or task would probably be useful as guidance for simple build files

**Comment by autonomousapps** [comment]
I'll take a look at writing some guidance on how to manage that at an external level.
