### ISSUE TITLE
Add detection for OkHttp runtime dependency security providers

### ISSUE THREAD

**Issue by Naitbit** [autonomousapps/dependency-analysis-android-gradle-plugin#153]
OkHttp detects available Security Providers at runtime. Try to detect those dependencies as used if they are used in same project as OkHttp Dependency.

Current list of OkHttp security providers:
https://github.com/square/okhttp/blob/593cfeb392f322bbb1033743ddc2ea39134e1e22/docs/security_providers.md

Alternative:
Blacklist dependencies like conscrypt to not be mentioned as unused.

**Comment by autonomousapps** [comment]
I've done a bit of research, and I see that all security providers must extend the `java.security.Security` class. As a first pass, I could easily detect if a class extends that and blacklist it from being suggested for removal. As a second pass, I could search bytecode for usages of `java.security.*` classes, and only if those are found, blacklist the discovered security providers. If no such usages are found, this suggests the security provider isn't used and could be safely removed.

**Comment by autonomousapps** [comment]
@Naitbit can you share the specific dependency declaration you're using for conscrypt? I want to ensure I have an accurate test case.

**Comment by autonomousapps** [comment]
I've merged a PR to address this. The effect is that any dependency that supplies a security provider (such as conscrypt) is no longer a candidate for removal. Ideally I'd have some way to detect if a security provider were even desired so that we're not just whitelisting all of them, but there are issues there (see comment on PR). For now, closing this issue.

**Comment by Naitbit** [comment]
I did my previous test with
com.squareup.okhttp3:okhttp:4.3.1
org.conscrypt:conscrypt-android:2.4.0
