### ISSUE TITLE
FR - Infer if an android project could be a plain java/kotlin project

### ISSUE THREAD

**Issue by ZacSweers** [autonomousapps/dependency-analysis-android-gradle-plugin#16]
If a project is an android project but doesn't use any android APIs, AAR deps, or android resources, it could suggest this project could be a plain java/kotlin project and avoid being tied solely to android.

**Comment by autonomousapps** [comment]
Do you think it would be sufficient if there were no usages of any class in the `android.*` package?

**Comment by ZacSweers** [comment]
Not necessarily, there could be aar dependencies as well.

**Comment by autonomousapps** [comment]
So, no direct usages of android.jar (i.e., nothing from `android.*`), and no `.aar` files on the classpath. Do I need to care about runtime vs compile classpath for this? Is it possible a project doesn't need anything android to compile, but expects it at runtime?

I think implementing this wouldn't necessarily be very hard. Once we agree on an appropriate set of criteria, I can write it up and implement myself or offer guidance for someone to offer a PR.

**Comment by ZacSweers** [comment]
That sounds about right. The other components would be 
- not using any classes in those AARs. 
- not have any Android resources

Some other more-obscure things might be
- use of BuildConfig
- use of R.class
- specified proguard rules file

**Comment by ZacSweers** [comment]
Actually just to edit - a proguard rules file wouldn't preclude it from being a jvm library, since it can just embed it in its jar resources instead

**Comment by autonomousapps** [comment]
This will be released as 1.10.0.
