### ISSUE TITLE
FR - Allow whitelisting certain dependencies as intentionally declared (even if unused)

### ISSUE THREAD

**Issue by ZacSweers** [autonomousapps/dependency-analysis-android-gradle-plugin#17]
Some projects could expose `api` deps that exist as a base project with common deps. Being able to intentionally whitelist these would be useful, possibly via `because()` argument.

An `implementation` dependency could be warned in this case as useless.

**Comment by autonomousapps** [comment]
There is partial support for this via a mechanism added in v0.19.2 (latest at time of writing). Please take a look at the readme ([this section](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin#failure-conditions)) and let me know if that solves your problem, or if you think something closer to your specific semantics would be generally useful.

**Comment by dsvensson** [comment]
The documentation doesn't sound like it can exclude specific unused dependencies from the report?

**Comment by autonomousapps** [comment]
@dsvensson indeed it can do that
```
dependencyAnalysis {
  issues {
    onUnusedDependencies {
      warn("some:dep") // or
      fail("some:dep")
    }
  }
}
```
It may not look intuitive, but that's how you do it. I have an open issue where I've begun to think aloud about an improved DSL https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/67

**Comment by dsvensson** [comment]
Weird... I still get the following in the output:

```
Unused dependencies which should be removed:
- implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.70")
- implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.2")
```

**Comment by autonomousapps** [comment]
Can you share your configuration?

**Comment by autonomousapps** [comment]
Closing for now. Feel free to reopen if you have more information.
