### ISSUE TITLE
Kotlin inline function not detected as lib usage

### ISSUE THREAD

**Issue by stephanenicolas** [autonomousapps/dependency-analysis-android-gradle-plugin#173]
We have a kotlin module using the artifact: 
`com.jakewharton.threetenabp:threetenabp:1.2.1`

especially the inline function: `import org.threeten.bp.temporal.TemporalAdjusters.firstDayOfMonth`

and the lib is recognized as unused dependency.

**Comment by autonomousapps** [comment]
There's something a bit weird here. As far as I can tell, `org.threeten.bp.temporal.TemporalAdjusters.firstDayOfMonth` is _neither_ an inline function _nor_ a member of the JakeWharton/ThreeTenABP project. It is instead a static function in the core [ThreeTenBP](https://www.threeten.org/threetenbp/) project.

I don't know what the actual problem is, nor the expectation.

Looking at the JW project, it looks like the only place that needs his artifact is your custom `Application` class, where you are meant to call `AndroidThreeTen.init(this)`, and otherwise you're just using the core ThreeTenBP project, which is provided as an `api` dependency.

Per the design philosophy of this plugin, if you're using a transitive dependency, you're wrong and should declare it directly. If a user finds this to be an unsatisfying answer, they can ignore certain dependencies with the DSL.

**Comment by autonomousapps** [comment]
@stephanenicolas any more information on this?

**Comment by kyhule** [comment]
I think I am running into this issue. I have a very small android library module that references a single inline function from `androidx.core:core-ktx:1.3.0`. The library module declares this dependency as `implementation`. Running `adviceDebug` on the library module reports the following:
```
Unused dependencies which should be removed:
- implementation("androidx.core:core-ktx:1.3.0")

Transitively used dependencies that should be declared directly as indicated:
- api("com.google.dagger:dagger:2.28.3")
- api("javax.inject:javax.inject:1")
- implementation("androidx.core:core:1.3.0")
```

This is the inline function that is being used:
```kotlin
inline fun <reified T : Any> Context.getSystemService(): T? =
        ContextCompat.getSystemService(this, T::class.java)
```
I understand the transitive usage of `androidx.core:core:1.3.0` but it should not be telling me to remove `androidx.core:core-ktx:1.3.0`.

Unfortunately, I attempted to create a small example project but I am not able to reproduce there so now I am even more confused. Let me know if you have any ideas on how to provide any additional details.

**Comment by autonomousapps** [comment]
@kyhule thanks for the report. There are two things you could tell me:
1. provide a usage example so I can see _exactly_ how you're using this, including your import statement
2. could you share the contents of `<module>/build/reports/dependency-analysis/debug/intermediates/inline-usage.json`

**Comment by kyhule** [comment]
I went back to my minimal working example to push it up so you could at least see how I have it set up in my real project. I did a quick comparison and found a difference that I originally missed. The lib module in my real project was setting and using the directory `src/main/kotlin` and adding it in the sourceSets via `main.java.srcDirs += 'src/main/kotlin'`. Once I made that change, I was able to successfully reproduce. Here is a minimal working example:
- The main branch reproduces the false positive: https://github.com/kyhule/unused-ktx-false-positive
- This branch does not: https://github.com/kyhule/unused-ktx-false-positive/tree/java-srcDir-fixes-false-positive
The the output of running `buildHealth` is included on each respective branch.

**Comment by autonomousapps** [comment]
If instead of
```groovy
sourceSets {
  main.java.srcDirs += 'src/main/kotlin'
}
```
you used
```groovy
android {
  sourceSets {
    main.java {
      srcDir 'src/main/kotlin' // this function adds a single directory
    }
  }
}
```
then this problem would be solved.

So, two things:
1. I do think it is more correct to use `android.sourceSets` for an Android project. The bare `sourceSets` is for Java libraries.
2. I believe I should support your use-case nonetheless, and will work to resolve it.

**Comment by kyhule** [comment]
Thanks for the advice. This looks like one of those things that everyone just copy/pastes into a new module's build.gradle in our project not considering what type it is, especially given this is in every one of our build.gradles even for projects that don't even use a `kotlin` source directory.
