### ISSUE TITLE
Cannot identify ComponentIdentifier subtype. Was OpaqueComponentIdentifier, named Gradle API

### ISSUE THREAD

**Issue by eugene-krivobokov** [autonomousapps/dependency-analysis-android-gradle-plugin#199]
**Build scan link**
https://scans.gradle.com/s/3zjh7xrjmnnvu/failure

**Plugin version**
0.48.0

**Gradle version**
6.3

**Android Gradle Plugin (AGP) version**
3.6.2, 3.6.3

**Describe the bug**
`buildHealth` task fails with an exception.

**To Reproduce**
1. Checkout https://github.com/avito-tech/avito-android
1. Checkout branch `MBS-8670-reproducible-example-issue-199`
1. `./gradlew -p subprojects buildHealth`

**Expected behavior**
Produce a report.

**Additional context**
It works in 0.38.0, 0.39.0.

**Comment by autonomousapps** [comment]
Thanks for the report. It's very curious that the "name" of the artifact involved is "Gradle API". I'll take a look at your reproducer, but in the meanwhile do you have any idea why that would be?

**Comment by autonomousapps** [comment]
Ah interesting https://github.com/avito-tech/avito-android/blob/develop/subprojects/gradle/kotlin-dsl-support/build.gradle.kts#L8

I'll have to consider how best to handle this.
