### ISSUE TITLE
Add a single dependencyHealth task

### ISSUE THREAD

**Issue by vlsi** [autonomousapps/dependency-analysis-android-gradle-plugin#2]
I'm not sure if dependencies must be analyzed for each "source set", however, I would suggest to have an umbrella task always.
Then people would not have to remember what to execute.

For instance:

```
$ ./gradlew dependencyHeath

...

Declared as `api`, but could be `implementation` or `runtimeOnly`
-------------------------------

commons-io:commons-io is declared as api, but it is not used in public APIs, so it should be declared as implementaion
...


Declared as `implementation`, but could be `runtimeOnly`
--------------------

commons-codec:commons-codec is declared as implementation, but it is not really used for compilation. Should it be runtimeOnly?
...

Unused dependencies
----------------
com.fasterxml.jackson.core:jackson-databind is declared as implementation, but it is unused.


Used, but undeclared
--------------
org.apache.commons:commons-lang3 is declared in 
"DEF is not explicitly declared in dependencies, but its clases are used. Consider declaring the dependency explicitly as implementation(...)"
"G is declared as api, and it is not used"
...
```

and so on.

**Comment by autonomousapps** [comment]
Thanks for the feedback.

**Comment by autonomousapps** [comment]
I added a task called `buildHealth` on the root project (you must apply the plugin to the root project). It depends on both the misused dependencies task and the ABI analysis task. It doesn't quite reach the level of output you want, but it's a step in that direction, and I'm going to close this ticket. We'll get there!

https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/commit/2ec25967918b1705fc30b5f3e0fad67653844f9a
