### ISSUE TITLE
How could I disable verbose output

### ISSUE THREAD

**Issue by sboishtyan** [autonomousapps/dependency-analysis-android-gradle-plugin#202]
`chatty(false)` is no-op now. Do I have an opportunity to disable console output?

**Comment by autonomousapps** [comment]
Thanks for asking. I have made an effort with recent releases to reduce console output by default. Do you find this is still too verbose?

**Comment by sboishtyan** [comment]
Yes, we have a lot of modules around 300 and a lot of plugins and they all want to print something
Now your plugin makes a lot of noise in the logs
It makes hard to read logs and I prefer to look for your plugin advice only in files

**Comment by autonomousapps** [comment]
Thanks for the response. Would you like the ability to suppress _all_ output from this plugin?

**Comment by sboishtyan** [comment]
It would be enough for me.

**Comment by autonomousapps** [comment]
I'm not sure I want to make this an extension method (like chatty), but I'm also not totally opposed to it. What about using a system property to disable it? You could do it via the command line or in `gradle.properties`.

**Comment by sboishtyan** [comment]
For me, it would be enough. Feel free to make any design decision you think fits for your vision

**Comment by autonomousapps** [comment]
Note to self, I think I only need to disable logging in the `AdviceSubprojectAggregationTask` class. This is one of only two places where `logger.quiet` is used. The other is `FailOrWarnTask`, which runs just once per invocation of `buildHealth`, compared to once per subproject for the `Advice...` task.

**Comment by autonomousapps** [comment]
I have resolved this by adding a system property the plugin will respond to. If you add
```
systemProp.dependency.analysis.silent=true
```
to `gradle.properties`, then logging will be greatly reduced. You may also use `-Ddependency.analysis.silent=true` on the command line.

This has not yet been published, but is available as a snapshot if you want to test.
