### ISSUE TITLE
buildHealth hooks into assemble task, which confuses builds

### ISSUE THREAD

**Issue by ZacSweers** [autonomousapps/dependency-analysis-android-gradle-plugin#204]
**Plugin version**
0.49

**Gradle version**
6.5

**Android Gradle Plugin (AGP) version**
4.0

**Describe the bug**
The analysis plugin hooks into assemble tasks, which studio uses for `Make Project`. This makes local builds slower for developers on our team unknowingly, and worse if a post-processing task is also applied. I think this hook should be slightly different or more configurable

**Comment by autonomousapps** [comment]
Unless I am not remembering correctly, this plugin does not use any assemble task. It _does_ depend on various compilation tasks, as well as some jar tasks. I cannot think of a way for this plugin to do its work _without_ hooking into those tasks, unless I give up on the idea of consuming tasks and just use fileTree for everything.

I'm actually confused how this could be an issue. The plugin adds task that depend on compilation tasks, yes, but they don't force those tasks to run. E.g., I'm not saying `compileKotlin.dependsOn buildHealth` or whatever. Is AS or IDEA doing something weird with `Make project`?

One option to handle this use-case would be to detect if a build is run in AS (there is at least one well-known project or system property set), and in that case disable itself.

nb: it's possible I forget how my own plugin works and running `assembleDebug` somehow also triggers buildHealth-related tasks.

**Comment by autonomousapps** [comment]
My current understanding, based on our conversation in slack, is that this is only happening in the IDE, as a result of some weirdness with how **Make project** and the gradle TAPI work. As a workaround, I will add some code to detect if the plugin is running in the IDE and, if so, disable it.

**Comment by autonomousapps** [comment]
I think this is now resolved, but I haven't tested the snapshot yet. Please let me know if/when you get a chance.

**Comment by autonomousapps** [comment]
There's actually an issue with my original implementation in 0.50. 0.52, which I will release today, resolves it.

**Comment by autonomousapps** [comment]
I believe this is now fully resolved with 0.52.0, just released.
