### ISSUE TITLE
FR - Dependencies added by plugins but aren't declared directly

### ISSUE THREAD

**Issue by ZacSweers** [autonomousapps/dependency-analysis-android-gradle-plugin#21]
A good example of this is "org.jetbrains:annotations", which is added by the kotlin plugin and shows up as a "used transitive dependency" of unused dependencies written in kotlin.

**Comment by autonomousapps** [comment]
I'm not sure how to detect that a dependency is added by a plugin. Any ideas?

**Comment by ZacSweers** [comment]
No clue :/. Maybe some hook for when a plugin is applied and record
dependencies added during that?

**Comment by autonomousapps** [comment]
I've talked with some gradle folk, and there isn't any way to do this right now. The best we could do is probably whitelist some dependencies based on pre-existing knowledge that plugin X adds dependency Y. I've already done a bit of this for databinding and viewbinding.

If you helped provide a list of such well-known dependency-plugin relationships, I could either add that feature or provide some guidance on PRing it.

**Comment by autonomousapps** [comment]
Closing as impossible. Feel free to re-open (or, even better, open new issues), if you have whitelist candidates.
