### ISSUE TITLE
Incorrect Advice to replace dependence from `implementation` to `testImplementation`

### ISSUE THREAD

**Issue by sboishtyan** [autonomousapps/dependency-analysis-android-gradle-plugin#211]
gradle=6.5
plugin=0.50
agp=3.6.2 but in this module, it isn't used 
branch for reproducing: https://github.com/avito-tech/avito-android/tree/dependencies-analysis-0.50

**Describe the bug**
1. `./gradlew -p subprojects buildHealth`
2. Look at `subprojects/gradle/upload-cd-build-result/build/reports/dependency-analysis/advice-all-variants-pretty.json`
3. `{
      "dependency": {
        "identifier": ":gradle:git",
        "configurationName": "implementation"
      },
      "usedTransitiveDependencies": [],
      "fromConfiguration": "implementation",
      "toConfiguration": "testImplementation"
    }`
4. Do what advice says
5. `make publish_to_maven_local` from the project root dir
6. Get compile error
`e: /Users/sergey/projects/avito-android-infra/subprojects/gradle/upload-cd-build-result/src/main/kotlin/com/avito/cd/UploadCdBuildResultTask.kt: (4, 18): Unresolved reference: git
e: /Users/sergey/projects/avito-android-infra/subprojects/gradle/upload-cd-build-result/src/main/kotlin/com/avito/cd/UploadCdBuildResultTask.kt: (5, 18): Unresolved reference: git
e: /Users/sergey/projects/avito-android-infra/subprojects/gradle/upload-cd-build-result/src/main/kotlin/com/avito/cd/UploadCdBuildResultTask.kt: (57, 32): Unresolved reference: gitState
e: /Users/sergey/projects/avito-android-infra/subprojects/gradle/upload-cd-build-result/src/main/kotlin/com/avito/cd/UploadCdBuildResultTask.kt: (57, 65): Expression expected, but a package name found
e: /Users/sergey/projects/avito-android-infra/subprojects/gradle/upload-cd-build-result/src/main/kotlin/com/avito/cd/UploadCdBuildResultTask.kt: (79, 19): Unresolved reference: GitState
`

**Expected behavior**
Advice is correct and module compiles and publishes to maven local

**Comment by autonomousapps** [comment]
Thank you for the report and reproducer. I hope to resolve this soon.

**Comment by autonomousapps** [comment]
Looks like there's a related issue:
```json
  {
    "dependency": {
      "identifier": "com.google.code.gson:gson",
      "resolvedVersion": "2.8.5",
      "configurationName": "implementation"
    },
    "usedTransitiveDependencies": [],
    "fromConfiguration": "implementation",
    "toConfiguration": "testApi"
  }
```
`testApi` does not make any sense as a configuration.
