### ISSUE TITLE
analyzeClassUsageMain task failed on 0.53.0

### ISSUE THREAD

**Issue by gotson** [autonomousapps/dependency-analysis-android-gradle-plugin#224]
**Build scan link**
https://scans.gradle.com/s/733xjdupl346g

**Plugin version**
0.53.0

**Gradle version**
6.5.1

**Android Gradle Plugin (AGP) version**

**Describe the bug**
Gradle build fails:

```
There was a failure while executing work items
> A failure occurred while executing com.autonomousapps.tasks.ClassListAnalysisWorkAction
  > java.nio.ByteBuffer.limit(I)Ljava/nio/ByteBuffer;
```

**To Reproduce**
You can pull the branch `code-cleanup` from junrar/junrar: https://github.com/junrar/junrar/tree/code-cleanup
Change the dependency version to 0.53.0, and run `buildHealth`

**Expected behavior**
Task should suceed.

**Additional context**

**Comment by autonomousapps** [comment]
That branch doesn't seem to exist anymore?

**Comment by autonomousapps** [comment]
Ugh. I'm almost certain that what happened is that I inadvertently built 0.53.0 with Java 9 instead of Java 8 🤦 

I can get `buildHealth` to fail if I use the binary 0.53 that I published, and it succeeds if I build from scratch with it as an included build (building with Java 8). I'll push out a 0.53.1 to resolve this.

**Comment by autonomousapps** [comment]
Ok, 0.53.1 has been published. It should already be available from the Gradle Plugin Portal, and will be on Maven Central once it syncs. Can you confirm that this version resolves your issue?

**Comment by gotson** [comment]
> That branch doesn't seem to exist anymore?

it's been merged to `master`.

> Ugh. I'm almost certain that what happened is that I inadvertently built 0.53.0 with Java 9 instead of Java 8 🤦
> 
> I can get `buildHealth` to fail if I use the binary 0.53 that I published, and it succeeds if I build from scratch with it as an included build (building with Java 8). I'll push out a 0.53.1 to resolve this.

That's why you need CI/CD ;)

> Ok, 0.53.1 has been published. It should already be available from the Gradle Plugin Portal, and will be on Maven Central once it syncs. Can you confirm that this version resolves your issue?

I'll give it a try.

**Comment by autonomousapps** [comment]
I use Github Actions for CI, and I have automated the publication of snapshots, but I do not yet publish releases in an automated way. This project has dozens of end-to-end tests that run against a matrix of Gradle and Android versions, and which takes about two hours :P It does not, unfortunately, run against multiple JDKs yet....

**Comment by gotson** [comment]
> Ok, 0.53.1 has been published. It should already be available from the Gradle Plugin Portal, and will be on Maven Central once it syncs. Can you confirm that this version resolves your issue?

I confirm `0.53.1` fixes the issue.
