### ISSUE TITLE
In DependencyAnalysisPlugin.kt: "This plugin is only known to work with versions of AGP between" is unclear

### ISSUE THREAD

**Issue by stephanenicolas** [autonomousapps/dependency-analysis-android-gradle-plugin#230]
During build time, the following log is generated by the plugin: 
"This plugin is only known to work with versions of AGP between.."

It is not clear which plugin is logging this. Can you replace it by 
"The dependency analysis android gradle plugin is only known to work with versions of AGP between"?

Thx in advance.

**Comment by autonomousapps** [comment]
I think (but not with 100% certainty) that info or debug level logging would indicate the plugin the message is coming from. That said, I agree it can be confusing and that we can improve this message 👍

**Comment by autonomousapps** [comment]
This is now on main (but unreleased).
