### ISSUE TITLE
[Feature Request] allow to dump the public API of modules?

### ISSUE THREAD

**Issue by martinbonnin** [autonomousapps/dependency-analysis-android-gradle-plugin#237]
How feasible would it be to have an option to dump the public API of a project/module? That could be used to detect API changes/breakages by comparing the latest public API with the one that is checked in source control. 

The functionality would be very similar to [Japicmp](https://github.com/siom79/japicmp) except easier to work with in a CI pipeline as it's often tedious to find the jar to compare with when using JapiCmp. 

From my first quick look, this plugin is able to inspect the methods/classes and already has a notion of [ABI-filtering](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/wiki/ABI-filtering). That seem like a good place to start dumping the public API of a module. 

This is certainly a stretch but I think it could be a useful for library maintainers to keep control of their API surface. Would you be open to such an addition? Any other thoughts?

**Comment by autonomousapps** [comment]
The plugin already does this. You should see a file in the intermediates subdirectory called abi-dump.txt. Take a look and let me know what you think about the format. 
GitHub <notifications@github.com> wrote:
“How feasible would it be to have an option to dump the public API of a project/module? That could be used to detect API changes/breakages by comparing the latest public API with the one that is checked in source control.

The functionality would be very similar to Japicmp except easier to work with in a CI pipeline as it's often tedious to find the jar to compare with when using JapiCmp.

From my first quick look, this plugin is able to inspect the methods/classes and already has a notion of ABI-filtering. That seem like a good place to start dumping the public API of a module.

This is certainly a stretch but I think it could be a useful for library maintainers to keep control of their API surface. Would you be open to such an addition? Any other thoughts?”

**Comment by martinbonnin** [comment]
Awesome 😃 

The format looks good. Now it's just missing some code to do the diffing and break the build on ABI changes. I might give it a shot at some point.

**Comment by autonomousapps** [comment]
Would love to have that contribution! Please file an issue so we can track it.
GitHub <notifications@github.com> wrote:
“Awesome 😃

The format looks good. Now it's just missing some code to do the diffing and break the build on ABI changes. I might give it a shot at some point.”

**Comment by autonomousapps** [comment]
The first step here is to generalize this to include Java. Right now we only do the ABI dump for Kotlin, and it's a byproduct of the Kotlin-specific ABI analysis.

**Comment by autonomousapps** [comment]
I think the first step here is to expose that abi-dump task output to users via the DSL, in the same way we currently expose the result of `buildHealth` for post-processing. This would automatically enable ad hoc post-processing of that dump file in any way the user saw fit. We might then iterate and create a "batteries included" version. The real tricky part is actually holding onto old dumps for diffing purposes. That would have to be user-specific. They would need to upload the file somewhere, for example, and then download it when comparing to new builds.

**Comment by martinbonnin** [comment]
> The real tricky part is actually holding onto old dumps for diffing purposes. That would have to be user-specific. They would need to upload the file somewhere, for example, and then download it when comparing to new builds.

I was thinking about committing them in source control. Firebase does this for an exemple: https://github.com/firebase/firebase-android-sdk/blob/master/firebase-crashlytics/api.txt

It's convenient because the repo becomes "standalone", you can get the history of the API for a module by looking at the git history. And it's easy to check backward compatibility in CI.

For some more context, I also looked into japicmp and bumped into this exact problem. Some projects using japicmp download the latest release jar to compare against but it's sometimes hard to get the "latest release" (it's bintray or sonatype specific). And also, it doesn't track changes per-commit.

**Comment by sboishtyan** [comment]
> I was thinking about committing them in source control
I agree with @martinbonnin. It looks useful for CI scenarios

**Comment by autonomousapps** [comment]
@martinbonnin do you want to work with me to get the associated PR done? Given that you have a real use-case, I'd like to ensure that whatever I do meets your needs and not just my fantasy of a real need.

**Comment by martinbonnin** [comment]
Hi 👋 
The main use case I have in mind would be to replace [Metalava](https://android.googlesource.com/platform/tools/metalava/) in [apollo-android gradle scripts](https://github.com/apollographql/apollo-android/blob/main/buildSrc/src/main/kotlin/MetalavaHelper.kt)

`apollo-android` is moving more and more modules to multiplatform though and I'm not sure what the status is there.  In a perfect world, I would do things in this order:
1. Add multiplatform support to `dependency-analysis-android-gradle-plugin` (#228)
1. Apply the plugin in `apollo-android` (I made a bunch of tests earlier but never got it to a point where it could be merged
1. Add public API dumps (this issue)

Now we don't live in a perfect world so I'm happy to look into this issue first. I want to clean the apollo build scripts this week, I'll take that opportunity to apply the plugin again and investigate where to start.

**Comment by autonomousapps** [comment]
That's all very fair. I would also be happy to work with you on improving KMP support. I've never had such a project, so I have very little insight into how it works at the tooling level.

Regarding the ABI issue, I'll probably merge the associated PR but leave this issue open.

**Comment by martinbonnin** [comment]
I've been playing a bit with multiplatform support there: https://github.com/martinbonnin/dependency-analysis-android-gradle-plugin/tree/multiplatform. With multiplatform + android + application + java + etc..., the matrix of possible configurations becomes quite daunting... 👻 

All in all I'm starting to think maybe dependencies-analysis and abi-compatibility-checks are better left orthogonal after all. Would it be possible to make the plugin more modular so that I could use e.g. `AbiAnalysisTask` and dump the ABI without having to configure all the multiplatform projects?

**Comment by autonomousapps** [comment]
Simply applying the plugin in the default configuration results in adding tasks to all compatible projects. And even more to the point, gradle always configures all projects in a build, unless you use configuration-on-demand. So I don't really understand what you mean by "without having to configure all the multiplatform projects."

You can of course run the abi analysis tasks independent of `buildHealth` -- there's no need for the full buildHealth analysis if you only want the ABI dumps.

Finally, you can also tell the plugin _not_ to apply itself to all subprojects, if you want finer-grained control over it. See [the wiki](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/wiki/Customizing-plugin-behavior#controlling-the-projects-on-which-the-plugin-is-applied). If you do that, you will need to manually apply the plugin to any subproject you want to analyze.

**Comment by martinbonnin** [comment]
> So I don't really understand what you mean by "without having to configure all the multiplatform projects."

Indeed, "configure" is a loaded word in the Gradle context, I shouldn't have used that word. I meant without having buildHealth support multiplatform projects. 

> You can of course run the abi analysis tasks independent of buildHealth -- 

This is what I meant. Maybe with some helper "extension"/API to make configuration a bit easier.

> there's no need for the full buildHealth analysis if you only want the ABI dumps.

I _feel_ like there's slightly more to it than passing the `jar` file (or is it the `.class` files?) to the `abi analysis task`. I was under the impression that there's also some configuration involved like the exclusions that would make sense to share between `buildHealth` and `dumpAbi`. But again, I'm not 100% clear how this all works yet, I'll keep digging.

**Comment by autonomousapps** [comment]
You can start by just running the task and looking at the output. The task name is `proj:abiAnalysis$variant`, where `$variant` is `Debug`, `Release`, `Main` (for the JVM), etc.

Please note that this task does not (yet?) attempt any kind of _comparison_. It simply produces a text file that represents the ABI of the project under analysis. What you could do is run the task on one commit, and save the output. Then checkout another commit, run the task again, and again grab the output. Now just use any diffing tool you like to compare the two reports.

This is a far cry from what japicmp does. The main reason you'd prefer this tool to that one is that this one is Kotlin-aware (`internal` types aren't part of the ABI). But maybe japicmp is as well?

The PR describes one way to easily access the ABI report:

```groovy
def postDebug = tasks.register("postProcessDebug", AbstractAbiPostProcessingTask) {
  doLast {
    String abiDump = abiDump()
    println(abiDump)
  }
}

dependencyAnalysis {
  registerAbiPostProcessingTask(postDebug, "debug")
}
```
if you added that to a subproject's `build.gradle`, you could then run `./gradlew proj:postProcessDebug` and it would print your ABI to console.

**Comment by martinbonnin** [comment]
> this task does not (yet?) attempt any kind of comparison.

Having a comparison would be awesome. Especially if it can detect source and runtime binary compatibility issues.

> The main reason you'd prefer this tool to that one is that this one is Kotlin-aware (internal types aren't part of the ABI). But maybe japicmp is as well?

I just made a quick test and it looks like japicmp doesn't do any specific handling for internal methods:

![Screenshot 2020-10-13 at 10 28 18](https://user-images.githubusercontent.com/3974977/95835743-e7061100-0d3e-11eb-8c7f-678883b5f5af.png)

Other reasons to prefer `dependency-analysis-android-gradle-plugin`:
* it can work with source API dumps that I can commit to source control (and not only jars). 
* also it's written in Kotlin  and easier to contribute to.

```
def postDebug = tasks.register("postProcessDebug", AbstractAbiPostProcessingTask) {
  doLast {
    String abiDump = abiDump()
    println(abiDump)
  }
}

dependencyAnalysis {
  registerAbiPostProcessingTask(postDebug, "debug")
}
```

That'd only work if the plugin is applied, right? Since multiplatform is not supported at the moment, that'd skip all the multiplatform modules in the project.
