### ISSUE TITLE
Detect resource conflicts

### ISSUE THREAD

**Issue by autonomousapps** [autonomousapps/dependency-analysis-android-gradle-plugin#242]
Android libraries can provide "android resources", such as strings, drawables, etc. Different libraries can provide different resources which have the same name, and this leads to conflicts. You might think you're using `R.string.whatever` from library A, but instead get it from library B. The manner in which resource conflicts are handled by aapt is functionally non-deterministic. It could be useful for the plugin to warn users when they have such conflicts.

**Comment by stephanenicolas** [comment]
"functionally non-deterministic": there is (obviously) an algorithm to linearize the dependency graph for `aapt2` but humans cannot predict easily this order given a DAG, even less. when it changes as you clean dependencies as advised by the plugin.

**Comment by stephanenicolas** [comment]
Here is how to access the order that is passed to `aapt2`:
```
afterEvaluate {
  def runtimeConfiguration = project.configurations["debugRuntimeClasspath"]
  def artifactsForAaptMerging = runtimeConfiguration
          .incoming
          .artifactView { view ->
            view.attributes { attributeContainer ->
                attributeContainer.attribute(ARTIFACT_FORMAT, "android-compiled-dependencies-resources")
            }
          }
          .artifacts
          .artifacts
    .forEach { println it.id.componentIdentifier.displayName }
}
```

**Comment by eugene-krivobokov** [comment]
Here is an example implementation of this check but for application modules only:
https://github.com/avito-tech/avito-android/tree/develop/subprojects/gradle/build-checks/src/main/kotlin/com/avito/android/build_checks/internal/unique_app_res 
I will be glad if it helps in any way.

**Comment by blundell** [comment]
![image](https://user-images.githubusercontent.com/655860/135065869-d9e9adbd-de9a-4aa6-a553-654da2d58fb1.png)
https://developer.android.com/studio/projects/android-library#Considerations

This might be useful information for when resolving resources.
