### ISSUE TITLE
FR / Question - More information / explanation regarding advices (especially impl -> api; vice-versa)

### ISSUE THREAD

**Issue by aconda-mercari** [autonomousapps/dependency-analysis-android-gradle-plugin#248]
First of all thank you for this amazing plugin!
I tried this in a project and for starters just simply tried to blindly follow **all**  advice from the output (18K LoC json).
With this the **build times improved by a whopping 36%** which is incredible.

**Is your feature request related to a problem? Please describe.**
Naturally, I'd like to be able to understand better the advices instead of just blindly following them. Some of them are straightforward such as the unused plugins and dependencies, but I got a lot of  `change implementation -> api` and `api -> implementation` advices which I didn't really understand.

I checked the wiki and code and saw some explanation here
https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/blob/3242ae118a459e729c2be3795e335ddabd0e1ca9/src/main/kotlin/com/autonomousapps/internal/advice/Advisor.kt#L162-L168

However it is still not clear to me for some of the advices (see snippet below)

**Describe the solution you'd like**
Hoping for more information regarding the advices in the wiki, and if I could get clarification from here as well.

**Describe alternatives you've considered**
I could also help add this documentation in your wiki

**Additional context**
As example, I got these advices for a feature module. I don't understand why or when should I declare the dependency as api instead of implementation. I got a ton of these in 21 of our modules so I figured this is not so apparent for everyone else in my team either, especially since it's quite convenient to just copy paste dependencies from GitHub.

I tried looking for more clarification on the web when I should use which, though for a feature_module I feel like all the dependencies should be declared as `implementation` if no other module will depend on this module.

Another example is I got advice to declare `Timber` (a logging library) as `api`, and I don't understand why I would need to. Also there are performance concerns with using `api` that's why our team is using this keyword sparingly.
```json
 {
    "projectPath": ":feature_sample",
    "dependencyAdvice": [
      {
        "dependency": {
          "identifier": "androidx.lifecycle:lifecycle-livedata-core",
          "resolvedVersion": "2.3.0-alpha06",
          "configurationName": "implementation"
        },
        "usedTransitiveDependencies": [],
        "fromConfiguration": "implementation",
        "toConfiguration": "api"
      },
      {
        "dependency": {
          "identifier": "androidx.lifecycle:lifecycle-viewmodel",
          "resolvedVersion": "2.3.0-alpha06",
          "configurationName": "implementation"
        },
        "usedTransitiveDependencies": [],
        "fromConfiguration": "implementation",
        "toConfiguration": "api"
      },
      {
        "dependency": {
          "identifier": "androidx.compose.runtime:runtime",
          "resolvedVersion": "0.1.0-dev16",
          "configurationName": "implementation"
        },
        "usedTransitiveDependencies": [],
        "fromConfiguration": "implementation",
        "toConfiguration": "api"
      },
      {
        "dependency": {
          "identifier": "javax.inject:javax.inject",
          "resolvedVersion": "1",
          "configurationName": "implementation"
        },
        "usedTransitiveDependencies": [],
        "fromConfiguration": "implementation",
        "toConfiguration": "api"
      },
      {
        "dependency": {
          "identifier": "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm",
          "resolvedVersion": "1.3.8-1.4.0-rc",
          "configurationName": "implementation"
        },
        "usedTransitiveDependencies": [],
        "fromConfiguration": "implementation",
        "toConfiguration": "api"
      },
      {
        "dependency": {
          "identifier": "androidx.compose.ui:ui",
          "resolvedVersion": "0.1.0-dev16",
          "configurationName": "implementation"
        },
        "usedTransitiveDependencies": [],
        "fromConfiguration": "implementation",
        "toConfiguration": "api"
      },
      {
        "dependency": {
          "identifier": "androidx.camera:camera-lifecycle",
          "resolvedVersion": "1.0.0-beta07",
          "configurationName": "implementation"
        },
        "usedTransitiveDependencies": [],
        "fromConfiguration": "implementation",
        "toConfiguration": "api"
      },
      {
        "dependency": {
          "identifier": "androidx.camera:camera-core",
          "resolvedVersion": "1.0.0-beta07",
          "configurationName": "implementation"
        },
        "usedTransitiveDependencies": [],
        "fromConfiguration": "implementation",
        "toConfiguration": "api"
      }
    ],
    "pluginAdvice": [],
    "shouldFail": true
  }
```

**Comment by autonomousapps** [comment]
> build times improved by a whopping 36%

Wow! Could you tell me more about this? I could use your project as a case study :)

The long answer to this is an essay (and I actually have a draft blog post almost ready to go touching on some of this), but the short answer is that you can look in a file called `intermediates/abi-dump.json` and it's a human-readable description of a module's ABI. You could then look for something like `Timber` to see where it gets exposed publicly. Anything that's a return type or method param on a non-private function (public, protected, internal) is part of your ABI. If it's not part of the ABI (`api`), then it's `implementation`.

**Comment by aconda-mercari** [comment]
Unfortunately it is closed-source so I cannot share too much about it. But I think I can say it is a multi-modular project (around 21 modules) and currently it is taking past 1-minute to assemble, but after blindly following all the advice it now takes around 44 seconds for some reason. This plugin is the only thing that made such improvement in my project.

I'm also considering to integrate this in our CI to keep our modules in-check.

I just checked the `abi-dump.txt` and I now understand how the plugin is recommending to use `api` instead of `implementation`.

If you don't mind I'd also like to ask how the plugin decides this advice:
> Transitively used dependencies that should be declared directly as indicated:

Does this apply for all transitive-dependencies or is it also related to the ABI somehow? Also, I am not sure if it is advising me to redeclare a transitive-dependency as that would seem redundant. Consider transitive dependencies `a -> b -> c`:
```kotlin
// module A
implementation(":b")
implementation(":c") // <- Is the plugin advising me to do explicitly declare this?
// module B
api(":c")
```

Also I wonder, if the plugin would recommend to declare
```kotlin
// module A
implementation(":b")
implementation(":c")
// module B
implementation(":c")
```
instead of 
```kotlin
// module A
implementation(":b")
// module B
api(":c")
```
or at least would have the option to prefer `implementation`. As I've seen from this [talk](https://vimeo.com/430648415) using `implementation` has considerable perf improvement if you prefer performance over convenience. Also, I thought if we use this plugin we wouldn't have to worry about missing to include an `implementation` dependency.

Anyway my point of creating this GitHub issue is to request more documentation regarding the advices, or like you've mentioned we could just refer to the blog post you would be making.

I'm looking forward to your blog post!

**Comment by autonomousapps** [comment]
This [earlier blog post](https://dev.to/autonomousapps/the-proper-care-and-feeding-of-your-gradle-build-d8g) actually explains (or tries to) how and why the plugin advises you to directly add transitive dependencies. It also explains how you can turn that advice off if you disagree with the philosophy behind it.

Happy to keep discussing it. Maybe there's something I can add directly to the docs.

**Comment by BraisGabin** [comment]
> Anything that's a return type or method param on a non-private function (public, protected, internal) is part of your ABI. If it's not part of the ABI (api), then it's implementation.

Why a return type of an `internal` function is part of my ABI? It can't be used from outside, right?

**Comment by autonomousapps** [comment]
https://kotlinlang.org/docs/reference/java-to-kotlin-interop.html

> `internal` declarations become `public` in Java. Members of internal classes go through name mangling, to make it harder to accidentally use them from Java and to allow overloading for members with the same signature that don't see each other according to Kotlin rules;

**Comment by sboishtyan** [comment]
Does Kotlin mark interop methods like `synthetic`? Maybe you could determine that and use for advices

**Comment by BraisGabin** [comment]
Maybe this is a bit offtopic... but I don't want to open an issue that I'm not sure of it. I didn't find the case yet in my project (I'm just starting). But, for what I read, wouldn't have sense to have a we to filder the ABI using the `internal` visibility modifier? Probably as an opt-in, but, in my case I really don't care about interoperability with java. If I make a fucniton/class internal I don't want anyone to use it outside the module so I would like to filter it from my ABI for the analisis. Do this have sense? Should I open an issue to track it or it is just me not knowing enough about the plugin?

**Comment by autonomousapps** [comment]
@BraisGabin you're right. I just double-checked, and given the following:
```kotlin
import org.apache.commons.collections4.Bag

class Library {
      internal fun newBag(): Bag<String> {
        TODO()
    }
}
```
this plugin will _not_ recommend moving the Apache Commons Collections lib to `api`. However, if you remove the `internal` modifier, making the function public, then the plugin advises changing the dep from `implementation` to `api`.

So, **tl;dr** I just forgot what my own plugin does for a minute 😅

**Comment by autonomousapps** [comment]
I recently created issue https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/251, and am actively working on it (check out the `provenance` branch if you want to see the very-much-work-in-progress). That work should also resolve this issue.
