### ISSUE TITLE
Provenance: make it easier to trace the reason for a piece of advice

### ISSUE THREAD

**Issue by autonomousapps** [autonomousapps/dependency-analysis-android-gradle-plugin#251]
Right now it is challenging to understand _why_ the plugin is advising you to do X, Y, or Z. It takes a lot of investigation, such as looking at all the file outputs, maybe even looking at source code, to understand (or be the project maintainer and know intimately what every file contains...). I would like to simplify this process of understanding in some way. I have it in my head that some kind of serializable AST might be the way to go.

**Comment by sboishtyan** [comment]
It may look like `dependencyInsight` when you gather details about dependency you are interested in.

**Comment by autonomousapps** [comment]
I think this will differ in that it will have to embed information on api/implementation/etc, and the "capabilities" or classes/resources/etc the dependency provides.

**Comment by autonomousapps** [comment]
More progress:
```
./gradlew db:reasonDebug --id io.reactivex.rxjava2:rxjava
```
```
You asked about the dependency io.reactivex.rxjava2:rxjava. You have been advised to add this dependency.

Shortest path to io.reactivex.rxjava2:rxjava from the current project:
:db
\--- androidx.room:room-rxjava2
     \--- io.reactivex.rxjava2:rxjava

Dependency io.reactivex.rxjava2:rxjava provides the following:
- 1651 classes
- 141 public constants

And this project exposes the following classes provided by this dependency:
- io.reactivex.Flowable

Please see abi-dump.txt for more information.
```

And this visualization:
<img width="873" alt="Screen Shot 2020-08-24 at 10 05 44 AM" src="https://user-images.githubusercontent.com/5402301/91095188-c956de00-e610-11ea-808e-c9976302c066.png">

**Comment by autonomousapps** [comment]
`@Arunkumar`, author of [Scabbard](https://github.com/arunkumar9t2), gave me some advice on auto-generated they visualizations. He uses a library [here](https://github.com/arunkumar9t2/scabbard/blob/master/scabbard-processor/src/main/java/dev/arunkumar/scabbard/plugin/output/OutputWriter.kt#L101), that library is [here](https://github.com/nidi3/graphviz-java), and he has a [custom DSL](https://github.com/arunkumar9t2/scabbard/tree/master/dot-dsl) for generating the DOT files.

**Comment by sboishtyan** [comment]
Do you create documentation or example for using this feature?

**Comment by autonomousapps** [comment]
I will. Honestly part of the reason I've merged what I currently have is I was doing other important work on the same branch, and as an optional feature I didn't feel it could do any harm. As it is not yet in its final state, I didn't want to spend a lot of time writing about it just yet.


Check out the changelog for an example usage.
GitHub <notifications@github.com> wrote:
“Do you create documentation or example for using this feature?”
