### ISSUE TITLE
Native library-only aars always show up as unused

### ISSUE THREAD

**Issue by ZacSweers** [autonomousapps/dependency-analysis-android-gradle-plugin#252]
**Build scan link**

**Plugin version**
0.56

**Gradle version**
6.6

**Android Gradle Plugin (AGP) version**
4.0.1

**Describe the bug**
Similar to proguard-only artifacts, aars that contain only native library files always are reported as unused

**To Reproduce**

Example aar https://amazon-chime-sdk-android.s3.amazonaws.com/media/0.6.1/amazon-chime-sdk-media-0.6.1.tar.gz

**Expected behavior**
Unsure if the plugin should try to detect loading native libraries in the aar, but at least not suggesting their removal would be a good start

**Additional context**

**Comment by ZacSweers** [comment]
The library associated with the above link is amazon chime https://github.com/aws/amazon-chime-sdk-android

**Comment by autonomousapps** [comment]
It might be challenging to determine if libraries such as these are in fact "unused", so I may have to treat them like libraries that include service loaders -- that is, never call them unused. 

I'm considering enhancing the reporting so that "whitelisted" dependencies are listed for a human to double-check.

**Comment by autonomousapps** [comment]
@ZacSweers To save me from learning how to use this SDK, can you provide a snippet of sample code that ought to indicate "this is used"? I'd like to write a(n accurate) failing test to get started.

**Comment by ZacSweers** [comment]
Here's how it loads them https://github.com/aws/amazon-chime-sdk-android/blob/b43e22c435eab388ac1258669b0011c29c747fda/amazon-chime-sdk/src/main/java/com/amazonaws/services/chime/sdk/meetings/internal/audio/AudioClientFactory.kt#L18-L19
