### ISSUE TITLE
False positive on removal of implementation "org.jetbrains.anko:anko-commons:0.10.8"

### ISSUE THREAD

**Issue by peterhav** [autonomousapps/dependency-analysis-android-gradle-plugin#253]
**Plugin version**
0.56.0

**Gradle version**
6.6

**Android Gradle Plugin (AGP) version**
'com.android.tools.build:gradle:4.1.0-rc01'

**Describe the bug**
the buildHealth task lists that the dependency "org.jetbrains.anko:anko-commons:0.10.8" is unused ans should be removed.
When recompiling the app, the build fails due to missing dependencies:

import org.jetbrains.anko.doAsync
import org.jetbrains.anko.uiThread

**To Reproduce**
1. Create an app using the above dependencies and run the buildHealth tasj

**Expected behavior**
"org.jetbrains.anko:anko-commons:0.10.8" not showing as unused dependency

**Additional context**
Great plugin! This functionality has been missing for a long time.

**Comment by autonomousapps** [comment]
Thank you for the report!

**Comment by autonomousapps** [comment]
I wonder if this relates to https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/173

@peterhav can you tell me how you have your project set up? Is your Kotlin src in src/main/kotlin or src/main/java? And are you using `main.java.srcDirs += 'src/main/kotlin'`?

**Comment by peterhav** [comment]
Hi, I'm not using src/main/kotlin (all my sourcedirs are src/main/java). 
Due to a huge refactor in my sources the mentioned dependencies are no longer in my app; all other alarms raised by this plugin have been correct. I will close this issue and will report in case I encounter any other false positives.
