### ISSUE TITLE
Reports not updated after a change

### ISSUE THREAD

**Issue by BraisGabin** [autonomousapps/dependency-analysis-android-gradle-plugin#255]
**Build scan link**
https://gradle.com/s/likm367ju6kya

**Plugin version**
0.56.0

**Gradle version**
6.4.1

**Android Gradle Plugin (AGP) version**
none

**Describe the bug**
The general report `advice-holistic-pretty.json` and the specific `advice-all-variants-pretty.json` from the submodule is not updated after I fix an issue and run `./gradlew buildHealth` again. It works as expected if I run `./gradlew buildHealth --rerun-tasks`

**To Reproduce**
1. clone https://github.com/BraisGabin/detekt/
2. checkout dependency-analysis
3. run `./gradlew buildHealth`
4. change the dependency in `detekt-psi-utils/build.gradle.kts` from `implementation` to `api` (as the plugin advices)
5. run `./gradlew buildHealth` again
6. You will check that `advice-holistic-pretty.json` doesn't changed

**Expected behavior**
I don't need to use `--rerun-tasks` to make it work

**Comment by autonomousapps** [comment]
Thanks for the report, and reproducer. Sounds like maybe there's an issue with the up to date check, and therefore how the inputs and outputs are wired. Will take a look.

**Comment by autonomousapps** [comment]
There was a bug in the `LocateDependenciesTask` with its inputs. For now, I'm going to resolve it by forcing the task to never be up to date. Next release will have the fix. Thanks for the report.
