### ISSUE TITLE
Kotlin 1.4 automatic stdlib depency triggers some warnings

### ISSUE THREAD

**Issue by martinbonnin** [autonomousapps/dependency-analysis-android-gradle-plugin#262]
Using Kotlin 1.4, the kotlin plugin will add the stdlib automatically. If build scripts declare `jvmTarget = "1.8"`, that will include `kotlin-stdlib-jdk8` although most of it is used reflectively and this will show up as warnings in the output:

```
Unused dependencies which should be removed:
- api("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.4.0")

Transitively used dependencies that should be declared directly as indicated:
- implementation("org.jetbrains.kotlin:kotlin-stdlib:1.4.0")
```

I'm not sure what can be done about this. Maybe an exception for `kotlin-stdlib` ?

Reproducer project: https://github.com/martinbonnin/reproducer-dependency-analysis-android-gradle-plugin-262

**Comment by autonomousapps** [comment]
With this new 1.4 plugin behavior, I think I need to finally break down and whitelist it. Thanks for the report. 
GitHub <notifications@github.com> wrote:
“Using Kotlin 1.4, the kotlin plugin will add the stdlib automatically. If build scripts declare jvmTarget = "1.8", that will include kotlin-stdlib-jdk8 although most of it is used reflectively and this will show up as warnings in the output:

Unused dependencies which should be removed:
- api("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.4.0")

Transitively used dependencies that should be declared directly as indicated:
- implementation("org.jetbrains.kotlin:kotlin-stdlib:1.4.0")

I'm not sure what can be done about this. Maybe an exception for kotlin-stdlib ?”

**Comment by plastiv** [comment]
I guess the goal of this project is to be explicit over implicit. Even if it means additional verbosity.

With this goal in mind projects should opt-out instead from implicit stdlib management by kotlin plugin with `kotlin.stdlib.default.dependency=false` property.

**Comment by autonomousapps** [comment]
I try to balance clarity with ergonomics. In the case of the Kotlin plugin, this is far from the first time I've gotten a request to essentially "whitelist" it to conform to common practice. I think it makes sense to do so.

If you would like the ability to opt-out, please file a feature request and I'll be happy to consider it.
