### ISSUE TITLE
Add code coverage via codecov

### ISSUE THREAD

**Issue by stephanenicolas** [autonomousapps/dependency-analysis-android-gradle-plugin#27]
The setup seems failry simple, but you have to do it on the repo itself: 
* goto https://github.com/apps/codecov
* login
* enable code cov on the project repo (select it individually rather than all of them)
* you will be provided a token, but you don't need it.

**Comment by autonomousapps** [comment]
Not interested. I don't think code coverage is a useful metric, and don't want to burden myself with it.
