### ISSUE TITLE
adviceDebug and aggregateAdvice should fail if there are errors

### ISSUE THREAD

**Issue by bartek-wesolowski** [autonomousapps/dependency-analysis-android-gradle-plugin#272]
I specified the following configuration:
```
dependencyAnalysis {
    issues {
        all {
            onAny {
                severity('fail')
            }
        }
    }
}
```
When I add an unused dependency intentionally and run `buildHealth` then the task fails. However, when I run `adviceDebug` or `aggregateAdvice` on the module with the unused dependency, both task finish successfully. I would expect them to finish with a failure.

**Comment by bartek-wesolowski** [comment]
The problem with `buildHealth` in my case is that the project is very large and running it takes more than ten minutes. I'd rather run a smaller task for the module I'm currently modifying.

**Comment by vlsi** [comment]
@bartek-wesolowski , how come you created an issue 13.5 hours earlier? 🙀 

Other than that, I fully support this request :)

**Comment by autonomousapps** [comment]
Copy-pasting from 275
> My current plan for this is to use the gradle.buildFinished() listener as the only point of advice-failure. I don't want individual tasks to fail because if a user runs buildHealth I want the whole build to finish and only then fail. If I collect all failures during the build, I can check that collection in the buildFinished listener, and react accordingly.

I suppose @vlsi is right, this issue came first ;-)

**Comment by vlsi** [comment]
>autonomousapps: As I have said several times, the intended end-user task is buildHealth. If that build failed early, because a subsidiary task failed, it would be a Bad Thing.

I believe users can decide which failure is important and which is not.
They can add use `--continue`, they can use `mustExecuteAfter`, and they can use an extra Gradle execution.

However, I expect that a common use case would be to add `check { dependsOn("buildHealth") }` dependency, so users do not really call `buildHealth` manually because they don't really need to know of such a task.

**Comment by autonomousapps** [comment]
Relates to https://github.com/gradle/gradle/issues/14553.

**Comment by autonomousapps** [comment]
The associated PR resolves this issue to my satisfaction. However, it does not meet the articulated desire of failing on `adviceDebug`. Instead:
1. A new task is registered on each module: `:module:projectHealth`. This task aggregates tasks like `:module:adviceDebug`, `:module:adviceRelease`, etc. This `projectHealth` task _will_ fail if `severity` has been set to `fail`.
2. `:failOrWarn` has been removed. `:buildHealth` will now fail directly if there is _any_ issue in a build where `severity` has been set to `fail`.

There are a couple of consequences of this:
1. You can also run `projectHealth` and it will sort-of-kind-of-almost mimic `:buildHealth` insofar as it runs all the advice tasks in all the projects. A failure in any project would immediately fail the build, and you could also run `projectHealth --continue` and have the build keep going even in the face of one or more failures. It's _not_ like `:buildHealth` in that only the latter produces a file output that is a `List<BuildHealth>`, and only the latter would trigger the post-analysis task, should there be one.
2. This change further formalizes the intended "API" of this plugin. I expect users to _primarily_ run `projectHealth` and `buildHealth`. I do _not_ intend to provide additional support for direct invocations of tasks like `adviceDebug`. In particular, these variant-specific tasks will never fail, regardless of the `severity` level.

The wiki will be updated accordingly.

**Comment by vlsi** [comment]
Thanks.

In practice, #289 is almost the same as I suggested in #275 modulo task names:

> Vladimir: Note: I know the current `aggregateAdvice` performs computations, and what I suggest is to use a technical (hidden from users) task to perform computations, and make `aggregateAdvice` always-stale task that would print advice and it would fail as it is necessary.
