### ISSUE TITLE
Inheriting the common configuration in modules

### ISSUE THREAD

**Issue by bartek-wesolowski** [autonomousapps/dependency-analysis-android-gradle-plugin#273]
When I declare the following configuration:
```
dependencyAnalysis {
    issues {
        all {
            onUsedTransitiveDependencies {
                severity('ignore')
            }
        }
        project(':lib') {
            onUnusedDependencies {
                exclude('some-dependency:to-exclude')
            }
        }
    }
}
```
I expect used transitive dependencies to be ignored in `lib` as well, but they aren't. If I declare a separate configuration for one of the modules, I have to copy the common configuration to the module configuration like this:
```
dependencyAnalysis {
    issues {
        all {
            onUsedTransitiveDependencies {
                severity('ignore')
            }
        }
        project(':lib') {
            onUnusedDependencies {
                exclude(
                    'some-dependency:to-exclude',
                )
            }
            onUsedTransitiveDependencies {
                severity('ignore')
            }
        }
    }
}
```
This is very inconvenient when you have 30+ modules and they all have to copy the configuration from `issues.all` when they declare their own configuration or excludes.

**Comment by autonomousapps** [comment]
> I expect used transitive dependencies to be ignored in lib as well, but they aren't.

I expect that as well. Looks like you've found a bug (and thank you for the report). Would it be possible to provide a reproducer project?
