### ISSUE TITLE
OutOfMemoryError when buildHealth in Apache Calcite

### ISSUE THREAD

**Issue by vlsi** [autonomousapps/dependency-analysis-android-gradle-plugin#274]
**Build scan link**

The build crashes, so no buildscan :-(

**Plugin version**

0.59.0

**Gradle version**

6.6

**Android Gradle Plugin (AGP) version**

n/a

**Describe the bug**

OOM happens when running `buildHealth` task.
Java 11, default options are used, so daemon runs with `-XX:MaxMetaspaceSize=256m -XX:+HeapDumpOnOutOfMemoryError -Xms256m -Xmx512m`

```
> Task :spark:compileJava
Note: calcite/spark/src/main/java/org/apache/calcite/adapter/spark/SparkRules.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Expiring Daemon because JVM heap space is exhausted
Daemon will be stopped at the end of the build after running out of JVM memory
Expiring Daemon because JVM heap space is exhausted
Expiring Daemon because JVM heap space is exhausted
Expiring Daemon because JVM heap space is exhausted
Expiring Daemon because JVM heap space is exhausted
Expiring Daemon because JVM heap space is exhausted
Expiring Daemon because JVM heap space is exhausted
Expiring Daemon because JVM heap space is exhausted
Expiring Daemon because JVM heap space is exhausted
Expiring Daemon because JVM heap space is exhausted
Expiring Daemon because JVM heap space is exhausted
Expiring Daemon because JVM heap space is exhausted
Expiring Daemon because JVM heap space is exhausted
Expiring Daemon because JVM heap space is exhausted
Exception in thread "Thread-22" java.lang.OutOfMemoryError: Java heap space

> Task :spark:findClassesMain FAILED

> Task :core:compileTestJava
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
compiler message file broken: key=compiler.misc.msg.bug arguments=11.0.8, {1}, {2}, {3}, {4}, {5}, {6}, {7}
java.lang.OutOfMemoryError: Java heap space: failed reallocation of scalar replaced objects

> Task :core:compileTestJava FAILED

Build calcite FAILURE reason:
    org.gradle.execution.MultipleBuildFailures: Build completed with 2 failures.
        at org.gradle.initialization.DefaultGradleLauncher.runWork(DefaultGradleLauncher.java:274)
        at org.gradle.initialization.DefaultGradleLauncher.doClassicBuildStages(DefaultGradleLauncher.java:179)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:155)
        at org.gradle.initialization.DefaultGradleLauncher.executeTasks(DefaultGradleLauncher.java:131)
        Execution failed for task ':spark:findClassesMain':
        Execution failed for task ':core:compileTestJava':
```

**To Reproduce**
1. `git clone --depth 100 --branch dependency-analysis https://github.com/vlsi/calcite.git calcite_dependency-analysis`
2. `./gradlew buildHealth`

**Expected behavior**

The build should succeed

**Additional context**

OOM happens

Sample screenshots:
.../.gradle/caches/modules-2/files-2.1/org.scala-lang/scala-compiler/2.10.0/fec8066cd2b4f8dc7ff7ba7a8e0a792939d9f9a/scala-compiler-2.10.0.jar
takes 14MiB on disk, and it takes 18MiB in memory:
<img width="1366" alt="scala-compiler" src="https://user-images.githubusercontent.com/213894/92791421-517d0780-f3b5-11ea-9994-40e477152bbd.png">

Retained set for the cache:
<img width="677" alt="retained_set" src="https://user-images.githubusercontent.com/213894/92791709-90ab5880-f3b5-11ea-90ba-acfa4565027c.png">

Dominator tree of all the objects in the heap:
<img width="843" alt="dominator_tree" src="https://user-images.githubusercontent.com/213894/92791956-cc462280-f3b5-11ea-92c5-322d2ec0d38c.png">

**Comment by autonomousapps** [comment]
Thank you for the report and detailed information.

**Comment by autonomousapps** [comment]
@vlsi please take a look at the associated PR. Do you need me to publish a snapshot for testing, or are you set up to test manually via an included build?

**Comment by autonomousapps** [comment]
Issue was auto-closed when I merged the PR. Re-opened so we can test and fine-tune the implementation.

**Comment by autonomousapps** [comment]
Have you had a chance to experiment with the cache size yet?

**Comment by vlsi** [comment]
Oh, It did not fail the last time I tried, so I forgot there was OOM.

**Comment by autonomousapps** [comment]
:)

On October 3, 2020, GitHub <notifications@github.com> wrote:
> Oh, it did not fail the last time I tried, so I forgot there was OOM.

>

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/autonomousapps/dependency-analysis-android-gradle-

plugin/issues/274#issuecomment-703133073>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/ABJG5PIWEGT4NVA5OSIQ6KDSI5J7ZANCNFSM4RFXCUMQ>.

**Comment by autonomousapps** [comment]
I'm going to close this for now. If you still run into memory issues, please feel free to reopen it.
