### ISSUE TITLE
Make it easier to understand which subprojects have violations

### ISSUE THREAD

**Issue by vlsi** [autonomousapps/dependency-analysis-android-gradle-plugin#275]
**Is your feature request related to a problem? Please describe.**

Currently, the plugin has a single `failOrWarn` task, however, it is not easy to understand which violations caused the failure, especially on CI.

**Describe the solution you'd like**

It would be better if there was per-project `aggregateAdvice` task that printed warnings or failed itself as per configuration.
Then Gradle would summarize the build failure automatically like it does so when other tasks fail.

Note: I know the current `aggregateAdvice` performs computations, and what I suggest is to use a technical (hidden from users) task to perform computations, and make `aggregateAdvice` always-stale task that would print advice and it would fail as it is necessary.

**Describe alternatives you've considered**

`failOrWarn` might print an aggregated failure message side by side with "machine-readable / human-readable" files.

**Additional context**

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':failOrWarn'.
> There were build health issues. Please see the report
  (machine-readable) calcite/build/reports/dependency-analysis/advice-holistic.json
  (pretty-printed)   calcite/build/reports/dependency-analysis/advice-holistic-pretty.json

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

**Comment by autonomousapps** [comment]
Thank you for the feature request.

**Comment by autonomousapps** [comment]
My current plan for this is to use the `gradle.buildFinished()` listener as the only point of advice-failure. I don't want individual tasks to fail because if a user runs `buildHealth` I want the whole build to finish and only _then_ fail. If I collect all failures during the build, I can check that collection in the buildFinished listener, and react accordingly.

**Comment by vlsi** [comment]
>I don't want individual tasks to fail because if a user runs buildHealth I want the whole build to finish and only then fail.

Have you tried `--continue`? I believe it provides the behavior you describe, and it is something that already exists and it is documented.

If you move failure to the end of the build it makes it harder to understand which task caused the failure, it makes it hard to re-run the task in question, and it makes the feedback loop slower, as I no longer can stop the local build as the first failure appears.

**Comment by vlsi** [comment]
Apparently this is a duplicate of #272

**Comment by autonomousapps** [comment]
As I have said several times, the intended end-user task is `buildHealth`. If that build failed early, because a subsidiary task failed, it would be a Bad Thing.
