### ISSUE TITLE
Display reason for the suggestion report (e.g. field, method, and class names that expose dependency classes)

### ISSUE THREAD

**Issue by vlsi** [autonomousapps/dependency-analysis-android-gradle-plugin#280]
**Is your feature request related to a problem? Please describe.**

I analyze the output for Apache Calcite, and I'm puzzled why the plugin suggests `implementation` rather than `testImplementation`:

```
> Task :core:aggregateAdvice
Transitively used dependencies that should be declared directly as indicated:
- implementation("log4j:log4j:1.2.17")
- implementation("org.apache.commons:commons-pool2:2.6.1") <-- HERE
```

The current output is as follows:

```
> Task :core:reason
You asked about the dependency org.apache.commons:commons-pool2. You have been advised to add this dependency.

Shortest path to org.apache.commons:commons-pool2 from the current project:
:core
\--- org.apache.commons:commons-dbcp2
     \--- org.apache.commons:commons-pool2

Dependency org.apache.commons:commons-pool2 provides the following:
- 77 classes
- 44 public constants

And this project uses the following classes provided by this dependency:
- org.apache.commons.pool2.ObjectPool
- org.apache.commons.pool2.PooledObjectFactory
- org.apache.commons.pool2.impl.GenericObjectPool

Reason DOT: /Users/vladimirsitnikov/Documents/code/calcite/core/build/reports/dependency-analysis/graph-reason.gv
```

Note: the current dot 

**Describe the solution you'd like**

It would be great if there was a task that printed the list (or a sample) of classes (and methods) that have a dependency on the module in question.

For instance:

```
org.apache.commons:commons-pool2 should be declared as testImplementation because

project :core
  ==has sourceset=> test
    ==has class==> org.apache.calcite.test.CalciteAssert$PoolingConnectionFactory
       ==has constructor==> (ConnectionFactory factory)
         ==uses==> org.apache.commons.pool2.impl.GenericObjectPool
           ==is part of==> org.apache.commons:commons-dbcp2
```

**Describe alternatives you've considered**

no idea

**Comment by autonomousapps** [comment]
So that I can be clear, are you saying that `org.apache.commons:commons-dbcp2` is _only_ used by test source? That would be a bug. Could you provide repro steps?

Regarding your suggestion, it's an interesting idea, but I couldn't provide any eta on implementing it right now. Maybe if this were a full-time paid job :D

**Comment by autonomousapps** [comment]
I know this is an old issue, but does the plugin still provide the _wrong_ advice in this case? This is a separate question from providing a more detailed reason for why the advice is being emitted.

(I'm triaging old issues in advance of the 1.0 release.)

**Comment by autonomousapps** [comment]
Latest version of `reason` emits more information, including one of the used classes. It doesn't print the path to the used class, but nevertheless it's an improvement. Closing this for now.
