### ISSUE TITLE
Publish plugin artifact to central repository

### ISSUE THREAD

**Issue by vlsi** [autonomousapps/dependency-analysis-android-gradle-plugin#290]
https://oss.sonatype.org/content/repositories/snapshots/com/autonomousapps/dependency-analysis/ seems to be outdated, and it does not contain new snapshots.

That makes it impossible to use `plugins {...}` syntax to specify snapshot versions

**Comment by autonomousapps** [comment]
You need to dive down one directory deeper to see all the releases, and furthermore I publish a snapshot before each release to the plugin portal as well. The [wiki](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/wiki/Adding-to-your-project) also includes instructions on how to use snapshots with the `plugins {}` block.
