### ISSUE TITLE
projectHealth should be console-friendly

### ISSUE THREAD

**Issue by vlsi** [autonomousapps/dependency-analysis-android-gradle-plugin#291]
**Build scan link**

https://scans.gradle.com/s/qjwex247wshzc/console-log#L210

**Plugin version**

v0.61.0-SNAPSHOT

**Gradle version**

6.6.1

**Describe the bug**

Build output provides no clue on what went wrong.
It makes the task useless for TravisCI / AppVeyor / GitHub Actions CI environments.

**To Reproduce**

Run `projectHealth` task

**Expected behavior**

Build failure should include the relevant cause.

**Comment by vlsi** [comment]
>That said, I agree the output could be friendlier and was already planning to improve it.

Thank you.

Frankly speaking, the way you approach issues is unclear for me. I don't say it is wrong ot something like that, but it is unclear.
As an end-user, I try to create issues with the intended behavior/features, and I try to avoid implementation details. The way you structure the plugin into tasks is your decision.

For instance, you closed #275 and #272 in #289 , which is nice (moving forward is nice anyway), however, the usability issue is still there. I asked to print the warnings in #275, however, now all the related issues are closed, and the output is obscure. That is why I created this issue to signal that the UX issue is still there.

Currently, I can't integrate the plugin to a CI pipeline as the error messages/output would be absent/unclear/surprising, especially for those who do not know what is dependency-analysis-plugin. Believe me or not, many of Apache Calcite committers know nothing on Gradle (as Calcite was using Maven for the past years).

Frankly speaking, the naming of `projectHealth` / `aggregateAdvice` / `buildHealth` is not very important to me. You want to have different tasks, fine, I've no problem, and it would work for me just fine. 

Of course, you can say "go ahead, fork the plugin or implement your own", and it would be a fair point. Currently, dependency-analysis is not the top priority for me. It is like "nice-to-have". I try it from time to time, I do see the progress you make, however, I can't integrate it yet.

I see you have your own way and vision on the way to evolve the plugin, so I use "file issues and see what happens" strategy here.

**Comment by autonomousapps** [comment]
I'm a sole maintainer and do not have a coherent strategy for issues.

Regarding use on CI, you might consider grabbing the file output either via a well-known path or by explicitly depending on the task that generates it, and printing it. I'm not saying this is my ideal solution, but it's something you could do if you wanted CI integration before I get around to improving things in my spare time.

At the moment, I'm primarily driven by two things: (1) oh, that sounds like an interesting thing I'd like to learn more about and (2) getting rid of bugs in the analysis that may hurt trust in its correctness. UX, while important, is not the _top_ priority, simply as a matter of personal time management. Regarding (1), for example, I'm interested in exploring your idea for a dominator tree and have done some reading on algorithms that transform a DAG into a dom tree.

**Comment by autonomousapps** [comment]
Please take a look at https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/pull/293, which is intended to improve console output.
