### ISSUE TITLE
aggregateAdvice should be silent if the task is considered to be plugin-private

### ISSUE THREAD

**Issue by vlsi** [autonomousapps/dependency-analysis-android-gradle-plugin#292]
> autonomousapps:  I do not intend to provide additional support for direct invocations of tasks like adviceDebug

If `advice*` tasks are considered "private", then they should not produce output.

**Plugin version**
v0.61.0-SNAPSHOT

**Gradle version**

6.6.1

**Describe the bug**

`aggregateAdvice` prints output, however, it does so one-time only (second execution is up-to-date/from-cache, so the messages do not appear).

Sample output:

```
> Task :linq4j:aggregateAdvice
Existing dependencies which should be modified to be as indicated:
- implementation("org.apiguardian:apiguardian-api:1.1.0") (was api)

See machine-readable report at .../linq4j/build/reports/dependency-analysis/advice-all-variants.json
See pretty report at           .../linq4j/build/reports/dependency-analysis/advice-all-variants-pretty.json
```

**To Reproduce**

Run `./gradlew projectHealth`

**Expected behavior**

If the task is "private", then it should not produce output.
If the task is intended to be user-facing, then it should print messages on every execution rather than "one time only".

**Additional context**

See https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/5

**Comment by autonomousapps** [comment]
>  If the task is intended to be user-facing, then it should print messages on every execution rather than "one time only".

How do you expect this to work with up-to-date checks? See also https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/291#issuecomment-700052182.

**Comment by vlsi** [comment]
>How do you expect this to work with up-to-date checks?

I believe there are lots of ways to implement the behavior.

However, if you think `aggregateAdvice` is a plugin-private task, then I believe the task should be silent, especially, on successful (non-crashing) executions.
