### ISSUE TITLE
Recommend declaring annotations as api

### ISSUE THREAD

**Issue by vlsi** [autonomousapps/dependency-analysis-android-gradle-plugin#296]
Currently, dependency-analysis-android-gradle-plugin recommends downgrading `org.apiguardian:apiguardian-api` from `api` to `implementation` for Apache Calcite, however, that dependency should always be on the compile classpath.

Just in case, `apiguardian-api` is a single-annotation dependency: https://github.com/apiguardian-team/apiguardian

Here's a case by JUnit5 jhttps://github.com/junit-team/junit5/issues/1105
Similar case by Guava https://github.com/google/guava/issues/2824
Caffeine https://github.com/ben-manes/caffeine/issues/300

As far as I understand, many compilers need annotation classes for proper compilation (e.g. Error Prone compiler needs annotation definition for proper verification), so projects like Guava, JUnit5, Caffeine settled on using `<scope>compile</scope>` for their annotations.

It looks like `dependency-analysis-android-gradle-plugin` should suggest upgrading annotation dependencies to `api` in case they are used in public-like methods/classes.

**Comment by autonomousapps** [comment]
I read through the junit discussion and it was very interesting -- thanks for linking. Have you tried to follow the (perhaps inaccurate) advice and downgrade apiguardian to `implementation`? And if so, what was the result? Did you see issues similar in nature to what the junit team discussed?

**Comment by autonomousapps** [comment]
I have a PR now resolving this issue. Annotations on public types will now be considered part of the ABI.
