### ISSUE TITLE
Add integration with apiguardian-team/apiguardian

### ISSUE THREAD

**Issue by vlsi** [autonomousapps/dependency-analysis-android-gradle-plugin#3]
https://github.com/apiguardian-team/apiguardian provides a single annotation that enables to specify the state of the API.

For instance: `@API(status = STABLE)` means the API is public while `@API(INTERNAL)` means the API is not public.

In other words, if a class or method is declared as `@API(INTERNAL)`, then `dependency-analysis` should not suggest promoting the classes used in signatures as `api`.

**Comment by autonomousapps** [comment]
Thanks for the feedback. Will consider.

**Comment by autonomousapps** [comment]
Going to close as duplicate and add your comment to https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/69
