### ISSUE TITLE
Detect application of kotlin-android-extensions and whitelist auto-added dependencies

### ISSUE THREAD

**Issue by ColtonIdle** [autonomousapps/dependency-analysis-android-gradle-plugin#304]
I used this tool on my android project for the first time and it says that this dependency is unused.

According to a helpful person on slack they recommended that I should remove `apply plugin: "kotlin-android-extensions"` which I did indeed have and removing that plugin resolved the issue.

The report should hopefully specify to remove the plugin as it's a bit misleading

**Comment by autonomousapps** [comment]
I should be able to detect this, but in the meantime you can [instruct the plugin](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/wiki/Customizing-plugin-behavior) to ignore this dependency.

**Comment by autonomousapps** [comment]
At least one such dependency is
* `implementation("org.jetbrains.kotlin:kotlin-android-extensions-runtime:1.4.10")`

**Comment by ColtonIdle** [comment]
I removed the plugin as I wasn't using it so there's no need for me to instruct the plugin to ignore the dependency. So this plugin was correct that it wasn't needed!!!

**Comment by autonomousapps** [comment]
Hah, thanks for saying that. I'll check if that dependency is detectable if used, so maybe this will actually become a "detect if the kotlin-android-extensions plugin can be removed" feature.

**Comment by autonomousapps** [comment]
De-prioritizing this. I just created a new project with the AS new project wizard, and it looks like it no longer adds this plugin by default. Instead it uses ViewBinding. So, I'm not sure it's worth the effort to bake in support at this time.
