### ISSUE TITLE
Generics types should be considered as part of the ABI of a class

### ISSUE THREAD

**Issue by stephanenicolas** [autonomousapps/dependency-analysis-android-gradle-plugin#328]
Using version 0.67.1, given the classes:

In module `a`:
```
public class A {
  public void m(List<B> list)
}
```

In module `b`:
```
public class B {}
```

The plugin reports that the dependency of module A should be:

```
dependencies {
  implementation project(':b')
}
```
but according [to the documentation of Gradle](http://man.hubwiz.com/docset/Gradle_User_Guide.docset/Contents/Resources/Documents/userguide/java_library_plugin.html#sec:java_library_recognizing_dependencies): 
> So when should you use the api configuration? An API dependency is one that contains at least one type that is exposed in the library binary interface, often referred to as its ABI (Application Binary Interface). This includes, but is not limited to:
> * types used in super classes or interfaces 
> * types used in public method parameters, including generic parameter types (where public is something that is visible to compilers. I.e. , public, protected and package private members in the Java world)
> * types used in public fields
> * public annotation types

The advice for module `a` should be to declare the dependency to `b` as part of the api configuration: 
```
dependencies {
  api project(':b')
}
```

**Comment by autonomousapps** [comment]
Thanks for the issue. This should be a fun one to investigate.
