### ISSUE TITLE
Minimal mode to declare the least possible amount of dependencies in build files.

### ISSUE THREAD

**Issue by stephanenicolas** [autonomousapps/dependency-analysis-android-gradle-plugin#335]
Currently, the output of the plugin would recommend things like:

```
Transitively used dependencies that should be declared directly as indicated:
api("androidx.core:core:1.2.0")
etc...
```

The plugin focuses on "correctness" to make sure that all dependencies used by a project will be listed in its own build file.
Nevertheless, some dependencies don't need to be listed as they can already be transitively added by other dependencies. 

Gradle says such dependencies can be listed optionally. But the plugin is opinionated about this and advice to declare dependencies even if they can be acquired transitively, and there is no mode offered by the plugin to specifically advise to remove dependencies that do not need to be declared as they are acquired transitively.

Doing so is problematic:
* devs are not really free regarding this question and cannot choose the strategy they want.
* build files will be bloated in large graphs as the top level modules may contain hundreds of dependencies.
* build tools do not gain in efficiency by declaring these dependencies. 
* analysis tools are slowed down as soon as they deal with declared dependencies.
* it quite probably doesn't help syncing in Android Studio and building as it might trigger more dependency resolution inside Gradle. (Not sure of that).
* visualisation tools will also be bloated, or more complicated to write.
* devs are lazy and probably want the most compact build files possible. And they should.

For sure, listing all dependencies as some advantages as it isolates modules from each other and make it more easy to work in the graph independently. But the `:ripples` task now allows to quickly assert what modules will be impacted by a change in another module.

It would be really nice to have a switch to re-declare, or not, the dependencies used in a module and that are already acquired transitively via another dependency ?

**Comment by autonomousapps** [comment]
I have moved slightly in this direction in v0.72.0 with the new non-strict mode. Still considering this true "minimal mode."
