### ISSUE TITLE
Nulls in "Unused dependencies" block

### ISSUE THREAD

**Issue by Jacks0N23** [autonomousapps/dependency-analysis-android-gradle-plugin#339]
**Plugin version**
0.68

**Gradle version**
6.7.1

**Android Gradle Plugin (AGP) version**
4.1.1

**Describe the bug**
In some modules I have dependencies like: 
```
* What went wrong:
Execution failed for task ':ui-kit:projectHealth'.
> Unused dependencies which should be removed:
 - null(someInternalLibs)
 - null("com.squareup.okhttp3:okhttp:4.9.0")
 - null("com.squareup.retrofit2:adapter-rxjava2:2.9.0")
```

**To Reproduce**
I don't really know what exactly steps to reproduce the behavior. Maybe they are transitive dependencies of libs that I use?

**Expected behavior**
report either contains only api/implementation or empty

**Additional context**
Ask me if you need more information

**Comment by autonomousapps** [comment]
Could you tell me where and how those three dependencies are declared? And if they're declared in other subprojects, what are the plugins you have applied?

**Comment by autonomousapps** [comment]
@Jacks0N23 knock knock :)

**Comment by Jacks0N23** [comment]
Hey, sorry for a long time of silence, I've been very busy at work.
Now I checked  lates SNAPSHOT version and it work's good (better than some previous versions, because they didn't print any result decision(since 0.66 due 69.1-SNAPSHOT). Task successfully completed without print anything in console, but .json exists)
So upload this snapshot as release version please

**Comment by autonomousapps** [comment]
Thanks for confirming that, @Jacks0N23 . I will close this issue now. I do plan to release the next version soon.
