### ISSUE TITLE
Android view binding causes layout views to become part of the ABI

### ISSUE THREAD

**Issue by bartek-wesolowski** [autonomousapps/dependency-analysis-android-gradle-plugin#346]
**Plugin version**
0.69.0

**Gradle version**
6.7.1

**Android Gradle Plugin (AGP) version**
4.1.1

**Describe the bug**
When using Android view binding, all View types declared in XML layout become part of ABI and they shouldn't.

**To Reproduce**
I use Android view binding and [Android Image Cropper](https://github.com/ArthurHub/Android-Image-Cropper). I have an Activity with `CropImageView` in its layout XML file. The dependency analysis plugin suggests that Android Image Cropper should be an api dependency, probably because the generated binding class is public and it has a public field of type `CropImageView`. When I remove the `CropImageView` from the XML layout and stop referencing it in the code (it's only used via the generated binding class) then the problem disappears, and the api dependency on Android Image Cropper is no longer necessary.

**Expected behavior**
When using Android view binding, the generated binding classes shouldn't be included in the project's ABI and Views used in XML layout shouldn't be required to be declared as `api` dependencies.

**Comment by autonomousapps** [comment]
Can you clarify why these View types should not be part of the ABI? Could users of your library access those public View types? If so, then by definition it's part of the ABI, even if that seems undesirable.

That said, the plugin has a feature called [ABI filtering](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/wiki/ABI-filtering), which can be used to filter things from the ABI. Please give that a try and let me know if it resolves your issue.

**Comment by bartek-wesolowski** [comment]
I think you're right. By putting views in layout files they become part of the ABI. There's no such thing as module-private layout files on Android. It's just weird to see RecyclerView, CropImageView, AppCompat, ConstraintLayout, etc. listed as api dependencies.

**Comment by autonomousapps** [comment]
When you get a chance, I'd love to hear about your experience with the ABI filtering feature. I was designed with this use-case in mind. Please let us know if you have any issues with it.

**Comment by bartek-wesolowski** [comment]
In this case though, is it correct to use ABI filtering? Someone might actually use the layout file in another module and then it's necessary for them to be able to access the views declared in the layout.

**Comment by autonomousapps** [comment]
I would say it depends upon your intent. Are your layout files meant to be used by 3rd parties? If so, then you should not filter your ABI. If not, then it might be the right choice. People might still _try_ to use those layouts and the views they expose, but they shouldn't.

The simplest thing to do is nothing. Only filter if you think it important to define precisely your ABI.

**Comment by bartek-wesolowski** [comment]
OK, thanks for the explanation.

**Comment by autonomousapps** [comment]
Closing as WAI.

**Comment by bartek-wesolowski** [comment]
You can ignore classes generated by view binding by adding this fragment to your configuration:
```
dependencyAnalysis {
    abi {
        exclusions {
            ignoreSubPackage("databinding")
        }
    }
}
```

**Comment by BraisGabin** [comment]
> When you get a chance, I'd love to hear about your experience with the ABI filtering feature. I was designed with this use-case in mind. Please let us know if you have any issues with it.

Probably this arrives a bit late but for this use case it works like a charm :)
