### ISSUE TITLE
Absolute paths in cached artifacts

### ISSUE THREAD

**Issue by bartek-wesolowski** [autonomousapps/dependency-analysis-android-gradle-plugin#350]
**Plugin version**
0.69.0

**Gradle version**
6.7.1

**Android Gradle Plugin (AGP) version**
4.1.0

**Describe the bug**
The plugin uses absolute paths in cached artifacts. When the task results get stored in a remote cache, they fail locally because of incorrect paths, e.g.:
```
Execution failed for task ':api:analyzeJarDebug'. |  
-- | --
  | > java.io.FileNotFoundException: /home/bamboo/.gradle/caches/transforms-2/files-2.1/584cf8690492f1d4b5881565b71224ec/viewpager-1.0.0-api.jar (No such file or directory)
```
The paths clearly comes from my CI.

**To Reproduce**
Run `buildHealth` on CI with remote cache enabled, then run `buildHealth` locally.

**Comment by autonomousapps** [comment]
Thanks for the report. Would you be able to test a snapshot if I published one?

**Comment by bartek-wesolowski** [comment]
Sure.

**Comment by autonomousapps** [comment]
Could you provide me a stacktrace or build scan from the failure?

**Comment by bartek-wesolowski** [comment]
Here's a build scan:
https://scans.gradle.com/s/f4tnmuq67nsrg

**Comment by autonomousapps** [comment]
That looks like a different failure. In fact, the failure in that scan looks like an expected one, if you have severity set to 'fail'. Do you have a scan for the build cache-related failure?

**Comment by bartek-wesolowski** [comment]
Sorry for sending an unrelated build scan. This one should be better:
https://scans.gradle.com/s/sv3wlbsx2hwlq

**Comment by autonomousapps** [comment]
Ok, thanks. I have a good idea of the cause, and will let you know when a snapshot is ready to test.

**Comment by autonomousapps** [comment]
Please give `0.69.1-SNAPSHOT` a try and let me know if it resolves your issue. Thanks for testing.

**Comment by bartek-wesolowski** [comment]
It seems to solve the issue.

**Comment by autonomousapps** [comment]
Great. I'll publish this with the next release. Do you need it soon, or are you ok with using a snapshot for a while?

**Comment by bartek-wesolowski** [comment]
No worries. I'm not in a hurry.
