### ISSUE TITLE
Support Gretty

### ISSUE THREAD

**Issue by boris-petrov** [autonomousapps/dependency-analysis-android-gradle-plugin#354]
**Plugin version**
0.70.0

**Gradle version**
6.7

**Android Gradle Plugin (AGP) version**
Not an Android project

**Describe the bug**
On my project, running `gradle buildHealth` leads to:

```
> Task :aggregateAdvice SKIPPED
> Task :subproject1:aggregateAdvice SKIPPED
> Task :subproject2:aggregateAdvice SKIPPED
> Task :adviceReport

> Task :buildHealth
Advice for project :subproject2
Looking good! No changes needed

Advice for project :subproject1
Looking good! No changes needed

Advice for root project
Looking good! No changes needed
```

Which I guess means that the plugin did not work? I'm not sure, please tell me if that is not the case. But that happens also in an "empty" project:

```gradle
plugins {
	id 'java'
	id 'com.autonomousapps.dependency-analysis' version '0.70.0'
}
```

And the following in `src/main/java/com/company/Test.java`:

```java
package com.company;

public class Test {
	public static void main() {
	}
}
```

Am I missing something?

**Comment by autonomousapps** [comment]
That output means the plugin did not find any issues to report. It's possible that this has happened erroneously, but I couldn't say without knowing more about your project. If you provided a build scan, I would take a look.

That said, if your project only applies the `java` plugin (vs `java-library` or `application` or `org.springframework.boot`), then the plugin will in fact reduce to a no-op.

**Comment by boris-petrov** [comment]
@autonomousapps - I see, thanks for the response. My application is not using either of the three plugins you mention. I'm developing a web-application which I run with [Gretty](https://github.com/gretty-gradle-plugin/gretty) (without Spring Boot). So this is a feature-request rather than a bug-report - make `dependency-analysis-android-gradle-plugin` work in such cases. :smile:  Also you might want to mention that in the README so other people like me are not confused why it doesn't work. Thanks!

**Comment by autonomousapps** [comment]
That's a fair critique about the readme.

Could you elaborate on your use-case so I can consider this a proper feature request? What plugins are you applying? Explain like I have no idea what Gretty is (because I don't) :-) If you supply a build scan that would also be helpful.

**Comment by boris-petrov** [comment]
@autonomousapps - I'll create a project you can play with a bit later today/tomorrow. I'm actually not sure what `dependency-analysis-android-gradle-plugin` exactly does so I'll create a generic project with a couple of "general" dependencies and will explain how to run it and you'll tell me if you can work with that.

**Comment by autonomousapps** [comment]
Sounds good, and much obliged. 

On January 4, 2021, GitHub <notifications@github.com> wrote:
> @autonomousapps <https://github.com/autonomousapps> - I'll create a
> project you can play with a bit later today/tomorrow. I'm actually not

> sure what dependency-analysis-android-gradle-plugin exactly does so
> I'll create a generic project with a couple of "general" dependencies

> and will explain how to run it and you'll tell me if you can work with

> that.
>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/autonomousapps/dependency-analysis-android-gradle-

plugin/issues/354#issuecomment-754477616>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/ABJG5POJVQ3DKZ4BHUE7HXDSYLCOLANCNFSM4VSVKUUA>.

**Comment by boris-petrov** [comment]
@autonomousapps - so [here is the repo](https://github.com/boris-petrov/gretty-test-for-dependency-analysis). It's a very simple web-app containing a single [endpoint](https://github.com/boris-petrov/gretty-test-for-dependency-analysis/blob/master/src/main/java/com/company/TestResource.java). To run it clone the repo and simply do a `gradle appStart`. Then, when it starts (takes a few seconds), try it out with `curl http://localhost:8080/gretty-test-for-dependency-analysis/test-resource` - you should get `Hello World!`.

Running `gradle buildHealth` on that doesn't do anything. I've added ErrorProne (which should be irrelevant) and a few unused dependencies like `shiro` and the likes. This could be further simplified if you need.

Please tell me if I can do anything more.

**Comment by autonomousapps** [comment]
That sounds like a good start @boris-petrov . Thanks for the repro'ing repo.

**Comment by autonomousapps** [comment]
hi @boris-petrov. First, apologies for the long delay since we last talked about this. I was very focused on improving the model and general algorithms, vs supporting new plugins/ecosystems.

I cloned your sample and ran `buildHealth` against it (https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/pull/676) and got the following advice. Does it strike you as correct?
```
Advice for root project
Unused dependencies which should be removed:
  implementation 'org.apache.shiro:shiro-core:1.7.0'
  implementation 'org.apache.shiro:shiro-web:1.7.0'
  implementation 'org.glassfish.jersey.media:jersey-media-multipart:2.32'

Transitively used dependencies that should be declared directly as indicated:
  implementation 'jakarta.ws.rs:jakarta.ws.rs-api:2.1.6'

Dependencies which should be removed or changed to runtime-only:
  runtimeOnly 'org.glassfish.jersey.containers:jersey-container-servlet:2.32' (was implementation)
  runtimeOnly 'org.glassfish.jersey.core:jersey-server:2.32' (was implementation)
```

**Comment by autonomousapps** [comment]
Opportunistically closed based on successful PR. Feel free to reopen if there are specific issues.

**Comment by boris-petrov** [comment]
@autonomousapps - thanks a lot for the support and no worries about the delay! I'll be sure to try it once you release a new version containing the fix/feature.

**Comment by boris-petrov** [comment]
I'll delete the repo so for the sake of history, here's the reproduction:

`build.gradle`:
```gradle
import net.ltgt.gradle.errorprone.CheckSeverity

plugins {
	id 'java'
	id 'net.ltgt.errorprone' version '1.3.0'
	id 'org.gretty' version '3.0.3'
	id 'dev.jacomet.logging-capabilities' version '0.9.0'
	id 'com.autonomousapps.dependency-analysis' version '0.70.0'
}

repositories {
	mavenCentral()
	jcenter()
}

ext.errorProneVersion = '2.4.0'
ext.shiroVersion = '1.7.0'
ext.jerseyVersion = '2.32'

def webAppDirName = "${projectDir}/src/web/webapp"
project.metaClass.webAppDir = file(webAppDirName) // this is needed by Gretty

gretty.servletContainer = 'tomcat9'

dependencies {
	errorprone "com.google.errorprone:error_prone_core:$errorProneVersion"

	compileOnly 'javax.servlet:javax.servlet-api:4.0.1'
	implementation "org.glassfish.jersey.core:jersey-server:$jerseyVersion"
	implementation "org.glassfish.jersey.containers:jersey-container-servlet:$jerseyVersion"
	implementation "org.glassfish.jersey.media:jersey-media-multipart:$jerseyVersion"
	implementation "org.apache.shiro:shiro-core:$shiroVersion"
	implementation "org.apache.shiro:shiro-web:$shiroVersion"
	runtimeOnly 'jakarta.xml.bind:jakarta.xml.bind-api:2.3.3'
	runtimeOnly "org.glassfish.jersey.inject:jersey-hk2:$jerseyVersion"
	runtimeOnly 'org.apache.logging.log4j:log4j-web:2.14.0' // https://logging.apache.org/log4j/2.x/manual/webapp.html
}

tasks.withType(JavaCompile) {
	options.compilerArgs += '-Xlint:all,-processing'
	options.compilerArgs += '-Werror'
	// error-prone compiler arguments:
	options.errorprone {
		check('TypeParameterUnusedInFormals', CheckSeverity.OFF)
		check('CheckReturnValue', CheckSeverity.OFF)
		check('FutureReturnValueIgnored', CheckSeverity.OFF)
		check('GuardedBy', CheckSeverity.OFF)
		check('EmptyBlockTag', CheckSeverity.OFF)
		check('MissingSummary', CheckSeverity.OFF)

		disableWarningsInGeneratedCode = true
	}
}
```

`src/main/java/com/company/JerseyApp.java`:
```java
package com.company;

import java.util.HashSet;
import java.util.Set;
import javax.ws.rs.ApplicationPath;
import javax.ws.rs.core.Application;

@ApplicationPath("/")
public class JerseyApp extends Application {
	@Override
	public Set<Class<?>> getClasses() {
		Set<Class<?>> classes = new HashSet<Class<?>>();
		classes.add(TestResource.class);
		return classes;
	}
}
```

`src/main/java/com/company/TestResource.java`:
```java
package com.company;

import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;

@Path("test-resource")
public class TestResource {
	@GET
	@Produces("text/plain")
	public String hello() {
		return "Hello World!";
	}
}
```

`src/web/webapp/WEB-INF/web.xml`:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<web-app xmlns="http://xmlns.jcp.org/xml/ns/javaee"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/web-app_4_0.xsd"
         version="4.0">

    <servlet>
        <servlet-name>JerseyServletContainer</servlet-name>
        <servlet-class>org.glassfish.jersey.servlet.ServletContainer</servlet-class>
        <init-param>
            <param-name>javax.ws.rs.Application</param-name>
            <param-value>com.company.JerseyApp</param-value>
        </init-param>
        <load-on-startup>1</load-on-startup>
    </servlet>

    <servlet-mapping>
        <servlet-name>JerseyServletContainer</servlet-name>
        <url-pattern>/*</url-pattern>
    </servlet-mapping>
</web-app>
```
