### ISSUE TITLE
Raise a warning when a private method exists with signature that is looks like overload of a public method

### ISSUE THREAD

**Issue by vlsi** [autonomousapps/dependency-analysis-android-gradle-plugin#356]
**Is your feature request related to a problem? Please describe.**

See sample: https://github.com/gradle/gradle/issues/15660
Users might think that `private` methods do not leak to the "public API" scope, however, Java Language Specification suggests that permissions check is the last step in the overload resolution: https://docs.oracle.com/javase/specs/jvms/se7/html/jvms-5.html#jvms-5.4.3.1

**Describe the solution you'd like**

No idea. Ideally, g-a-a-g-p could detect such cases (`private` method which looks like an overload and which uses one of "non-api" classes) and raise a suggestion to rename the `private` method.

**Comment by autonomousapps** [comment]
Thanks for the issue. I was not aware of this fact:
> Java Language Specification suggests that permissions check is the last step in the overload resolution

I do think it would be possible to detect this situation. I know you said you have "no idea" what a solution would look like, but if you find time to consider and propose one, it would be helpful and make it more likely a feature like this would be added sooner than later. I'm asking for the user-facing "API", not how it would be implemented.

**Comment by vlsi** [comment]
>I'm asking for the user-facing "API"

Frankly speaking, I think it would be nice if the feature could work automatically. There might be user-facing api to suppress the warning, however, I belive the feature does not need configuration and it should be pretty much safe to be activated by default.

**Comment by autonomousapps** [comment]
I shouldn't have used the word "API", that was confusing. I meant "what should the warning look like, in the context of the other output generated by the plugin?"
