### ISSUE TITLE
Dependency analysis plugin should consider generated classes

### ISSUE THREAD

**Issue by pe4enko** [autonomousapps/dependency-analysis-android-gradle-plugin#357]
We use Kotlin Poet to genearate kotlin classes in build time. Generated classes writes to build/generated/different-name/src/main/kotlin folder. Dependency analysis plugin not consider this generated classes and generate wrong dependency report. 

Another example then we use com.google.protobuf plugin to generate protobuf classes or grpc stub.
It was good if Dependency analysis plugin consider generated by different plugins classes

**Comment by autonomousapps** [comment]
Are those generated classes then added to a source set? Can you provide a reproducer?
