### ISSUE TITLE
False positive for incorrect configuration check

### ISSUE THREAD

**Issue by gabrielittner** [autonomousapps/dependency-analysis-android-gradle-plugin#369]
**Build scan link**
I can privately provide one if needed.

**Plugin version**
0.71.0

**Gradle version**
6.8.2

**Android Gradle Plugin (AGP) version**
4.1.2

**Describe the bug**

I'm getting this report
```
Existing dependencies which should be modified to be as indicated:
- testApi("io.reactivex.rxjava2:rxjava:2.2.15") (was api)
```

However this I have this method in my project:
```
inline fun <T, R> Single<ApiResult<T>>.mapSuccess(crossinline mapper: (T) -> R): Single<ApiResult<R>> {
    return map { it.mapSuccess(mapper) }
}
```

This is the API dump of the file:
```
@Lkotlin/Metadata;
public final class com/freeletics/core/network/ApiResultKt {
	public static final fun mapSuccess (Lcom/freeletics/core/network/ApiResult;Lkotlin/jvm/functions/Function1;)Lcom/freeletics/core/network/ApiResult;
	public static final fun mapSuccess (Lio/reactivex/Single;Lkotlin/jvm/functions/Function1;)Lio/reactivex/Single;
}
```

While it actually compiles after applying the suggested change, Android Studio is not able to find `io.reactivex.Single` anymore.

**Comment by autonomousapps** [comment]
Hi @gabrielittner , thanks for the report. Is that function in your `main` or `test` source set?

**Comment by gabrielittner** [comment]
It's in the main source set

**Comment by autonomousapps** [comment]
Could you provide a reproducer and a build scan link? You can find me in the gradle community slack.

**Comment by osobolev** [comment]
Seems like I have the same issue. It can be reproduced only with non-standard sources layout. 
This example:
[repr369.zip](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/files/6409628/repr369.zip)
contains two folders with the same code: 8 with non-standard sourceSets, 9 with standard sourceSets. 

Running the plugin on folder 8 gives:
```
Advice for root project
Existing dependencies which should be modified to be as indicated:
- testApi("com.google.guava:guava:30.1.1-jre") (was api)

```
while running it on folder 9 finds no problems.

**Comment by autonomousapps** [comment]
Note to self: Gabriel sent me a reproducer separately.

**Comment by autonomousapps** [comment]
@gabrielittner could you try again with the latest snapshot? I just fixed another issue that seems similar, regarding test vs main source sets.

**Comment by gabrielittner** [comment]
I can confirm that it's fixed with the snapshot
