### ISSUE TITLE
False report about unused dependency when using AppsFlyer

### ISSUE THREAD

**Issue by ColtonIdle** [autonomousapps/dependency-analysis-android-gradle-plugin#371]
**Plugin version**
0.71.0

**Gradle version**
6.8.2

**Android Gradle Plugin (AGP) version**
4.1.0+

**Describe the bug**
Getting a report that a dependency is unused but according to my [third party lib documentation](https://support.appsflyer.com/hc/en-us/articles/207032126-Android-SDK-integration-for-developers#integration-22-adding-android-install-referrer-to-your-app) it says I should add the two dependencies like so

```
	implementation 'com.appsflyer:af-android-sdk:5.+'
	implementation 'com.android.installreferrer:installreferrer:1.1'
```

but then I get this error:

```
Unused dependencies which should be removed:
- implementation("com.android.installreferrer:installreferrer:2.2")
```

**To Reproduce**
Add two dependencies listed and run analysis

My hunch is that the developer docs are actually wrong and I don't need that android dependency (it's my hunch because the documentation isn't all that great, and a lot of stuff is out of date, so I feel like maybe it's just an old suggestion they never removed). Happy to provide more info if needed

**Comment by autonomousapps** [comment]
Hey @ColtonIdle , thanks for the report. My suggestion would be to remove that dependency, as suggested, and see if the project (1) still compiles and (2) still works at runtime. It's possible that the docs suggest it to address common use-cases that you nevertheless do not need, or it's possible there's a bug in the plugin that isn't detecting its usage somehow.

If you want to keep the dependency even if it's not used now, you could also declare a dependency bundle (see the wiki).

**Comment by autonomousapps** [comment]
@ColtonIdle I'm going to close this now, under suspicion that the advice is correct and the library docs are not :) If you find it's a real issue, please feel free to reopen.
