### ISSUE TITLE
`buildHealth` fails when using Fragment Testing

### ISSUE THREAD

**Issue by marcellogalhardo** [autonomousapps/dependency-analysis-android-gradle-plugin#377]
**Build scan link**
Not required for this problem.

**Plugin version**
0.71.0

**Gradle version**
6.8.3

**Android Gradle Plugin (AGP) version**
4.2.0-beta06

**Describe the bug**
To use fragment testing artefact, the official documentation recommend us to use: `debugImplementation "androidx.fragment:fragment-testing:$fragment_version"`. However, when running `buildHealth` we fail with the following error message: check Additional context.

The error is right as the dependency can not be found on release variant for unit tests and `buildHealth` is trying (I'm guessing) to verify the release variant. 

**To Reproduce**

1. Include `fragment-testing` artefact as recommended in the docs (`debugImplementation`);
2. Create any test that uses any class from `fragment-testing`;
3. Try to execute `buildHealth`.

**Expected behavior**

It should be possible to use both `fragment-testing` and `buildHealth` in a same project.

One solution I see is to be able to filter a specific build variant (e.g., ignore "unit test release" but still run for all the rest).

**Additional context**

```
e: /Users/marcellogalhardo/Developer/OpenSource/retained/fragment/src/test/java/dev/marcellogalhardo/retained/fragment/FragmentRetainedObjectTest.kt: (4, 30): Unresolved reference: testing
e: /Users/marcellogalhardo/Developer/OpenSource/retained/fragment/src/test/java/dev/marcellogalhardo/retained/fragment/FragmentRetainedObjectTest.kt: (16, 9): Unresolved reference: launchFragmentInContainer
e: /Users/marcellogalhardo/Developer/OpenSource/retained/fragment/src/test/java/dev/marcellogalhardo/retained/fragment/FragmentRetainedObjectTest.kt: (17, 13): Unresolved reference: onFragment
e: /Users/marcellogalhardo/Developer/OpenSource/retained/fragment/src/test/java/dev/marcellogalhardo/retained/fragment/FragmentRetainedObjectTest.kt: (18, 35): Function '<ERROR FUNCTION>' should return Unit to be used by corresponding operator '+='
e: /Users/marcellogalhardo/Developer/OpenSource/retained/fragment/src/test/java/dev/marcellogalhardo/retained/fragment/FragmentRetainedObjectTest.kt: (19, 45): Function '<ERROR FUNCTION>' should return Unit to be used by corresponding operator '+='
e: /Users/marcellogalhardo/Developer/OpenSource/retained/fragment/src/test/java/dev/marcellogalhardo/retained/fragment/FragmentRetainedObjectTest.kt: (21, 13): Unresolved reference: recreate
e: /Users/marcellogalhardo/Developer/OpenSource/retained/fragment/src/test/java/dev/marcellogalhardo/retained/fragment/FragmentRetainedObjectTest.kt: (22, 13): Unresolved reference: onFragment
```

**Comment by autonomousapps** [comment]
Could you provide a minimal reproducer? That would make it easier for me to find the root problem and resolve it.

**Comment by autonomousapps** [comment]
It would also be useful if you could provide a link to the docs you are referring to. (As well as a reproducer.)

**Comment by marcellogalhardo** [comment]
Hey @autonomousapps,

Sorry for the late reply, I miss the notification.

You can find the docs about Fragment Testing here: https://developer.android.com/guide/fragments/test

Simple add the dependency should cause the problem (as you'll see it is added only to `debugImplementation`):

```
dependencies {
    def fragment_version = "1.3.3"

    debugImplementation "androidx.fragment:fragment-testing:$fragment_version"
}
```

I will create an example and send you in the next couple of hours.

Sorry again for the delay, and thank you for the support! 🙏

**Comment by marcellogalhardo** [comment]
Hey @autonomousapps,

sorry for the late reply, I missed your comment before.

You can find a [sample here](https://github.com/marcellogalhardo/dependency-analysis-android-gradle-plugin-issue-377), simple clone and run `./gradlew :buildHealth`. I added details in the readme, including the error output and the classes that caused the error in this sample project.

The documentation for fragment testing can be [found here](https://developer.android.com/guide/fragments/test).

Thank you in advance for the support!

**Comment by marcellogalhardo** [comment]
Hey @autonomousapps - I'm just checking out if my sample project works as expected and if I can help with any extra information. Thank you!

**Comment by autonomousapps** [comment]
Hey, thanks for the nudge. I'll take a look!

**Comment by autonomousapps** [comment]
@marcellogalhardo I cloned your project and reproduced the error. I also reproduced the error by simply running `./gradlew app:testDebugUnitTest` -- your code doesn't compile. Note that your test code is in the `src/test` directory, and your only test dependency is JUnit4. The compiler is complaining because it can't find the other symbols. Looks like you've only declared them in `androidTestImplementation`.

**Comment by marcellogalhardo** [comment]
Hey @autonomousapps - I'm so sorry for not simulating it properly previously. I updated the sample project and now you should be able to simulate the problem. Below you find the output of both commands.

- `./gradlew app:testDebugUnitTest` output:

![image](https://user-images.githubusercontent.com/4348197/132199823-d1320df4-ae85-4bac-8ba2-f3fe29a0f87a.png)

- `./gradlew buildHealth` output:

![image](https://user-images.githubusercontent.com/4348197/132199921-0f8b79e5-b711-429e-84ee-dc3ef1287617.png)

Thank you a lot and I'm sorry again for not simulating it properly before.

**Comment by autonomousapps** [comment]
Thanks for the update. I see the issue now. It's still down to the fact that your code doesn't compile under certain circumstances. When you run `buildHealth`, this is the task that fails:
```
> Task :app:compileReleaseUnitTestKotlin FAILED
```
In other words, if you tried to run _release_ unit tests, rather than debug (`app:testReleaseUnitTest`), that would fail. This is because you've only added your dependency to `debugImplementation`. The probably would disappear if you used `implementation`, or even `testImplementation`. It's unclear to me why Google is saying to add that dependency to `debugImplementation` rather than a test configuration, since this seems to be a test-related artifact.

You could also resolve this by disabling release unit tests, which is a feature AGP provides.

**Comment by marcellogalhardo** [comment]
Hey @autonomousapps - thank you for the update.

From my limited understand, Google recommends you to add as `debugImplementation` due to the [EmptyActivity](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:fragment/fragment-testing/src/main/java/androidx/fragment/app/testing/FragmentScenario.kt;l=249) the fragment-testing uses internally: if we added as an `implementation` it won't be merged to the manifest and the test should fail.

Oh, the idea of disabling release unit tests sounds good for me (as I don't really use them). For those who find this issue with the same problem, you can disable release unit tests as following:

```kotlin
android {
    testOptions {
        unitTests.all { task ->
            // Verify if task should be enabled.
            task.isEnabled = task.name != "testDebugUnitTest"
        }
    }
}
```

I will close the issue as the solutions provided are satisfactory for my problem. Thank you for all the support @autonomousapps  and for the great library. 😄
