### ISSUE TITLE
Readme and wiki do not mention how to invoke the plugin

### ISSUE THREAD

**Issue by stealthrabbi** [autonomousapps/dependency-analysis-android-gradle-plugin#379]
Maybe I missed it, but I don't see where in the readme or the wiki it says how to actually  use the plugin. Had to go to a linked article that mentioned using the `buildHealth` task.

**Comment by autonomousapps** [comment]
I discuss that in the wiki [here](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/wiki/Tasks), but you are correct that it could be more discoverable. In fact, I should at least include `buildHealth` in the readme :sweat_smile:

**Comment by autonomousapps** [comment]
I've updated the README with quick-start information and additional pointers to the wiki.
