### ISSUE TITLE
False positive when super class/interface resides in a transitive dependency and required for kapt

### ISSUE THREAD

**Issue by technoir42** [autonomousapps/dependency-analysis-android-gradle-plugin#391]
**Plugin version**
0.72.1-SNAPSHOT

**Gradle version**
6.8.3

**Android Gradle Plugin (AGP) version**
4.2.0

**Describe the bug**
Consider the following module graph:
```
app -> lib1 (impl), lib2 (impl)
lib1 -> lib2 (impl)
lib2
```

and class hierarchy:
```kotlin
// app:
@AnnotationProcessed
class Lib1InterfaceImpl : Lib1Interface
// lib1:
interface Lib1Interface : Lib2Interface
// lib2:
interface Lib2Interface
```

`app` module has kapt plugin applied and `Lib1InterfaceImpl` gets processed. We don't want to expose `lib2` from `lib1` so instead we require every consumer of `lib1` to declare an explicit implementation dependency on `lib2`.

When running `buildHealth` or `:app:projectHealth`, the following advice is given regarding `app` module:

```
Advice for project :app
Unused dependencies which should be removed:
- implementation(project(":lib2"))
```

If we apply this advice, that is remove the dependency on`lib2` from `app`, the latter fails to build:

```
> Task :app:kaptDebugKotlin FAILED
app/build/tmp/kapt3/stubs/debug/com/app/Lib1InterfaceImpl.java:7: error: cannot access Lib2Interface
public final class Lib1InterfaceImpl implements com.lib1.Lib1Interface {
             ^
  class file for com.lib2.Lib2Interface not found
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:kaptDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptExecution
   > java.lang.reflect.InvocationTargetException (no error message)
```

**To Reproduce**
Repro project: https://github.com/technoir42/dependency-analysis-bug-repro, branch: `superclass-bug`.
Remove the dependency on `lib2` from `app` and run `./gradlew :app:assembleDebug`.

**Expected behavior**
If a super class/interface is required for kapt, the plugin does not recommend removing the dependency which contains such class/interface.

**Comment by autonomousapps** [comment]
From what you've described, I would also expect you'd have advice for project `:lib1` suggesting that you upgrade `lib1 -> lib2 (impl)` to `lib1 -> lib2 (api)`. Is that the case? (If not, it's a bug in this plugin.)

The advice given by `buildHealth` is meant to be taken holistically. It is possible to follow one single piece and end up with a project that does not compile, for reasons you've discovered :)

> We don't want to expose lib2 from lib1 so instead we require every consumer of lib1 to declare an explicit implementation dependency on lib2.

This is brittle behavior, and I would argue it violates the principles behind dependency management. `lib2` _is_ part of `lib1` 's ABI, so the most correct approach is to use the `api` configuration. If you insist, however, your best bet is to follow the instructions in the wiki [here](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/wiki/Customizing-plugin-behavior#failure-conditions-and-filtering).
