### ISSUE TITLE
Unexpected implementation("xerces:xercesImpl:2.9.1") (was runtimeOnly) advice

### ISSUE THREAD

**Issue by vlsi** [autonomousapps/dependency-analysis-android-gradle-plugin#394]
**Build scan**
https://scans.gradle.com/s/j24ycgqyzorjy/dependencies?dependencies=xerces&expandAll&projectFilter=WyI6c3BhcmsiXQ

**Plugin version**
0.73.0

**Gradle version**
6.8.3

**Describe the bug**

The plugin suggests to use `implementation` for `xerces:xercesImpl` for `:spark` project, however, the xerces is never explicitly used in the code.

Is there a reason for `implementation`?

I know the code works in the current way.
The idea behind `runtimeOnly(xerces)` is to ensure that xerces is present at the runtime even though it is not needed for the project compilation.

**To Reproduce**

clone https://github.com/apache/calcite
execute `./gradlew -PenableDependencyAnalysis -Pcom.autonomousapps.dependency-analysis.version=0.73.0 buildHealth`

**Expected behavior**

The plugin should keep the dependency as is

**Comment by autonomousapps** [comment]
It's interesting that the plugin is suggesting you add that to `implementation`, when you say it's not necessary for compilation. If it were truly unnecessary for compilation, I would expect the plugin to suggest that you remove it.

The plugin basically only analyzes dependencies from the perspective of compilation. So for a case like yours, I think the correct resolution is, if a dependency is specified as `runtimeOnly`, we assume the dev knows what they're doing and we don't advise changing it.

**Comment by vlsi** [comment]
I guess it is related to https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/280

For instance:
a) If the plugin suggests `implementation`, it could provide evidence that the dependency is used in a compilation like "class Abc is used in Def#createAbc()"
b) If the plugin suggests `api`, then it could provide something like "class Abc is used in a return value of a public method Def#getAbc()"

**Comment by autonomousapps** [comment]
Regarding
>         kotlin.UninitializedPropertyAccessException: lateinit property query has not been initialized

Thanks, I will improve the validation on that so that the error is more informative.

Regarding the lack of real information in the `reason` task, I know I still need to make improvements on that. In particular, I would like to start tracing usages in a more AST-like way, but it's not a high priority for time-management reasons.

I haven't repro'd your issue yet, but as always, thank you for the clear instructions. I'm confident this can be resolved 👍
