### ISSUE TITLE
Exceptions not reported as API, exceptions missing in ABI dump

### ISSUE THREAD

**Issue by loetifuss** [autonomousapps/dependency-analysis-android-gradle-plugin#395]
**Plugin version**
0.71.0

**Gradle version**
6.5.1

**Describe the bug**
The following method signature
`public void delete(InteressentenNr interessentenNr) throws InteressentException`

yields the following ABI dump:

```
public class de/foo/builder/TestBuilder {
	public fun delete (Lde/foo/type/InteressentenNr;)V
}
```
If the "buildHealth" task is run the following advice is created:

```
   "dependency": {
        "identifier": ":interessent.module",  --> module containing the exception type 'InteressentException'
        "configurationName": "compile"
      },
      "usedTransitiveDependencies": [],
      "fromConfiguration": "compile",
      "toConfiguration": "implementation"  --> expect this to be "api" instead
    }
```

**To Reproduce**
1. create method in "moduleX" which throws exception type from a different module e.g. "moduleY"
2. verify moduleX has advice set to "implementation" for moduleY instead of "api"

**Expected behavior**
Exceptions thrown in method signatures should be considered in the ABI. If a method refers to an exception type from a different module, this module should be advised to have "api" configuration.

**Context**

Classes compiled using ECJ on Java 1.8

**Comment by autonomousapps** [comment]
I'm not an expert on the Java specification. I just did some cursory searching online and found [this](https://docs.oracle.com/javase/tutorial/java/javaOO/methods.html), which doesn't list exceptions as part of the definition of method signatures. Can you point me to anything discussing the relationship between exceptions and ABI?

I do understand what you're saying here, but I want to make sure we come to the right resolution here, not just the one that _feels_ right.

**Comment by loetifuss** [comment]
Sorry for the late reply, after some research I'd agree that exceptions aren't part of the ABI. I found the following sections in the JLS:

- https://docs.oracle.com/javase/specs/jls/se8/html/jls-13.html#jls-13.4.21
- https://docs.oracle.com/javase/specs/jls/se8/html/jls-8.html#jls-8.4.2

Nevertheless, I think that dependencies from "throws"-clauses should be regarded in the dependency analysis plugin, since following the advice in the current output of the "buildHealth" task will result in code that won't compile.

**Comment by autonomousapps** [comment]
Thank you. I'll be taking a look at resolving this for the 1.0 release.

**Comment by autonomousapps** [comment]
Resolved via https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/pull/459
