### ISSUE TITLE
support scala projects

### ISSUE THREAD

**Issue by igreenfield** [autonomousapps/dependency-analysis-android-gradle-plugin#399]
Can you add support for scala?

**Comment by autonomousapps** [comment]
Maybe! I don't have any experience with Scala, so I'm not sure what the edges cases would be. Would you be able to create a small sample project with instructions on how to build and run it?

**Comment by autonomousapps** [comment]
Similarly to https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/364#issuecomment-1134017073, I am not aware of any _specific_ issue with support for analyzing Scala projects. So long as either the `java-library` or `application` plugin is also applied, then this should just work. So, I'm going to close this. If you know it doesn't work with Scala, please provide a reproducer.

**Comment by autonomousapps** [comment]
Hm, upon reflection, there is still missing functionality. Need to analyze Scala source to really be able to say this plugin can handle Scala projects.

**Comment by autonomousapps** [comment]
This will be released as v1.4.0.
