### ISSUE TITLE
Provide a way to override API status

### ISSUE THREAD

**Issue by vlsi** [autonomousapps/dependency-analysis-android-gradle-plugin#4]
There might be valid reasons to use `implementation` (rather than `api`) even in case a class is present in a signature of a public method.

The method could be `visible-for-test` only or `internal` or something like that.

**Comment by autonomousapps** [comment]
This seems like an edge case and I would rank it low in priority.

**Comment by autonomousapps** [comment]
I'm going to close this as duplicate and add your comment to https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/69
