### ISSUE TITLE
Some questions about the plugin

### ISSUE THREAD

**Issue by Astro03** [autonomousapps/dependency-analysis-android-gradle-plugin#400]
I'm trying to use this plugin with a multi-project java project

1.  Is Gradle's Variant aware build the same as the variant used for android builds? 
1a. If so, is there a plan to make the jvm analyzer to use variants optionally instead of source sets?  
2. Does this plugin work with user defined configurations? 
3. Does this plugin work with test configurations? ->(I have multiple testCompile configurations which should be testImplementation)
3a. I see abiAnalysisMain task run but I cannot figure out how to get abiAnalysisTest task to trigger. Does it exist?
4. I've added unused compileOnly configurations -> is the plugin supposed to report these? 

As far as I've seen, this plugin works great for the api, compile, and implementation configurations. Unfortunately, I'm having difficulty with the others.

**Comment by autonomousapps** [comment]
I have no plans right now to expand the JVM analysis beyond looking at the main source set. This isn't out of the question, but I'd have to see a use-case.

> Does this plugin work with user defined configurations?

Can you elaborate?

> Does this plugin work with test configurations?

There is support for `testImplementation` only at this point. If you want to see this expanded, please open a feature request.

> abiAnalysisTest

No, that task does not exist. The test-analysis this plugin currently has is rather limited, and the test code is analyzed in the same pass as the main source set code. This could be improved, and feature requests are welcome.

> I've added unused compileOnly configurations -> is the plugin supposed to report these?

The plugin [explicitly will not suggest](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/blob/main/src/main/kotlin/com/autonomousapps/internal/advice/Advisor.kt#L120-L140) removing a compileOnly dependency. This was a conservative decision made to avoid some false positives regarding dependencies that seemed unused but were still needed at compile-time. The plugin makes every effort to err on the side of safety -- applying the advice shouldn't break your project, even if there might be some unused dependencies left behind.
