### ISSUE TITLE
Used constant of dependency not recognized

### ISSUE THREAD

**Issue by gabrielittner** [autonomousapps/dependency-analysis-android-gradle-plugin#408]
**Build scan link**

Reproducer instead [constants.zip](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/files/6591259/constants.zip)

**Plugin version**

0.73.1-SNAPSHOT

**Gradle version**

7.0.0

**Android Gradle Plugin (AGP) version**

n/a

**Describe the bug**

The root project declares a constant like this
```
const val ARG_WINDOW_DRAW_BELOW_NAV_BAR = "core.window.drawBelowNavigationBar"
```

Another project uses that constant, for example 
```
fun foo() {
    println(ARG_WINDOW_DRAW_BELOW_STATUS_BAR)
}
```

The advice is to remove the dependency on the project declaring the constant, which would then make compilation fail
```
Advice for project :settings
Unused dependencies which should be removed:
- implementation(project(":"))
```

**To Reproduce**
1. Run `buildHealth` in the sample project

**Expected behavior**

There shouldn't be advice to remove the dependency

**Additional context**

In my project from work where I initially found this it only started happening after updating from Kotlin 1.4.32 to 1.5.10. In the reproducer it seems to happen regardless of Kotlin version

**Comment by autonomousapps** [comment]
The kotlin compiler doesn't use the constant pool (unlike `javac`), so to detect constant usage, the plugin looks at import statements in the source code and tries to infer which dependency is associated with that import statement. This works, but not if you have a fully-qualified usage (i.e., no import statement).

Thanks for the reproducer, I'll take a look.

**Comment by gabrielittner** [comment]
The reproducer does not have an import because I just used the same package when creating it. When I move the usage to a different package and add the import I'm seeing what I see in our work project:

Kotlin 1.4.32
```
> Task :buildHealth
Advice for root project
Looking good! No changes needed

Advice for project :settings
Looking good! No changes needed
```

Kotlin 1.5.10
```
> Task :buildHealth
Advice for root project
Looking good! No changes needed

Advice for project :settings
Unused dependencies which should be removed:
- implementation(project(":"))
```
[constants2.zip](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/files/6598733/constants2.zip)

**Comment by autonomousapps** [comment]
Very interesting. Thanks! 

On June 3, 2021, GitHub ***@***.***> wrote:
> The reproducer does not have an import because I just used the same
> package when creating it. When I move the usage to a different package
> and add the import I'm seeing what I see in our work project:
>
> Kotlin 1.4.32
>
> > Task :buildHealth Advice for root project Looking good! No changes
> needed Advice for project :settings Looking good! No changes needed
> Kotlin 1.5.10
>
> > Task :buildHealth Advice for root project Looking good! No changes
> needed Advice for project :settings Unused dependencies which should
> be removed: - implementation(project(":"))
> constants2.zip <https://github.com/autonomousapps/dependency-analysis-
> android-gradle-plugin/files/6598733/constants2.zip>
>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/autonomousapps/dependency-analysis-android-gradle-
plugin/issues/408#issuecomment-854717200>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/ABJG5POGKTD45JHPCSFSQELTRDG7JANCNFSM46ASM5RQ>.

**Comment by autonomousapps** [comment]
Fixed.
