### ISSUE TITLE
Ability to downgrade severity per project

### ISSUE THREAD

**Issue by eugene-krivobokov** [autonomousapps/dependency-analysis-android-gradle-plugin#409]
**Is your feature request related to a problem? Please describe.**

I want to use `fail` severity by default. 
In case of problems in one project and with one check, I want to downgrade severity to warn\ignore only to this project and check.

**Describe the solution you'd like**

Current API is suitable:

```kotlin
dependencyAnalysis {
    issues {
        all {
            onUnusedDependencies {
                severity("fail")
            }
        }
        project(":a") {
            issues {
                onUnusedDependencies { // will fail
                    severity("ignore")
                }
            }
        }
    }
}
```

I found inconsistent and not-obvious that it works for `warn` --> `ignore`:

```kotlin
dependencyAnalysis {
    issues {
        all {
            onUnusedDependencies {
                severity("warn")
            }
        }
        project(":a") {
            issues {
                onUnusedDependencies { // will be ignored
                    severity("ignore")
                }
            }
        }
    }
}
```

If I'm not mistaken, it's where `max`  hardcoded in `IssueHandler.union()`.
A probable option is to set a strategy for merging explicitly.

```kotlin
dependencyAnalysis {
  severityStrategy = preferProject \ preferGlobal \ max severe \ ...
  issues {
        all {
           ...
        }
        project(":a") {
            ...
        }
    }
}
```

**Describe alternatives you've considered**

Don't configure in root project and do it only in subprojects. 

```kotlin
root project:

subprojects {
    plugins.withId("com.autonomousapps.dependency-analysis") {
        dependencyAnalysis {
            onUnusedDependencies {
                severity(resolveSeverityForProject(this@subprojects))
            }
```
`resolveSeverityForProject()` - finds optional property in case of override or return a default value.
It should work, but less convenient and not declarative as simple config in a project (see above).

**Additional context**

Plugin version: 0.73.0

**Comment by autonomousapps** [comment]
Thank you for filing this feature request.
