### ISSUE TITLE
Does not work on JDK 16

### ISSUE THREAD

**Issue by boris-petrov** [autonomousapps/dependency-analysis-android-gradle-plugin#416]
**Plugin version**
0.73.0

**Gradle version**
7.0.2

**Describe the bug**
Running an analysis on JDK 16 fails with:

```
Execution failed for task ':backend:analyzeClassUsageMain'.
> A failure occurred while executing com.autonomousapps.tasks.ClassListAnalysisWorkAction
   > Unsupported class file major version 60
```

**To Reproduce**
1. Install JDK 16
2. `gradle buildHealth`

**Expected behavior**
No exception.

**Comment by autonomousapps** [comment]
Thanks for the issue report.

**Comment by tony-schellenberg** [comment]
Just tried with Java 17 and saw the same error but with file version `61`

**Comment by autonomousapps** [comment]
Noted. I plan to take a look at this issue after release 1.0, which ought to be in the near future.

**Comment by tony-schellenberg** [comment]
Super, thanks a lot.

**Comment by autonomousapps** [comment]
Verified the plugin now works with JDK 16 (not yet published).
