### ISSUE TITLE
False-positive unused dependencies error for resources in XML files

### ISSUE THREAD

**Issue by eugene-krivobokov** [autonomousapps/dependency-analysis-android-gradle-plugin#420]
**Build scan link**

**Plugin version**

0.73.0

**UPD:** 0.77.0

**Gradle version**

6.9

**(Optional) Android Gradle Plugin (AGP) version**

4.1.2

**Describe the bug**

False-positive unused dependencies error when Android resources are used only in XML resources.

**To Reproduce**
1. Checkout branch [dep-analyzer-res-in-xml-reproducer](https://github.com/avito-tech/avito-android/compare/35fe990b018a31b46ba57b540cc5144a30e8b680...dep-analyzer-res-in-xml-reproducer)
1. `./gradlew -p subprojects :android-lib:snackbar-proxy:projectHealth`

**Expected behavior**

Detect usages of resources

**UPD:** See `subprojects/android-lib/snackbar-proxy/src/main/res/drawable/ic_pin.xml` file. It uses `android:fillColor="?themeColor"` from `:android-lib:ui-lib`.

**Additional context**

- `android.nonTransitiveRClass=true`
- In code it works, commented it in a sample.

**Comment by autonomousapps** [comment]
Interesting, thanks for the reproducer. The plugin does attempt to detect resources used by other resources, but it looks like it is failing here.

**Comment by konnovdev** [comment]
I also faced the same problem, i have a **module** that only has **layouts**, (no kotlin files), and from this **module** i declare a **dependency** on **another module** to use some **strings** from that **module** in **layouts**, and it's saying that the **dependency is unused**

**Comment by autonomousapps** [comment]
I realized that this issue report is lacking some important detail. It's unclear what "detect usage of resources" means. I cloned that branch and ran the indicated task and saw this
```
> Task :android-lib:snackbar-proxy:projectHealth
Unused dependencies which should be removed:
- implementation(project(":android-lib:ui-lib"))
```
So I should infer that `:android-lib:ui-lib` contains resources that are being used?

**Comment by eugene-krivobokov** [comment]
Sure, see a comment "This usage is not detected" in `subprojects/android-lib/snackbar-proxy/src/main/res/drawable/ic_pin.xml` file. It uses `android:fillColor="?themeColor"` from `:android-lib:ui-lib` module.

How to check it:
- Remove dependency to `:android-lib:ui-lib` from `:android-lib:snackbar-proxy` module
- `./gradlew -p subprojects :android-lib:snackbar-proxy:assembleRelease`
- AAPT fails:

```
':android-lib:snackbar-proxy:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > 1 exception was raised by workers:
     com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
     /.../avito-android-github/subprojects/android-lib/snackbar-proxy/src/main/res/drawable/ic_pin.xml:9: AAPT: error: resource attr/themeColor (aka com.avito.android.snackbar.proxy:attr/themeColor) not found.
```

**Comment by eugene-krivobokov** [comment]
I've updated the issue description accordingly and rechecked with 0.77.0.

**Comment by autonomousapps** [comment]
I have resolved this specific case (using an attr from another module) with the associated PR, but I haven't tried to fix the problem more comprehensively. Android resource linking is very complicated and I'd rather solve it on a case-by-case basis, with actual use-cases, then try to figure it all out a priori.
