### ISSUE TITLE
Used transitive dependencies advice for test dependencies suggests wrong configuration

### ISSUE THREAD

**Issue by gabrielittner** [autonomousapps/dependency-analysis-android-gradle-plugin#424]
**Build scan link**

[transitive-test.zip](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/files/6682008/transitive-test.zip)

**Plugin version**

0.74.0

**Gradle version**

7.0

**(Optional) Android Gradle Plugin (AGP) version**

4.2.1

**Describe the bug**

I'm depending on `io.kotest:kotest-assertions-core-jvm` in `testImplementation` but only use things from the transitive `io.kotest:kotest-assertions-shared-jvm` dependency. I correctly get the advice to remove the former, but the suggestion to add the latter directly tells me to add it using `implementation` instead of `testImplementation`.

```
Advice for project :settings
Unused dependencies which should be removed:
- testImplementation("io.kotest:kotest-assertions-core-jvm:4.6.0")

Transitively used dependencies that should be declared directly as indicated:
- implementation("io.kotest:kotest-assertions-shared-jvm:4.6.0")
```

**To Reproduce**

See above or sample project.

**Expected behavior**

The advice should be

```
Advice for project :settings
Unused dependencies which should be removed:
- testImplementation("io.kotest:kotest-assertions-core-jvm:4.6.0")

Transitively used dependencies that should be declared directly as indicated:
- testImplementation("io.kotest:kotest-assertions-shared-jvm:4.6.0")
```

**Comment by autonomousapps** [comment]
The fix for this will be published with the next release. You can already verify by using the latest snapshot (once it gets published).
