### ISSUE TITLE
Ignored redundantPlugins still produces advice in output

### ISSUE THREAD

**Issue by eugene-krivobokov** [autonomousapps/dependency-analysis-android-gradle-plugin#431]
**Plugin version**

0.74.0

**Gradle version**

6.9

**(Optional) Android Gradle Plugin (AGP) version**

4.1.2

**Describe the bug**

Can't suppress `redundantPlugins` check:

```kotlin
dependencyAnalysis {
    issues {
        all {
            onRedundantPlugins {
                severity("ignore")
            }
        }
    }
}
```

```sh
./gradlew :project:projectHealth  
```

Still see the advice:

```txt
Plugin advice:
- java-library: this project has both java-library and org.jetbrains.kotlin.jvm applied, which is redundant. You can remove java-library
```

project/build/reports/dependency-analysis/advice-all-variants-pretty.json:

```json
  "pluginAdvice": [
    {
      "redundantPlugin": "java-library",
      "reason": "this project has both java-library and org.jetbrains.kotlin.jvm applied, which is redundant. You can remove java-library"
    }
  ]
```

It makes it harder to read the `buildHealth` report with many unsuppressed messages.

**To Reproduce**
1. Checkout https://github.com/avito-tech/avito-android/tree/dependency-analysis-reproducer-ignore-redundantPlugins
1. `./gradlew -p subprojects :gradle:build-properties:projectHealth`

**Expected behavior**

No plugin advice at all.

**Additional context**

**Comment by autonomousapps** [comment]
Let me know if you need any advice on how to get started with this.

**Comment by autonomousapps** [comment]
This fix just landed on `main`.
