### ISSUE TITLE
TypeNotPresentException: Type org.jetbrains.kotlin.gradle.dsl.KotlinProjectExtension in Kotlin jvm library

### ISSUE THREAD

**Issue by eugene-krivobokov** [autonomousapps/dependency-analysis-android-gradle-plugin#432]
**Build scan link**

https://scans.gradle.com/s/gde5zkyzhipge/failure#1

**Plugin version**

0.74.0

**Gradle version**

6.9

**(Optional) Android Gradle Plugin (AGP) version**

no AGP

**Describe the bug**

Can't apply the plugin in simple project with Kotlin jvm module:

```txt
java.lang.TypeNotPresentException: Type org.jetbrains.kotlin.gradle.dsl.KotlinProjectExtension not present	
at org.gradle.api.reflect.TypeOf.captureTypeArgument(TypeOf.java:291)	
at org.gradle.api.reflect.TypeOf.<init>(TypeOf.java:97)	
at com.autonomousapps.DependencyAnalysisPlugin$configureKotlinJvmProject$1$$special$$inlined$the$1.<init>(TypeOfExtensions.kt:28)	
at com.autonomousapps.DependencyAnalysisPlugin$configureKotlinJvmProject$1.execute(DependencyAnalysisPlugin.kt:1076)	
at com.autonomousapps.DependencyAnalysisPlugin$configureKotlinJvmProject$1.execute(DependencyAnalysisPlugin.kt:58)
```

**To Reproduce**
1. Checkout https://github.com/eugene-krivobokov/dependency-analysis-KotlinProjectExtension-issue
1. `./gradlew :library:projectHealth`

**Expected behavior**

Task executes without error or plugin explains what is wrong with the project.

**Additional context**

**Comment by autonomousapps** [comment]
This is actually expected. Fortunately, the solution is very simple. I have just added a [FAQ](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/wiki/FAQ) that includes this question (because I get it regularly). Let me know if you have any questions after consulting it. I'm closing this issue for now.

**Comment by autonomousapps** [comment]
Hm, I suppose I should add: if you want to try to add something to the plugin to catch and explain this error to users, I'm open to such a PR.
