### ISSUE TITLE
Handle Kotlin internal classes

### ISSUE THREAD

**Issue by bartek-wesolowski** [autonomousapps/dependency-analysis-android-gradle-plugin#433]
Classes that are `internal` in Kotlin shouldn't be added to project's ABI.

Example:
```
internal class A(private val b: B)
```
`B` is taken from `libB`
The plugin suggests that I should add `api libB` instead of `implementation libB`.

**Comment by autonomousapps** [comment]
As far as I can determine with automated testing, this is already the case. I have created a PR with a new test demonstrating this.

Absent a reproducer, I will consider the issue resolved once the PR is merged.
