### ISSUE TITLE
FR: Ability to skip tasks execution for ignored\disabled checks

### ISSUE THREAD

**Issue by eugene-krivobokov** [autonomousapps/dependency-analysis-android-gradle-plugin#438]
**Is your feature request related to a problem? Please describe.**

I've faced a bug with an unknown workaround: #437 
I want to disable temporarily broken checks only in one module.

**Describe the solution you'd like**

**First option: use current API:**

```kotlin
project(':lib') {
            onUnusedDependencies {
                severity("ignore")
            }
            onUsedTransitiveDependencies {
                severity("ignore")
            }
            ... // ignore everything
}
```

The assumption is that ignored check has no expected side effects. Thus, any real logic can be skipped. Tasks could run but do nothing.

**Second option: explicitly disable checks**

```kotlin
project(':lib') {
            onUnusedDependencies {
                enabled.set(false)
            }
            onUsedTransitiveDependencies {
                enabled.set(false)
            }
            ... 
}
```

**Describe alternatives you've considered**

Disable the whole plugin.

**Additional context**

This is also a performance issue. Running checks but ignoring results looks like a waste of resources.

**Comment by autonomousapps** [comment]
This would be very challenging to implement. The filtering behavior as currently implemented is a post-processing step. I agree that it can be inefficient if your intention is to ignore a class of advice, but honestly I have no plans to fix that in the near future, unless someone wants to provide significant funding :upside_down_face:

**Comment by eugene-krivobokov** [comment]
I see, this is reasonable.

I've found a workaround - disable `autoApply` and don't apply the plugin to such modules. I haven't noticed it before. This is a good compromise.

**Comment by autonomousapps** [comment]
By the way, to the extent this request was about that PR you filed, which is now merged, you can use snapshot that got published when `main` finished building. The wiki has [instructions](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/wiki/Adding-to-your-project).
