### ISSUE TITLE
Type references to another package reported as unused, but are necessary for compilation

### ISSUE THREAD

**Issue by rjfioravanti** [autonomousapps/dependency-analysis-android-gradle-plugin#439]
**Plugin version**
0.74.0

**Gradle version**
7.0.2

**(Optional) Android Gradle Plugin (AGP) version**
n/a

**Describe the bug**
I have a Kotlin file like this

```
package com.faire.moduleA

import com.faire.moduleB.Token
import com.faire.moduleB.TokenAdapter

class SomeModule : ParentModule() {
  override fun configureModule() {
    addTypeAdapter<Token>().to<TokenAdapter>()
  }
}
```

The plugin recommends removing the dependency from moduleA onto moduleB, but then compilation fails.

**Comment by autonomousapps** [comment]
Thanks for the issue.

**Comment by autonomousapps** [comment]
Could you provide a minimal reproducer? The specifics might be important here. What kind of functions are `addTypeAdapter()` and `to()`?

**Comment by autonomousapps** [comment]
Any update?

**Comment by autonomousapps** [comment]
Apologies, but I'll have to close this issue at some point in the absence of a reply with more information.

**Comment by autonomousapps** [comment]
Closing as stale.
