### ISSUE TITLE
Don't warn if dependency is declared twice in different scopes

### ISSUE THREAD

**Issue by Mahoney** [autonomousapps/dependency-analysis-android-gradle-plugin#447]
Hi,

I declare a `testImplementation` dependency on kotest in a `subprojects` block in my root `build.gradle.kts`.

In one of my sub projects I need it as an api dependency.

I don't think I should be warned about that. Or at least I should be able to suppress it in some way if it's deliberate.

https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/blob/600fe29669731bf9f4c80a389837ebd49bffca57/src/main/kotlin/com/autonomousapps/internal/ConfigurationsToDependenciesTransformer.kt#L82-L84

**Comment by autonomousapps** [comment]
I think this is a valid request. My inclination is to add support for a new system property that could be used to suppress this warning, and maybe others (I'll have to double-check the various warnings the plugin emits to see if any look like good candidates). Would a **system property** work for you? You could set it in `gradle.properties` like `systemProp.dependency.analysis.nowarning=true` ("nowarning" is just the working title for discussion purposes).

**Comment by Mahoney** [comment]
It would work, yes. Thanks.

**Comment by autonomousapps** [comment]
The plugin no longer warns for this case. Closing.
