### ISSUE TITLE
Clarify onAny API only applies to dependencies and not plugins

### ISSUE THREAD

**Issue by gabrielittner** [autonomousapps/dependency-analysis-android-gradle-plugin#462]
**Is your feature request related to a problem? Please describe.**

Adding
```
issues {
    all {
        onAny {
            severity('fail')
        }
    }
}
``` 
to the build config will only make the build fail on dependency issues, not on plugin issues. For that you need to add
```
onRedundantPlugins {
	severity('fail')
}
```

**Describe the solution you'd like**

There are 3 possible solutions that I'd all be fine with:
1. just clarify this in the documentation
2. change the name of `onAny` to make this clearer
3. make onAny also apply to plugins with the possibility to still explicitly override that in `onRedundantPlugins`

**Additional context**

https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/454

**Comment by autonomousapps** [comment]
I will fix the documentation for this. Thanks.

**Comment by autonomousapps** [comment]
While reminding myself of how this code worked, I decided it was simple enough to fix it up so that it did the intuitive thing. With the associated PR, `onAny` will now also control `onRedundantPlugins`.
