### ISSUE TITLE
Advice issues when library contains annotations that are provided by multiple libraries

### ISSUE THREAD

**Issue by tony-schellenberg** [autonomousapps/dependency-analysis-android-gradle-plugin#472]
**Plugin version**
0.73.0 Seems to work
0.74.0 -> 0.77.0 Does not work as expected

**Gradle version**
7.0.2

**Describe the bug**
There are annotations are that provided by two different libraries. One is declared as `api`, the other is declared as `testImplementation`. The test implementation advice says that it should be switched to `api` even though there is already an api entry that provides this functionality.

**To Reproduce**
1. Set up the code snippets below
2. Run `./gradlew buildHealth`
3. Notice that it says that the `wiremock` library should be switched to `api`

**Expected behavior**
Previous versions of the plug in didn't identify this. Since the `jsr305` library provides these annotations, it seems like they should already be available without changing the advice for the other library.

In the sample provided, the second library is actually unused outside of these annotations but that isn't identified.

**Additional context**
`build.gradle` file content:
```groovy
plugins {
    id 'java-library'
}

repositories {
    mavenCentral()
}

apply plugin: 'com.autonomousapps.dependency-analysis'

dependencies {
    api 'com.google.code.findbugs:jsr305:3.0.2'

    testImplementation 'com.github.tomakehurst:wiremock-jre8-standalone:2.30.1'
}
```

`Main.java` file content:
```java
import javax.annotation.CheckForNull;

public class Main
{
    public static void thisUsesAnntoation(@CheckForNull Object o)
    {
        System.out.println(o);
    }
}
```

**Comment by tony-schellenberg** [comment]
Apologies if this is a breach of etiquette but I was curious if there was any information available on the issue above.

**Comment by autonomousapps** [comment]
No worries. I just haven't triaged this yet. On the face of it I find it confusing for there to be two dependencies that provide the same annotation class. That violates a core invariant in my model. From a classpath perspective, the JVM handles this by "first one wins" rules. From my perspective, it looks like a build anti pattern.

**Comment by tony-schellenberg** [comment]
I did some more digging around on this. I agree that it seems unusual that both jars expose those same classes. In our particular build, the second set only appears as `testImplementation` so I'm suppressing the error in the plugin configuration.

I'm going to close this ticket as it seems like a pretty odd case and I can work around it by excluding the error in the config. In case you're interested, I'm including a bit more context below this in case it's useful somehow. Thanks for all the help on this.
