### ISSUE TITLE
Rename advice$variant task to generateAdvice$variant (avoid ambiguity clash with assemble$variant)

### ISSUE THREAD

**Issue by jrodbx** [autonomousapps/dependency-analysis-android-gradle-plugin#476]
This could totally be a personal preference thing, but I use Gradle task name abbreviation alot, e.g., 

app:iD for app:installDebug, or
app:aD for app:assembleDebug

When applying this plugin, I get the following error when running `app:aD`:

```
Task 'aD' is ambiguous in project ':app'. Candidates are: 'adviceDebug', 'assembleDebug'.
```

Would it be possible to rename the task to something like `generate${VARIANT}Advice` to eliminate the conflict with the task provided by the Android Gradle Plugin?

**Comment by autonomousapps** [comment]
I can do this. I think it actually makes a lot of sense to generally avoid stepping on other very common tasks, such as `assemble...`. Is this the only one causing you trouble?

FWIW, I prefer `generateAdvice$variant`, because that's the format I use in all my other tasks. Does that work for you?

**Comment by jrodbx** [comment]
> Is this the only one causing you trouble?

Yes.

> FWIW, I prefer `generateAdvice$variant`, because that's the format I use in all my other tasks. Does that work for you?

For sure.  My suggestion was going by AGP-style but i don't have any opinion either way.

**Comment by autonomousapps** [comment]
Cool, thanks for confirming. I fixed this in the associated PR. You can already use it with a snapshot, but you can also wait for the next release (0.78.0), which is probably today.
