### ISSUE TITLE
Don't recommend adding direct dependencies if they're only used by generated code?

### ISSUE THREAD

**Issue by autonomousapps** [autonomousapps/dependency-analysis-android-gradle-plugin#48]

**Comment by autonomousapps** [comment]
For example, I think that `org.jetbrains:annotations` is either added by the Kotlin plugin or brought in transitively, and in either case does not appear in source. Added to generated code or only present in bytecode (added by kotlinc).

**Comment by ZacSweers** [comment]
Examples:

- Annotated by `@Generated`
- In a package containing `.generated`
- Under the `build` dir

**Comment by autonomousapps** [comment]
Added a 1.0 milestone. This issue is important enough that I consider it a prereq for 1.0 status.

**Comment by ZacSweers** [comment]
Related - a `.generated` support would need to be a custom package exclusion, which also opens up excluding `.internal` (another convention)
