### ISSUE TITLE
Change plugin advice message when analyzing annotation processors failed

### ISSUE THREAD

**Issue by gabrielittner** [autonomousapps/dependency-analysis-android-gradle-plugin#485]
**Is your feature request related to a problem? Please describe.**

Currently the plugin will print this warning `Could not reflectively access processor class dagger.internal.codegen.ComponentProcessor` during the build and then in the end will advice to remove kapt because it's unused:
```
Plugin advice:
- kotlin-kapt: this project has the kotlin-kapt (org.jetbrains.kotlin.kapt) plugin applied, but no annotation processors (or no used annotation processors), which is redundant.
```

However since analyzing the processor failed it can't actually determine whether kapt is unused. In bigger projects the earlier log is easy to miss, so in many cases this will lead to users removing kapt and then realizing it was actually needed when their next build fails. 

**Describe the solution you'd like**

Change the plugin advice message to "Could not determine whether kapt is used because processor ... could not be accessed" when analyzing a processor fails.

**Additional context**

Initial discussion happened here https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/479

**Comment by autonomousapps** [comment]
Thanks for the issue. I think this is a valid enhancement for 1.0, given that it has come up more than once.

**Comment by autonomousapps** [comment]
I'm going to close this as `wontfix` based on the idea that this kind of failure doesn't happen anymore.
