### ISSUE TITLE
Make GeneralUsageDetectionTask cacheable

### ISSUE THREAD

**Issue by eugene-krivobokov** [autonomousapps/dependency-analysis-android-gradle-plugin#486]
**Is your feature request related to a problem? Please describe.**

`com.autonomousapps.tasks.GeneralUsageDetectionTask` task is quite heavy:

![Screenshot from 2021-09-28 12-51-20](https://user-images.githubusercontent.com/1104540/135064985-abac1d6d-f89d-458c-9c0f-ebce0266a495.png)

**Describe the solution you'd like**

Make this task cacheable

**Describe alternatives you've considered**

--

**Additional context**

Plugin version: 0.78.0
Gradle: 7.2

**Comment by autonomousapps** [comment]
This is another one that looks like an oversight. We can just add `@CacheableTask` to the task declaration. Would you want to contribute that?

**Comment by eugene-krivobokov** [comment]
Sure, with pleasure. Just can't give exact commitments about dates.

**Comment by SubhrajyotiSen** [comment]
@eugene-krivobokov Do you still want to work on this fix? Else, I'd like to work on this

**Comment by eugene-krivobokov** [comment]
@SubhrajyotiSen , feel free to take it

**Comment by SubhrajyotiSen** [comment]
Looks like this issue can be closed since `GeneralUsageDetectionTask` was deleted in https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/commit/183b175ddbfe63dfec18da247ef4cf09bce285f5
