### ISSUE TITLE
Cache of AnalyzeJarTask is not relocatable

### ISSUE THREAD

**Issue by eugene-krivobokov** [autonomousapps/dependency-analysis-android-gradle-plugin#488]
**Build scan link**

--

**Plugin version**

0.78.0

**Gradle version**

7.2

**(Optional) Android Gradle Plugin (AGP) version**

7.0.2

**Describe the bug**

Cache miss of `AnalyzeJarTask` between different machines.

**To Reproduce**

I've checked it on the same commit on different machines similar to this [doc](https://docs.gradle.org/current/userguide/build_cache_debugging.html#caching_relocation_test)

- `./gradlew :module:projectHealth` on the first machine. It pushes to a remote build cache
- `./gradlew :module:projectHealth` on the second machine. It reads from the remote build cache

Expected result: AnalyzeJarTask is `FROM_CACHE`
Actual result: executed.

**Expected behavior**

The task is relocatable.

**Additional context**

I narrowed it down to the root cause.

`./gradlew :module:projectHealth` shows the difference in inputs:

```
// machine 1

> Task :module:analyzeJarRelease
Appending implementation to build cache key: com.autonomousapps.tasks.AnalyzeJarTask_Decorated@e78b8455a7d7eca5bf491b961b530fff
Appending additional implementation to build cache key: com.autonomousapps.tasks.AnalyzeJarTask_Decorated@e78b8455a7d7eca5bf491b961b530fff
Appending input file fingerprints for 'allArtifacts' to build cache key: 0382434ae95159f487e2ac43802e8459 - RELATIVE_PATH{/home/ekrivobokov/project/module/build/reports/dependency-analysis/release/intermediates/artifacts.json='artifacts.json' / 89d3d3d2e98941190304333c7f3e7c71}
Appending input file fingerprints for 'androidLinters' to build cache key: 98163082037c59a29efbd867d34c3548 - IGNORED_PATH{...}
Appending input file fingerprints for 'artifactFiles' to build cache key: ddb32eb9d84a5e01fd21fe7c8cb2ebd1 - CLASSPATH{...}
Appending input file fingerprints for 'testArtifactFiles' to build cache key: e393e963da94c4bf226972a08bb294cc - CLASSPATH{...}
Appending output property name to build cache key: allComponentsReport
Appending output property name to build cache key: allComponentsReportPretty
Build cache key for task ':module:analyzeJarRelease' is 112841c19cdf27ab0811a0df3e3b26c7

// machine 2

> Task :module:analyzeJarRelease
Appending implementation to build cache key: com.autonomousapps.tasks.AnalyzeJarTask_Decorated@e78b8455a7d7eca5bf491b961b530fff	
Appending additional implementation to build cache key: com.autonomousapps.tasks.AnalyzeJarTask_Decorated@e78b8455a7d7eca5bf491b961b530fff	
Appending input file fingerprints for 'allArtifacts' to build cache key: 11e308b0a9f5e188e40e2f61f4eaa537 - RELATIVE_PATH{/Users/ekrivobokov/project/module/build/reports/dependency-analysis/release/intermediates/artifacts.json='artifacts.json' / 6ed5f24c323f102f048a652af4a6ff3e}	
Appending input file fingerprints for 'androidLinters' to build cache key: 98163082037c59a29efbd867d34c3548 - IGNORED_PATH{...}
Appending input file fingerprints for 'artifactFiles' to build cache key: ddb32eb9d84a5e01fd21fe7c8cb2ebd1 - CLASSPATH{...}
Appending input file fingerprints for 'testArtifactFiles' to build cache key: e393e963da94c4bf226972a08bb294cc - CLASSPATH{...}
Appending output property name to build cache key: allComponentsReport	
Appending output property name to build cache key: allComponentsReportPretty	
Build cache key for task ':module:analyzeJarRelease' is 6e52e33c96407cd2b19abfea2735f7d3
```

The difference is only in the `allArtifacts` input.

```
/**
   * A [`Set<Artifact>`][Artifact].
   */
  @get:PathSensitive(PathSensitivity.RELATIVE)
  @get:InputFile
  abstract val allArtifacts: RegularFileProperty
```

I've compared the content and found these differences:

1. They contain the same dependencies, but the records are sorted randomly. The same dependency is on different positions in Json arrays. 
The probable workaround is to sort records before serializing them to file.

2. Absolute paths to project files: 

```json
{
        "dependency": {
            "identifier": ":utils:lang"
        },
        "file": "/home/ekrivobokov/project/another-module/build/libs/module.jar"
}

VS

{
        "dependency": {
            "identifier": ":utils:lang"
        },
        "file": "/Users/ekrivobokov/project/another-module/build/libs/module.jar"
}
```
The probable workaround is to store paths relative to the root project dir: `another-module/build/libs/module.jar`

3. Absolute paths to external dependencies:

```json
{
        "dependency": {
            "identifier": "com.squareup.retrofit2:retrofit",
            "resolvedVersion": "2.9.0"
        },
        "file": "/home/ekrivobokov/.gradle/caches/modules-2/files-2.1/com.squareup.retrofit2/retrofit/2.9.0/d8fdfbd5da952141a665a403348b74538efc05ff/retrofit-2.9.0.jar"
}

VS

{
        "dependency": {
            "identifier": "com.squareup.retrofit2:retrofit",
            "resolvedVersion": "2.9.0"
        },
        "file": "/Users/ekrivobokov/.gradle/caches/modules-2/files-2.1/com.squareup.retrofit2/retrofit/2.9.0/d8fdfbd5da952141a665a403348b74538efc05ff/retrofit-2.9.0.jar"
}
```
The probable workaround is to store paths relative to the Gradle cache dir: `com.squareup.retrofit2/retrofit/2.9.0/d8fdfbd5da952141a665a403348b74538efc05ff/retrofit-2.9.0.jar`

**Comment by autonomousapps** [comment]
This is the ultimate cause: https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/blob/main/src/main/kotlin/com/autonomousapps/tasks/ArtifactsReportTask.kt#L40-L49

I.e., the output of `ArtifactsReportTask` is based on an input (to _that_ task) that has absolute path sensitivity.

It's possible there's a solution, but I don't know offhand what it would look like and can't prioritize it right now.

**Comment by autonomousapps** [comment]
`AnalyzeJarTask` no longer exists in v1.0.0rcX. There are still tasks that use absolute-path sensitivity, however.

Since you already did significant analysis of the problem, would this be something you'd be willing to work on? That is:
1. Find tasks with non-relocatable outputs.
2. Ensure outputs are sorted before being serialized.
3. Take note of the tasks using absolute-path normalization and see if they can be relativized.

I would propose doing those three steps in that order. That is, the first step is getting a list of tasks that need to be optimized. The second step is relatively simple (and may already be done -- in my work on the new model, I made an effort to ensure all outputs are sorted, but I may have missed a few cases). The third step is the most complex.

**Comment by eugene-krivobokov** [comment]
Thanks for the proposal.
Unfortunately, most probably I'll have no time in the near future.

**Comment by autonomousapps** [comment]
Closing this for now.
