### ISSUE TITLE
Cache of InlineMemberExtractionTask is not relocatable

### ISSUE THREAD

**Issue by eugene-krivobokov** [autonomousapps/dependency-analysis-android-gradle-plugin#489]
**Build scan link**

--

**Plugin version**

0.78.0

**Gradle version**

7.2

**(Optional) Android Gradle Plugin (AGP) version**

7.0.2

**Describe the bug**

Cache miss of `InlineMemberExtractionTask` between different machines.

**To Reproduce**

I've checked it on the same commit on different machines similar to this [doc](https://docs.gradle.org/current/userguide/build_cache_debugging.html#caching_relocation_test)

- `./gradlew :module:projectHealth` on the first machine. It pushes to a remote build cache
- `./gradlew :module:projectHealth` on the second machine. It reads from the remote build cache

Expected result: AnalyzeJarTask is `FROM_CACHE`
Actual result: executed.

**Expected behavior**

The task is relocatable.

**Additional context**

I narrowed it down to the root cause - `artifacts` input.
`ArtifactsReportTask.output` - see details in #488, the same reason.

**Comment by autonomousapps** [comment]
Unfortunately, there have been cases where I must use absolute path sensitivity, which obviously makes a cache entry non-relocatable across machines. I think this is one such case.

**Comment by eugene-krivobokov** [comment]
Could you please give an example?

I was thinking about ways of "normalizing" absolute paths by using shortcuts for GRADLE_USER_HOME, PROJECT_DIR, and so on. 

```
/home/user/.gradle/caches/modules-2/files-2.1/com.squareup.retrofit2/retrofit/2.9.0/d8fdfbd5da952141a665a403348b74538efc05ff/retrofit-2.9.0.jar

--->

GRADLE_USER_HOME/caches/modules-2/files-2.1/com.squareup.retrofit2/retrofit/2.9.0/d8fdfbd5da952141a665a403348b74538efc05ff/retrofit-2.9.0.jar
```
At first glance, some cases look interchangeable.

**Comment by autonomousapps** [comment]
I'm open to PRs addressing this, but I don't have time to prioritize it right now. To be honest, I'm not entirely sure how to relativize paths to the gradle user home directory.

The reason I switched from relative path sensitivity to absolute is simply that the path to a jar in the gradle user home directory got cached and it wasn't present on a different machine, leading to a FileNotFoundException. I'm not entirely clear on how those paths are constructed.

**Comment by autonomousapps** [comment]
This task no longer exists. Closing.

If its equivalent in the new model (rc02+) has any issues, please re-open with relevant information.
