### ISSUE TITLE
Print task outcomes even in case the task is cached

### ISSUE THREAD

**Issue by vlsi** [autonomousapps/dependency-analysis-android-gradle-plugin#5]
```
$ gw misusedDependenciesMain
..
BUILD SUCCESSFUL in 1s
14 actionable tasks: 14 up-to-date
```

I can't really see task output. It is sad.

I suggest that the task that prints output to the screen should be never up to date. Then the user could run the task again and again and see the current output.

**Comment by autonomousapps** [comment]
This would require extra tasks that just printed output from the up-to-date or cached tasks. It could be done, but it's not a high priority.

**Comment by autonomousapps** [comment]
Please try the `:buildHealth` task on the root project (check the readme).

**Comment by autonomousapps** [comment]
Closing, as this is now the default behavior for the recommended tasks.
