### ISSUE TITLE
Allow configuration of printing duplicate declerations

### ISSUE THREAD

**Issue by mvegter** [autonomousapps/dependency-analysis-android-gradle-plugin#507]
**Is your feature request related to a problem? Please describe.**

Currently the `locateDependencies<VARIANT>` are printing duplicate declarations which can be lost in large Gradle projects. This also prevents proper caching of this task as an up-to-date/from-cache is not executing any println's

**Describe the solution you'd like**

Include the duplicate declarations as a separate category for the `projectHealth`, which can be configurable to print or not to print.

**Describe alternatives you've considered**

**Additional context**

**Comment by autonomousapps** [comment]
Resolved via eafc9b53c5ac1c2b7aa28172290039a10b378810.
