### ISSUE TITLE
buildHealth doesn't fail while projectHealth does

### ISSUE THREAD

**Issue by eugene-krivobokov** [autonomousapps/dependency-analysis-android-gradle-plugin#518]
**Build scan link**

--

**Plugin version**

0.78.0

**Gradle version**

7.2

**(Optional) Android Gradle Plugin (AGP) version**

7.0.3

**Describe the bug**

`projectHealth` finds an unused dependency. It fails with severity = fail.  
`buildHealth` doesn't fail.

**To Reproduce**
https://github.com/eugene-krivobokov/dependency-analysis-buildHealth-failure-condition-reproducer  
See the README.

**Expected behavior**

`buildHealth` fails if any `projectHealth` fails. 

**Additional context**

- Issues are customized only in subprojects due to #409 (`systemProp.dependency.analysis.autoapply=false`).
- Enabling strict mode fixes the issue.

**Comment by autonomousapps** [comment]
Closing as works-as-intended.
