### ISSUE TITLE
Select the variants to run on

### ISSUE THREAD

**Issue by blundell** [autonomousapps/dependency-analysis-android-gradle-plugin#519]
**Is your feature request related to a problem? Please describe.**

Our build has a few variants, (flavor / build type combo's), some of them are invalid in certain circumstances. However it seems this plugin runs on all combinations?

**Describe the solution you'd like**

Is there a way, that we can pass in what variants we want to run on?

For example, perhaps I just want to analyse the `debugPaid`, `debugFree` & `releaseFree` variants but not the `releasePaid` (as a contrived exampled).  Or another example run on `debugUnitTest` but skip `releaseUnitTest` (right now you can disable all test analysis, but not a subset `systemProp.dependency.analysis.test.analysis = false`)

**Describe alternatives you've considered**

My gradle foo isn't up to scratch but I imagine you can also disable these variants elsewhere outside the plugin, but that wouldn't be explicit as to the reason of why we are doing it.

**Additional context**

Thanks for your time!
Sorry if this is obviously a thing I should do in gradle and not in your plugin. 😅

**Comment by tronku** [comment]
@autonomousapps any update on this??

**Comment by autonomousapps** [comment]
I have no plans to introduce new features before the 1.0 release.

**Comment by autonomousapps** [comment]
If someone wants to take this on and create a PR, here's my take on how it might be implemented:
1. I don't think it makes sense to add DSL support. Rather, I'd prefer to see an allow-list of variants to analyze as a comma-delimited string set via Gradle property. Like, `dependency.analysis.android.variants=debug,release` (in `gradle.properties`). Alternatively, a deny-list of variants to exclude. The code managing this should be in [Flags.kt](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/blob/main/src/main/kotlin/com/autonomousapps/Flags.kt)
2. Update code [here](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/blob/main/src/main/kotlin/com/autonomousapps/subplugin/ProjectPlugin.kt#L157) and [here](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/blob/main/src/main/kotlin/com/autonomousapps/subplugin/ProjectPlugin.kt#L196) to skip non-matching variants.
3. Add one or more functional tests verifying the new behavior.

**Comment by tronku** [comment]
@autonomousapps picking this up, please assign this to me

**Comment by dzirbel** [comment]
What might be the most useful for my project - and what I believe most Android plugins do as well - is expose variant-specific versions of the task, like `projectHealthDebug` or `projectHealthPaidRelease`, which run just on that variant with the `projectHealth` task depending on all the variant-specific tasks. I will take a stab at implementing this but it may have far-reaching consequences so I wanted to ask if there were any particular reasons to avoid this approach?
