### ISSUE TITLE
Analysis result differs between windows and linux builds

### ISSUE THREAD

**Issue by cve92** [autonomousapps/dependency-analysis-android-gradle-plugin#529]
**Plugin version**
0.78.0

**Gradle version**
7.3

**Describe the bug**
The dependency analysis result differs between windows and linux builds. On linux builds (our CI-Environment) there are advices of type `onIncorrectConfiguration` for ~29 projects which suggest to move dependencies from `implementation` to the `testImplementation` configuration. These advices are correct and after following them the code still compiles. However they are completely missing on a local windows build.

**To Reproduce**
1. declare an `implementation` dependency to any module or other project in a `build.gradle`. Something like `implementation project(':foo')`.
2. use a class of that dependency in a test source file. For example call `Foo.hello()` in `src/test/java/MyTest.java`. Assure there is **no reference** from a production source file to any class of that dependency
3. switch to a windows machine
2. run the `buildHealth` task in the root project (or `projectHealth` for the project that has the dependency)
3. **no advice is** reported to move the dependency to the `testImplementation` configuration

**Expected behavior**
advice **is reported** to move the dependency to the `testImplementation` configuration

**Additional context**
After doing some investigation the problem seems to be related to the function `ProjectClassReferenceParser#variantsFromPath`. This function always returns an empty set on windows. This causes the information which variant a file belongs to to be lost. The endsWith predicate always evaluates to `false` because both paths involved are wrongly constructed on windows. For example a path such as 1 does not end with a path such as 2.
1. `"C:\projects\myproj\build\classes\java\main\org\foo\Bar.class/Bar.class"`
2. `"src\main\java\org\foo\Bar" + ".class"`

The first path is constructed in `ProjectClassReferenceParser#normalizePath` which receives a `filePath` parameter that contains a platform-specific path. Therefore the forwardSlash-based normalization logic does not correctly work on windows. For example the function returns `C:\projects\myproj\build\classes\java\main\org\foo\Bar.class/Bar.class` instead of the expected `C:\projects\myproj\build\classes\java\main\org\foo\Bar.class`.

The second path (or rather only the `src\main\java\org\foo\Bar` part without the `.class` suffix) ist constructed in `CreateVariantFiles#toVariantFiles` which uses `project.relativePath(file)` to return a relative path. This results in a platform-specific path. Therefore the forwardSlash-based Logic to remove the path segments `src`, `main` and `java` (or respective source set name instead of `main`) does not behave correctly on windows, resulting in a wrong `filePath` for each `VariantFile` (for example `src\main\java\org\foo\Bar` instead of the expected `org\foo\Bar`)

**Comment by autonomousapps** [comment]
Thank you so much for this thorough report!

Would you be interested in resolving this issue by using OS-agnostic path separators? Very sorry for my Linux-centered-ness here. It is probably also worth running the test matrix on Windows as well as Ubuntu, although I'm concerned about what that does to CI time with Github Actions.

FYI, some of the classes you mention are actually going away in the near future. I'm working on a redesign of the plugin's internals and there is no more `VariantFile` concept, for example. But I will definitely make a pass to ensure I'm not baking in assumptions about path separators.

**Comment by cve92** [comment]
Thank you for your quick reply. Sure, would be happy to contribute a Fix for this. Think I might find some time for this within the next few days.

**Comment by autonomousapps** [comment]
Resolved by https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/pull/530.
