### ISSUE TITLE
runtimeOnly dependency is advised to be removed

### ISSUE THREAD

**Issue by Vampire** [autonomousapps/dependency-analysis-android-gradle-plugin#563]
**Plugin version**
0.79.0

**Gradle version**
7.3.3

**Describe the bug**
I have a Weld project and for faster processing I include `org.jboss:jandex` as `runtimeOnly` dependency.
The plugin advises to remove that dependency.
I think it is never a good idea to advise removing `runtimeOnly` dependencies.
The whole point of a `runtimeOnly` dependency is, that you don't need it for compilation, but that it might change behavior at runtime which this dependency does.
An advice to change it to `api` or `implementation` where needed might be appropriate, but actually not necessary as in that case it would not even compile.

**Expected behavior**
Not being recommended to remove a runtime only dependency.

**Comment by Vampire** [comment]
Actually what you need as dependencies is
```kts
dependencies {
    implementation("org.hibernate:hibernate-core:5.6.3.Final")
    runtimeOnly("org.jboss:jandex:2.4.2.Final")
}
```
and then it will complain about `runtimeOnly("org.jboss:jandex:2.2.3.Final")`.

If only one of the two dependencies is used, there is no advice generated.

---

And actually an advice to change it to `api` or `implementation` where needed might be actually needed if it is used in the project directly but only in the compile classpath as transitive dependency. But I guess this is already the case.

**Comment by autonomousapps** [comment]
Thanks for the report. I'm surprised at this, because the plugin has logic to do exactly what you expect, which is to not advise removing a `runtimeOnly` dependency. Two questions:
1. Could you provide more detail about the project in question?
2. Could you try running `buildHealth` again, but with `-Dv=2`? That's a feature flag hiding a new implementation, which might give you the result you expect.

**Comment by Vampire** [comment]
As I said in the comment, the `runtimeOnly` of the project itself is `2.4.2.Final` which is not displayed.
But somehow when I add the `runtimeOnly` then suddenly the `hibernate-core` dependency brings in the `2.2.3.Final` one that is complained about.

Regarding the project, you don't need more information, I tried it in an otherwise empty play project.
Just define those two dependencies and apply your plugin, then execute the `buildHealth` task.

Algorithm v2 suffers from the same problem.

**Comment by autonomousapps** [comment]
I cannot reproduce the issue with the limited information you have provided. Do you have a build scan?

**Comment by Vampire** [comment]
I'm not sure why you cannot reproduce it, it is really not more than what I said.
Here a simple reproducer:
```sh
$ find -type f -not -name 'gradlew*' -not -name 'gradle-wrapper.jar' -exec sh -c 'echo; echo {}; cat {};' \;

./build.gradle.kts
plugins {
    `java-library`
    id("com.autonomousapps.dependency-analysis") version "0.79.0"
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("org.hibernate:hibernate-core:5.6.3.Final")
    runtimeOnly("org.jboss:jandex:2.4.2.Final")
}

./gradle/wrapper/gradle-wrapper.properties
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-7.3.3-bin.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists

./settings.gradle.kts
rootProject.name = "showcase"

$ ./gradlew buildHealth

> Task :buildHealth
Advice for root project
Unused dependencies which should be removed:
  runtimeOnly("org.jboss:jandex:2.2.3.Final")

This build is composed of 1 individual projects, with an average complexity of 17.0 nodes and 20.0 edges. If you follow all of this advice, the resultant complexity will average 17.0 nodes and 20.0 edges.

See machine-readable report at ...\build\reports\dependency-analysis\advice-holistic.json


BUILD SUCCESSFUL in 8s
25 actionable tasks: 25 executed

$ ./gradlew buildHealth -Dv=2

> Task :buildHealth
Advice for root project
Unused dependencies which should be removed:
  runtimeOnly("org.jboss:jandex:2.2.3.Final")

This build is composed of 1 individual projects, with an average complexity of 17.0 nodes and 20.0 edges. If you follow all of this advice, the resultant complexity will average 17.0 nodes and 20.0 edges.

See machine-readable report at ...\build\reports\dependency-analysis\advice-holistic.json


BUILD SUCCESSFUL in 6s
25 actionable tasks: 1 executed, 24 up-to-date
```

And here the build scan: https://gradle.com/s/wm7onjpfn7ob2

**Comment by autonomousapps** [comment]
Ah, I can see why I couldn't repro it earlier. The issue doesn't exist anymore on HEAD. So, if you `includeBuild ...` and `-Dv=2`, the report is empty, which is expected. If you confirm that, we can close this issue.

**Comment by Vampire** [comment]
Yes, with `0.80.0` and `v=2` the issue goes away.
When will `v=2` become the default?

Is it intended that with `v=2` the violations are not visible by default anymore but you have to look inside the text report?
I found it pretty handy, because if something is failing I ususally want to know what exactly.
Can this be re-enabled by some setting?

**Comment by autonomousapps** [comment]
Yes, that was intentional, and yes, I could consider re-enabling it. The reason for that decision is that for large projects, the buildHealth report can be HUGE. Printing it to console is absurd in such a case. Could you file an issue with this request?

v2 will be the default as soon as I implement the remaining missing features. You can find a couple of PendingFeatureIf annotations in the test suite.

**Comment by Vampire** [comment]
Sure: #571
