### ISSUE TITLE
Intermediate outputs in V2

### ISSUE THREAD

**Issue by cdsap** [autonomousapps/dependency-analysis-android-gradle-plugin#567]
Hi, thanks for the plugin. We integrated it into our internal tooling process since one year ago.

Currently, in our use case(version `0.76.0`), we consume the intermediate outputs to track relevant information on a highly modularized Android project. 
The process starts once we have new changes in the main integration branch, we execute the main `advice$Variant` for all modules. Then for each module, we parse the outputs based on our requirements:
```
 Metric( "advice_remove_dependencies_module",  dependencyAnalysisParser.advice(it.module.osPath) ?: -1)                     
```
Finally the information is stored and used in different dashboards for the team:

<img width="1595" alt="Screen Shot 2022-01-17 at 8 51 23 AM" src="https://user-images.githubusercontent.com/475733/150060088-0fb35e21-3ce7-420d-bb59-1738d5a0a55e.png">

The implementation is quite simple: We just parse the json files and apply the required filter: `parseAdvice(osPath)?.removeAdvice?.size`. The Current outputs used in the process:
```
all-used-classes.json
artifacts.json
imports.json
advice-console.json
```

We find  the intermediate information strongly useful because it helps us in our observability tasks giving more inputs on possible issues in the dependency graph.  

The main question would be: What's the support for intermediate outputs in V2? If there is no support, what would be the method to retrieve information calculated by the task? Thanks!

**Comment by autonomousapps** [comment]
Thanks for the issue.

Summary:
1. `all-used-classes.json` --> `exploding-bytecode.json`, with more information.
1. `artifacts.json` --> same, but slightly different format with an updated model.
1. `imports.json` --> `exploded-source.json`
1. `advice-console.json` --> `build-health-report.txt` and/or `project-health-report.txt`

As a rule, outputs in `intermediates` are intended to be volatile with no API stability guarantees. This is partially enforced by the fact that the model classes all have `internal` visibility. That said, I don't have any plans for this new model to change again after it becomes the default at some point in the next weeks-months.

Please give it a try with `./gradlew buildHealth -Dv=2` and let me know what you think.

**Comment by cdsap** [comment]
Thanks for the clarification on the intermediates/internal, it makes sense. 
Next week will try `buildHealth -Dv=2`

**Comment by cdsap** [comment]
Hi Tony, I tested the plugin directly in the project(500 modules). 
The output is more precise, I like it. We should quickly update our internal processes when updating to `v2`.
Thanks!

**Comment by autonomousapps** [comment]
Great, thanks for letting me know!

**Comment by autonomousapps** [comment]
FYI, I have a PR checking all the tests pass for v2, and I'm looking to merge it sooner than later (but no exact date just yet). At that point, the version will be 1.0.0-rc01. https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/pull/581

**Comment by cdsap** [comment]
thanks, once is deployed I will test against the rc

**Comment by autonomousapps** [comment]
@cdsap you can test this right now against `1.0.0-rc01`.

**Comment by cdsap** [comment]
Hi, so far test on `1.0.0-rc02` looks ok. Outputs generated and processed correctly. No problems using the new model.
I think we are ready to migrate with the new release. 
Thanks

**Comment by autonomousapps** [comment]
Ok! I'm going to close this ticket. Feel free to reopen it, or create a new one, if you run into any issues. In fact, it might be interesting to open a ticket to create an intentional API for your use-case, but I'll leave that up to you.

Note that, with rc02, the old model has been deleted, so the new model is all that's left. I don't expect to make any changes to the data classes, but it's possible.
