### ISSUE TITLE
Module that provides constant marked as unused

### ISSUE THREAD

**Issue by Tapchicoma** [autonomousapps/dependency-analysis-android-gradle-plugin#57]
**Gradle version** - 6.1.1
**Android Gradle Plugin (AGP) version** - 3.5.3

**Describe the bug**

I am running `adviceDebug` task on a submodule ":one" that has a dependency on one a constant defined in submodule ":two" object class. Submodule ":two" is reported as unused, though it is needed.

**Expected behavior**
Submodule dependency ":two" is not reported as unused.

**Comment by emartynov** [comment]
Also got this one. It is a kotlin const like:
```
const val PRIVACY_POLICY = "privacy"
```

**Comment by emartynov** [comment]
I found one more case when const was defined in java class:
```
  @IntDef({NONE, MORE_ERROR, MORE_NEW_FEATURE})
  @Retention(RetentionPolicy.SOURCE)
  public @interface FeedbackSource
  {
    int NONE = 0;
  }
```

And usage is:
```
import company.FeedbackSource

private var feedbackSource = FeedbackSource.NONE
```

**Comment by autonomousapps** [comment]
Constants get inlined by the compiler and as such are not present (as
constants) in the bytecode. So this is a hard one, but there might be
workarounds.

**Comment by autonomousapps** [comment]
I think I can reuse some of my existing infrastructure around source-code analysis to detect usage of constants. This issue will be near the top of my list to resolve.

**Comment by autonomousapps** [comment]
Could you both please try the latest snapshot, 0.20.1-SNAPSHOT (https://plugins.gradle.org/plugin/com.autonomousapps.dependency-analysis) and let me know if this fixes your issue?

**Comment by Tapchicoma** [comment]
Will try to do it today, still have integration branch around.
