### ISSUE TITLE
Clarify that plugin requires Java 11.

### ISSUE THREAD

**Issue by oehme** [autonomousapps/dependency-analysis-android-gradle-plugin#575]
[FirstClassloader](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/blob/186b6a9e42ce3064f1a0fd932e336955df489e33/src/main/kotlin/com/autonomousapps/tasks/FindDeclaredProcsTask.kt#L396) uses named URLClassloaders, which is an API introduced in Java 9.

You might want to use `release` instead of `sourceCompatibility` to catch these kinds of issues. I assume Java 8 support was intended, given the sourceCompatibility in your build script.

**Comment by autonomousapps** [comment]
Thanks for the report.

**Comment by autonomousapps** [comment]
https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/pull/578
