### ISSUE TITLE
Should make full use of ASM9

### ISSUE THREAD

**Issue by oehme** [autonomousapps/dependency-analysis-android-gradle-plugin#577]
The project already depends on ASM9, but instructs ASM to only use its capabilities from version 8: https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/blob/e8879cb762c6c795b628b2ac41c2e8f2e63f00cf/src/main/kotlin/com/autonomousapps/internal/asm.kt#L20.

**Comment by autonomousapps** [comment]
what is the advantage to making such a change?

**Comment by oehme** [comment]
Support for new Java features like sealed classes.
