### ISSUE TITLE
Reported unused module but dimension resource is used from it

### ISSUE THREAD

**Issue by emartynov** [autonomousapps/dependency-analysis-android-gradle-plugin#59]
**Gradle version**
6.0.1

**Android Gradle Plugin (AGP) version**
3.5.3

**Describe the bug**
I have a module A that defines enum with dimension from module B:
```
enum class IconSize(@DimenRes val res: Int) {
    SMALL(R.dimen.icon_size_small),
    NORMAL(R.dimen.icon_size);
}
```
Unfortunately, in this case module B reported as a non-used in module A.

**To Reproduce**
1. Use dimension in kotlin enum

**Expected behavior**
The module should not be reported as unused.

**Comment by emartynov** [comment]
I found one more, probably similar but style from different module:
```
class StealthModeDialog(private val onClick: () -> Unit) : AppCompatDialogFragment() {

    init {
        setStyle(DialogFragment.STYLE_NORMAL, R.style.Theme_Yolt_Dialog_Fancy)
    }
```

**Comment by autonomousapps** [comment]
This is probably because you've imported non namespaced (merged) R files. I
need to update the Readme to note this is a limitation that will not be
fixed. Later versions of AGP use namespaced R files by default. In 3.5, you
can opt in with a specific boolean value in gradle.properties.

**Comment by autonomousapps** [comment]
Can you confirm if you have the `android.namespacedRClass=true` flag set in your `gradle.properties`? I assume that you do _not_.

**Comment by emartynov** [comment]
I don't have this flag. If I add it my project won't build. But it is on our TODO list.

**Comment by emartynov** [comment]
You're completely right about merged R file. So close the issue and update README, please.

**Comment by autonomousapps** [comment]
I'll leave the issue open for the moment, while I consider if I want to invest time in resolving this (very real) problem for current versions of AGP following default behavior.

**Comment by autonomousapps** [comment]
I have updated the readme and will close this for now. I may revisit later, time permitting.
