### ISSUE TITLE
Dependencies with top level Kotlin functions indicated as unnecessary

### ISSUE THREAD

**Issue by bartek-wesolowski** [autonomousapps/dependency-analysis-android-gradle-plugin#594]
**Plugin version**
1.0.0-rc01

**Gradle version**
7.3.3

**(Optional) Android Gradle Plugin (AGP) version**
7.1.1

**Describe the bug**
The plugin detects libraries exposing top-level Kotlin functions as unused, e.g. `mockito-kotlin`. E.g. when you use `given` from `mockito-kotlin` in your tests then it still indicates that `mockito-kotlin` is not necessary.

**To Reproduce**
1. Create a new Android Project.
2. Add a dependency on `mockito-kotlin`.
3. Use the `given` function from `mockito-kotlin` in the example unit test.
4. Run the dependency analysis. It will say that `mockito-kotlin` is unnecessary.

**Expected behavior**
`mockito-kotlin` shouldn't be indicated as unnecessary.

**Comment by autonomousapps** [comment]
Thanks for the issue. There's a regression test for this behavior, so I'm a little confused what's going on, but I will check!

**Comment by autonomousapps** [comment]
I cannot reproduce this with rc02. I have
```groovy
testImplementation "org.mockito.kotlin:mockito-kotlin:4.0.0"
```
and
```
import org.junit.Test
import org.mockito.kotlin.given

class SampleTest {

  @Test fun test() {
    given {  }
  }
}
```
And when I run `./gradlew app:projectHealth`, the only advice I see is
```
Transitively used dependencies that should be declared directly as indicated:
  testImplementation("org.mockito:mockito-core:4.0.0")
```
Am I missing something?

**Comment by bartek-wesolowski** [comment]
Sorry for the trouble. Apparently it does work for the application module, but fails for library modules. Create a new Android library module, add a `mockito-kotlin` dependency there and create your `SampleTest`. The plugin will indicate `mockito-kotlin` as unused.

**Comment by autonomousapps** [comment]
Indeed the issue was specifically with Android library analysis of test source sets.
