### ISSUE TITLE
Consider using .json extensions for json files

### ISSUE THREAD

**Issue by vlsi** [autonomousapps/dependency-analysis-android-gradle-plugin#6]
`all-declared-dependencies-pretty.txt` looks like a JSON file, while it is saved as txt.
It impacts syntax highlighting

**Comment by autonomousapps** [comment]
Fixed with https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/commit/ce43777ea615be2ad4af47ef6d91c4ce3bc05e9b.
