### ISSUE TITLE
Re-implement "reason" for v1.0.

### ISSUE THREAD

**Issue by algattik** [autonomousapps/dependency-analysis-android-gradle-plugin#608]
**Build scan link**

**Plugin version**
1.0.0-rc03

**Gradle version**
7.3

**(Optional) Android Gradle Plugin (AGP) version**

**Describe the bug**

```
$ ./gradlew :core:contract:projectHealth
> Existing dependencies which should be modified to be as indicated:
    api("io.opentelemetry:opentelemetry-extension-annotations:1.11.0") (was implementation)
```

```
./gradlew :core:contract:reason --id io.opentelemetry:opentelemetry-extension-annotations  
FAILURE: Build failed with an exception.
* What went wrong:
Task 'reason' not found in project ':core:contract'.
```

I'm trying to understand why the dependency is still considered implementation after excluding the relevant annotation from ABI scan.

**Comment by autonomousapps** [comment]
The `reason` task was removed with rc02. I am currently working on re-implementing it.

> I'm trying to understand why the dependency is still considered implementation after excluding the relevant annotation from ABI scan.

You could take a look at abi-dump.txt and search for class references that come from that dependency.

**Comment by algattik** [comment]
Thank you for the hint. 

And most of all, for the amazing work, this is really a fantastic tool!

**Comment by autonomousapps** [comment]
For anyone else who uses that task, I have decided to re-add it for the v1.0 release, primarily because I want to validate that the new architecture does in fact make it "easier" to add new features.

**Comment by autonomousapps** [comment]
Just merged the PR re-adding this.
