### ISSUE TITLE
Documentation for Kotlin DSL

### ISSUE THREAD

**Issue by algattik** [autonomousapps/dependency-analysis-android-gradle-plugin#609]
**Is your feature request related to a problem? Please describe.**
It was some work to find out how to configure the plugin in build.gradle.kts

**Describe the solution you'd like**
Would have been useful to have such a snippet in the installation docs
```
plugins {
    id("com.autonomousapps.dependency-analysis") version "1.0.0-rc03"
}
configure<com.autonomousapps.DependencyAnalysisExtension> {
        issues {
...
}
```

**Comment by autonomousapps** [comment]
Addressed with new section in readme: https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/blob/main/README.asciidoc#basic-configuration
