### ISSUE TITLE
excludeAnnotations doesn't seem to work

### ISSUE THREAD

**Issue by algattik** [autonomousapps/dependency-analysis-android-gradle-plugin#610]
**Build scan link**

https://github.com/agera-edc/DataSpaceConnector/tree/tmp/algattik-exclude-annotations

Config at https://github.com/agera-edc/DataSpaceConnector/blob/22b572265779d61193ea9c4ebaa585829e91abb3/build.gradle.kts#L287

**Plugin version**
1.0.0-rc03

**Gradle version**
7.3

**Describe the bug**

```
$ env DEPENDENCY_ANALYSIS=fail ./gradlew :core:contract:projectHealth
> Existing dependencies which should be modified to be as indicated:
    api("io.opentelemetry:opentelemetry-extension-annotations:1.11.0") (was implementation)
```

`core/contract/build/reports/dependency-analysis/main/abi-dump.txt` shows only references to `Lio/opentelemetry/extension/annotations/WithSpan;`

This annotation was excluded in the config as follows, this doesn't seem to have any effect. (I'm aware these are regexes, didn't escape dot for simplicity)

```
abi {
            exclusions {
                excludeAnnotations(
                    "io.opentelemetry.extension.annotations.WithSpan",
                )
            }
        }
```

**Expected behavior**
The plugin should consider this should be in `implementation` config

**Comment by autonomousapps** [comment]
Thanks for the issue and the thorough information about it! Will take a look.
