### ISSUE TITLE
Outdated state gets restored from build cache leading to a failure

### ISSUE THREAD

**Issue by gabrielittner** [autonomousapps/dependency-analysis-android-gradle-plugin#612]
**Build scan link**

Will send one through Slack.

**Plugin version**

1.0.0-rc03

**Gradle version**

7.4.1

**(Optional) Android Gradle Plugin (AGP) version**

7.1.2

**Describe the bug**

I'm getting this error:
```
* What went wrong:
Execution failed for task ':core:coroutines:api:computeActualUsageMain'.
> A failure occurred while executing com.autonomousapps.tasks.ComputeUsagesTask$ComputeUsagesAction
   > Could not create an instance of type com.autonomousapps.tasks.ComputeUsagesTask$ComputeUsagesAction.
      > No file for com.freeletics.mad:state-machine-jvm:0.3.0-alpha27
```

That the file does not exist is expected because the pr that has this failure bumps the version to `0.3.0-alpha28`. All previous dependency analysis tasks are restored from cache so I think one of them might not specify all inputs and it shouldn't actually be restored from cache.
```
> Task :core:coroutines:api:findDeclarations FROM-CACHE
> Task :core:coroutines:api:graphViewMain FROM-CACHE
> Task :core:coroutines:api:artifactsReportMain FROM-CACHE
> Task :core:coroutines:api:explodeJarMain FROM-CACHE
> Task :core:coroutines:api:findDeclaredProcsMain FROM-CACHE
> Task :core:coroutines:api:findInlineMembersMain FROM-CACHE
> Task :core:coroutines:api:serviceLoaderMain FROM-CACHE
> Task :core:coroutines:api:synthesizeDependenciesMain FROM-CACHE
> Task :core:coroutines:api:abiAnalysisMain FROM-CACHE
> Task :core:coroutines:api:explodeByteCodeSourceMain FROM-CACHE
> Task :core:coroutines:api:explodeCodeSourceMain FROM-CACHE
> Task :core:coroutines:api:synthesizeProjectViewMain FROM-CACHE
> Task :core:coroutines:api:graphViewTest FROM-CACHE
> Task :core:coroutines:api:computeActualUsageMain FAILED
> Task :core:coroutines:api:artifactsReportTest FROM-CACHE
> Task :core:coroutines:api:explodeJarTest FROM-CACHE
> Task :core:coroutines:api:findDeclaredProcsTest FROM-CACHE
> Task :core:coroutines:api:findInlineMembersTest FROM-CACHE
> Task :core:coroutines:api:serviceLoaderTest FROM-CACHE
> Task :core:coroutines:api:synthesizeDependenciesTest FROM-CACHE
> Task :core:coroutines:api:compileTestKotlin FROM-CACHE
> Task :core:coroutines:api:compileTestJava NO-SOURCE
> Task :core:coroutines:api:explodeByteCodeSourceTest FROM-CACHE
> Task :core:coroutines:api:explodeCodeSourceTest FROM-CACHE
> Task :core:coroutines:api:synthesizeProjectViewTest FROM-CACHE
> Task :core:coroutines:api:computeActualUsageTest FAILED
```

**To Reproduce**

If the scans are not enough I can try creating a reproducer.

**Expected behavior**

Build does not fail.

**Comment by gabrielittner** [comment]
Forgot to mention that `--rerun-tasks` fixes it which points to the build cache

**Comment by autonomousapps** [comment]
Thanks for the report. This definitely sounds like an issue with the build cache. From a quick glance at the relevant code, it's not immediately clear what's causing this issue. The proximal cause is that, if your dependencies have changed, then `synthesizeProjectViewTest` should not have come from the cache. Its output as a serialized `ProjectVariant`, which includes a `classpath: Set<Coordinates>` property, and it's from that classpath that `ComputeUsagesTask` gets the no-longer-there dependency.

After getting the task to fail, could you do
```
ls core/coroutines/api/build/reports/dependency-analysis/test/dependencies/
```
and send the results? I would expect it to contain `com.freeletics.mad__state-machine-jvm__0.3.0-alpha28`, but I'd like to double-check

**Comment by gabrielittner** [comment]
Yes the file for the correct version is there

**Comment by autonomousapps** [comment]
Can you provide the file `core/coroutines/api/build/reports/dependency-analysis/main/graph/graph-compile.json`? I have a suspicion it will include coordinates for the _old_ dependency. This file is the ultimate source of the `classpath` property that provides the bad coordinates that leads to the `No file for com.freeletics.mad:state-machine-jvm:0.3.0-alpha27` error.

If I'm right, this is the issue:
```
// GraphViewTask
@Classpath
fun getCompileClasspath(): FileCollection = compileClasspath
  .artifactsFor(jarAttr.get())
  .artifactFiles
```
Probably alpha27 and alpha28 have an identical ABI and so are the same for `@Classpath` purposes. The normalization should be `@PathSensitive(PathSensitivity.NAME_ONLY) @InputFiles` instead.

**Comment by gabrielittner** [comment]
I can confirm that `graph-compile.json` includes the coordinates of the old dependency. Also that updating a dependency without any ABI changes reproduces the issue

**Comment by autonomousapps** [comment]
Great, then I should have a fix for this soon.
