### ISSUE TITLE
Print consoleReportPath path as file URI

### ISSUE THREAD

**Issue by G00fY2** [autonomousapps/dependency-analysis-android-gradle-plugin#627]
Hi and thanks for this great plugin!

I suggest printing the report path as file URI to make it clickable in most terminals.

This makes it much easier for consumers to navigate to the report.

So instead of
https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/blob/31c31026fd5cacfeed4a4a4309cef3bdcd64ff8f/src/main/kotlin/com/autonomousapps/tasks/BuildHealthTask.kt#L43

you could write
```kotlin
  append("There were dependency violations. See report at file://${consoleReportPath}")
```

**Comment by autonomousapps** [comment]
Sounds good! Do you want to PR that?

**Comment by autonomousapps** [comment]
I think the PR linked should also resolve this. Closing this optimistically.
