### ISSUE TITLE
Migration from comprehensiveAdvice() to projectAdvice()

### ISSUE THREAD

**Issue by GianfrancoMS** [autonomousapps/dependency-analysis-android-gradle-plugin#645]
Hi, we're trying to update from 0.80.0 to 1.1.0 and we realized that `comprehensiveAdvice` was removed from `AbstractPostProcessingTask`

Is there any guide or documentation to migrate from `comprehensiveAdvice` to `projectAdvice`?

**Comment by autonomousapps** [comment]
Here's the model for ProjectAdvice: https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/blob/main/src/main/kotlin/com/autonomousapps/model/ProjectAdvice.kt

It's basically the same. What exactly is the issue you see?

**Comment by GianfrancoMS** [comment]
We used something like this in version 0.80.0:

`
import com.autonomousapps.advice.Advice

private fun AbstractPostProcessingTask.applyDependencyAdvices(
    project: Project,
    extension: DependencyAdviceApplierPluginExtension
) {
    val comprehensiveAdvice = comprehensiveAdvice()
    // apply advice
}
`

In the version 1.1.0:
`
import com.autonomousapps.model.Advice

private fun AbstractPostProcessingTask.applyDependencyAdvices(
    project: Project,
    extension: DependencyAdviceApplierPluginExtension
) {
    // comprehensiveAdvice() was removed
    // pprojectAdvice returns  com.autonomousapps.model.Advice and not longer com.autonomousapps.advice.Advice
    val comprehensiveAdvice = projectAdvice()
    // apply advice
}
`

**Comment by GianfrancoMS** [comment]
I guess these two are very similar https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/blob/main/src/main/kotlin/com/autonomousapps/model/Advice.kt and https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/blob/main/src/main/kotlin/com/autonomousapps/advice/Advice.kt. But we use the latter for post processing, but projectAdvice() does not use it.

**Comment by autonomousapps** [comment]
Yes, the latter still exists because it made it easier to migrate my tests without rewriting them. You should migrate to the former, which is the new model. I think they're basically identical, but just in different packages?

**Comment by autonomousapps** [comment]
Btw, if you want an intermediate step between 0.80 and 1.1, take a look at this note in the readme: https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin#two-models
