### ISSUE TITLE
Sync to a single version

### ISSUE THREAD

**Issue by yschimke** [autonomousapps/dependency-analysis-android-gradle-plugin#650]
I'm frustrated by conflicting versions of dependencies in a single project.

![image](https://user-images.githubusercontent.com/231923/164934819-dcf47b14-cc11-47e3-8923-d9b6385ed093.png)

Even with version catalogs, if a dependency in debug or test brings in an older version, you have multiple versions in play.  for a single module app this should be solvable.

Either

a) manual steps to resolve this, as part of buildHealth.  Maybe pinning versions.
or
b) the buildHealth plugin actually enforces the right versions.

**Comment by autonomousapps** [comment]
I would suggest creating a single [platform ](https://docs.gradle.org/current/userguide/java_platform_plugin.html) and using it everywhere.

It would maybe be interesting to surface a report in `buildHealth` indicating the number of dependencies with varying versions across a build.
