### ISSUE TITLE
Customizing-plugin-behavior wiki page is out of date

### ISSUE THREAD

**Issue by 3flex** [autonomousapps/dependency-analysis-android-gradle-plugin#653]
https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/wiki/Customizing-plugin-behavior#strict-and-non-strict-modes

This section describes strict & non-strict modes, however it doesn't say that `strictMode` was removed in [v1.0.0-rc02](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/releases/tag/v1.0.0-rc02) by https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/commit/183b175ddbfe63dfec18da247ef4cf09bce285f5.

As a new user this was a bit confusing - especially as I would have liked a non-strict mode to avoid listing transitive dependencies in the list of actions (if there's some type of exclusion rule that now achieves this it would be great to document that).

Looking at some other config examples, they look like they need updating as well.

Thanks for the plugin!

**Comment by autonomousapps** [comment]
Thanks for filing this issue. I've been meaning to update the wiki.

If you want to exclude all transitive dependencies from your report, you can [do so](onUsedTransitiveDependencies) (but I don't really recommend it).
```groovy
dependencyAnalysis {
  issues {
    all {
      onUsedTransitiveDependencies {
        severity 'ignore'
      }
    }
  }
}
```

**Comment by autonomousapps** [comment]
Wiki updated. Thanks again.
