### ISSUE TITLE
Plugin should not recommend using `api` configuration when `application` plugin is used in project

### ISSUE THREAD

**Issue by 3flex** [autonomousapps/dependency-analysis-android-gradle-plugin#654]
**Is your feature request related to a problem? Please describe.**
When buildHealth or projectHealth tasks are run on a project that applies Gradle's `application` plugin it reports that certain dependencies should be applied to `api` configuration (instead of `implementation`). This makes sense for a library project but not an application.

**Describe the solution you'd like**
In a project where `application` is applied:
1. Do not recommend changing `implementation` to `api`.
2. Recommendation for missing transitive dependencies should be to add to `implementation` configuration, not `api`.

**Describe alternatives you've considered**
I could add manual config to ignore all dependencies in this project, or try and prevent the report from running on the project.

**Additional context**
Example output, using v1.1.0 (I don't think any of these recommendations are valid):
```
> Task :detekt-cli:projectHealth
Transitively used dependencies that should be declared directly as indicated:
  api("org.jetbrains.kotlin:kotlin-compiler-embeddable:1.6.21")
  api(project(":detekt-api"))

Existing dependencies which should be modified to be as indicated:
  api("com.beust:jcommander:1.82") (was implementation)
  api(project(":detekt-tooling")) (was implementation)
```

**Comment by autonomousapps** [comment]
Can you tell me more about your project? Do you have a build scan? The plugin already takes the `application` plugin into account.

**Comment by 3flex** [comment]
Build file here: https://github.com/3flex/detekt/blob/c4d3456db2ace9fead3482b94dc857d8b0f0d9c8/detekt-cli/build.gradle.kts

Do you want a build scan running the `buildHealth` or `projectHealth` task or a build of the project itself?

**Comment by autonomousapps** [comment]
Either `buildHealth` or `<your module>:projectHealth` would be fine.

**Comment by 3flex** [comment]
Thank you for investigating - I'll close this while I take a closer look and try to untangle things and will only reopen if it still seems like there's some issue.
