### ISSUE TITLE
Android assets are not accounted for

### ISSUE THREAD

**Issue by ZacSweers** [autonomousapps/dependency-analysis-android-gradle-plugin#657]
**Build scan link**

**Plugin version**

1.1.0

**Gradle version**

7.4.2

**(Optional) Android Gradle Plugin (AGP) version**

7.1.3

**Describe the bug**

Android assets are not currently accounted for, so a project that contains assets only is determined to be `compileOnly`-safe to depend on.

**To Reproduce**
1. Have an assets-only project with one kotlin file for compilation marker reasons (so IC data is generated)
2. Depend on it in your top-level app project
3. Run analysis in the app project and observe it suggests making it compile-only (interestingly not a removable dependency though?)

<img width="335" alt="image" src="https://user-images.githubusercontent.com/1361086/167045958-0d7588ba-c272-40d5-86e8-edc7e8411ef9.png">
![image](https://user-images.githubusercontent.com/1361086/167045970-aa622b71-6870-4a64-b5b4-caf8769c5173.png)

**Expected behavior**

It should ideally detect usage or at least maybe not touch projects with assets since they're un-trackable

**Additional context**

**Comment by autonomousapps** [comment]
It's been a while, so I have to ask: how do you _use_ an asset from another module? What does the code look like? This gets at the question: **how would I track that an asset is used?** From a packaging perspective, are all assets from all android libraries bundled into the final apk or aar?

**Comment by ZacSweers** [comment]
Here's an example snippet:

```kotlin
context.getAssets().open("some_icon.png")
```

Where `getAssets()` returns `AssetManager`: https://developer.android.com/reference/android/content/res/AssetManager

**Comment by autonomousapps** [comment]
Do you know any examples of published libraries that contain assets? Or is this only relevant for projects in a multi-project situation?
