### ISSUE TITLE
Consider treating KMP dependencies as implicit bundles

### ISSUE THREAD

**Issue by ZacSweers** [autonomousapps/dependency-analysis-android-gradle-plugin#659]
**Is your feature request related to a problem? Please describe.**

Currently, if a JVM project depends on something like `com.github.ajalt.clikt:clikt:3.4.2`, the plugin suggests removing it and replacing it with `com.github.ajalt.clikt:clikt-jvm:3.4.2` (the JVM artifact). It's not usual for projects to depend on this directly though, rather the kotlin plugin reads their gradle module metadata to pick the right dependencies for the given project.

**Describe the solution you'd like**

It would be ideal if the plugin recognized KMP dependencies from the same module metadata and implicitly treated them as bundle dependencies.

**Describe alternatives you've considered**

**Additional context**

**Comment by autonomousapps** [comment]
Just in case it's relevant, is it common for KMP dependencies it use the `-jvm` suffix as in your example?

**Comment by ZacSweers** [comment]
Yup. There would be a similar one for JS. Not sure about others
