### ISSUE TITLE
Task projectHealth is not created

### ISSUE THREAD

**Issue by martinda** [autonomousapps/dependency-analysis-android-gradle-plugin#668]
**Build scan link**
https://scans.gradle.com/s/5egkb67qz3e5a

**Plugin version**
1.2.0

**Gradle version**
7.3.3

**(Optional) Android Gradle Plugin (AGP) version**
This is not for an android project.

**Describe the bug**
No advice is generated, only two tasks are created: `buildHealth` and `generateBuildHealth`.
The task `projectHealth` is not created:

```
FAILURE: Build failed with an exception.

* What went wrong:
Task 'projectHealth' not found in root project 'bitbucket-rest'.
```

**To Reproduce**

```bash
git clone git@github.com:martinda/bitbucket-rest.git --branch fix-api
cd bitbucket-rest
./gradlew buildHealth
./gradlew projectHealth
```

**Expected behavior**
I expect the task `projectHealth` to exist, but I don't understand why it doesn't.

**Comment by autonomousapps** [comment]
There is no `projectHealth` task because the root project (the only project?) [doesn't apply](https://scans.gradle.com/s/5egkb67qz3e5a/plugins) any supported plugin. Is this project a java-app or a java-library? Basically, if you apply one of `java-library` or `application`, then you'll find that `:projectHealth` suddenly exists.

**Comment by martinda** [comment]
I thought the root project did apply a supported plugin ([java](https://scans.gradle.com/s/5egkb67qz3e5a/plugins#java-3)). According to the wiki [Compatibilities - item 4](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/wiki/Compatibilities-&-Limitations), the `java` plugin is supported.

**Comment by autonomousapps** [comment]
> Compatibilities - item 4

Ah, that is ambiguous. It would be more accurate to say `java-library` or `java` + `application`. There is no support for `java` alone. The plugin needs to know if it's dealing with a library or an application so that it can give correct advice.

**Comment by autonomousapps** [comment]
I just updated that page in the wiki.
