### ISSUE TITLE
A couple of issues in the wiki

### ISSUE THREAD

**Issue by boris-petrov** [autonomousapps/dependency-analysis-android-gradle-plugin#684]
In the [Customizing plugin behavior](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/wiki/Customizing-plugin-behavior) page.

1) In the first example there is a missing opening curly-brace after `dependencyAnalysis`.
1) In the second example `issues` is missing in `dependencyAnalysis`.

**Comment by autonomousapps** [comment]
Thank you! I have fixed those two examples.
