### ISSUE TITLE
FR: ABI exclusion configuration

### ISSUE THREAD

**Issue by ZacSweers** [autonomousapps/dependency-analysis-android-gradle-plugin#69]
There are certain types of annotations or package name structures that are conventionally used as "public-but-private" cases

- `@Generated`-annotated code is usually implementation detail for the code it originates from and is usually exposed (if at all) via something else.
- `@RestrictedApi` (error prone) or `@RestrictTo` (androidx) annotations
- package names with `.internal` in them
- public kotlin code annotated with `@PublishedApi`, as they're only public for use with inline functions

All of these cases could be candidates to be treated as `internal` visibility to a module and not part of ABI consideration.

A proposal API for configuring this:

```gradle
issues {
  abi {
    ignoreGeneratedCode() // Implicitly ignores `@Generated`
    ignoreAnnotations("androidx.annotation.RestrictTo", ...)
    ignorePattern("**.internal.**")
  }
}
```

**Comment by autonomousapps** [comment]
This request bears some similarities to [this earlier FR](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/3).

**Comment by autonomousapps** [comment]
Consider also `@VisibleForTesting`.

**Comment by autonomousapps** [comment]
Resolved by https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/pull/158.
