### ISSUE TITLE
FR: Declare some artifacts as conventionally compileOnly

### ISSUE THREAD

**Issue by ZacSweers** [autonomousapps/dependency-analysis-android-gradle-plugin#70]
Some artifacts, like annotations, are often marked as only compileOnly because they're only needed during annotation processing. It would be great if these could be configured somewhere to avoid this:

![image](https://user-images.githubusercontent.com/1361086/75927539-8d4d7800-5e3a-11ea-8100-397f206820ae.png)

**Comment by autonomousapps** [comment]
In the particular case of auto-value-annotations, I took a look at the [source](https://github.com/google/auto/tree/master/value/src/main/java/com/google/auto/value), as well as the published [jar](https://mvnrepository.com/artifact/com.google.auto.value/auto-value-annotations/1.7), and see that all of the classes are annotations with either CLASS or SOURCE retention policies. So I think I might be able to automatically detect a case like this and not erroneously suggest that a `compileOnly` dep be available at runtime. In fact, I can also imagine detecting that such a dep is available at runtime but doesn't need to be (can be `compileOnly`).

Can you think of any dependencies that are only required at compile-time but which _don't_ only contain CLASS/SOURCE annotations?

**Comment by ZacSweers** [comment]
There are some annotations that use enums for their members that wouldn't
work with that assumption :/.

**Comment by autonomousapps** [comment]
I wrote up some thoughts on what a "for-compilation-only jar" algorithm might look like. Feedback?

Jar must _only_ contain:
1. Annotation classes with `CLASS` or `SOURCE` retention policies (or no policy => `CLASS` is default).
2. 1, plus types that only exist to provide a sort of "namespace". For example, `@org.jetbrains.annotations.ApiStatus` has no members. It only has inner classes which are themselves annotations that comply with 1.
3. 1 and 2, plus types that are only used by the annotations in the jar that comply with 1. For example, the `@org.intellij.lang.annotations.PrintFormat` annotation uses a class (in this case defined in the same file), `org.intellij.lang.annotations.PrintFormatPattern`. The assumption here is that such classes (PrintFormatPattern) are only required during compilation, for their associated compile-only annotations.

**Comment by autonomousapps** [comment]
Going to close this for now, based on compileOnly support provided with https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/blob/master/CHANGELOG.md#version-0230
