### ISSUE TITLE
Java Projects not Analyzed Without Also Adding the Kotlin JVM Plugin

### ISSUE THREAD

**Issue by philliplbryant** [autonomousapps/dependency-analysis-android-gradle-plugin#765]
Dependency analysis is not performed for the attached Java only project but it is performed when (unnecessarily) applying the Kotlin plugin to this project.  I have attached a basic Java project that reproduces the problem.  Please see java-project/build.gradle.kts, noting analysis is not performed when only applying the java-project plugin and analysis is performed when commenting out the java-project plugin and uncommenting and only applying the java-and-kotlin-project plugin.

[dependency-analysis-plugin-example.zip](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/files/9337755/dependency-analysis-plugin-example.zip)

**Comment by autonomousapps** [comment]
Next time you file an issue, please use the issue template. I have it for a reason.

Your "java-project" plugin is simply a wrapper around the "java" plugin. That plugin does not provide enough information to DAGP for it to know how to analyze your project. It is not really meant to be applied directly to projects. You should apply either `java-library` or `application` (optionally plus a language ecosystem plugin).

Closing this issue.
