### ISSUE TITLE
Add config option to disable the AGP version check, or otherwise optimize it

### ISSUE THREAD

**Issue by ianbrandt** [autonomousapps/dependency-analysis-android-gradle-plugin#769]
**Build scan link**
https://scans.gradle.com/s/4ijdkgu4qmay4

**Plugin version**
1.12.0

**Gradle version**
7.5.1

**(Optional) Android Gradle Plugin (AGP) version**
N/A

**`reason` output for bugs relating to incorrect advice**
N/A

**Describe the bug**
I was profiling a multi-project Gradle build with hundreds of subprojects. This is for a client-server JVM project, so the Android Gradle Plugin isn't applied to any projects. The JDK Mission Control analysis of the Java Flight Recorder capture I made with the Gradle Profiler highlighted that this plugin is using [exceptions for flow control to test for the AGP version](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/blob/d239bb34a3f213e9168888195f0e92cdf3306e0a/src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt#L27).

It does this once for the root project, and then again for every subproject the plugin is applied to. For a project with hundreds of subprojects that adds up.

It would seem more efficient if a configuration option were to be added to tell the plugin not to bother checking the AGP version. That'd presumably be a simple boolean check per project instead of a throw-catch for every one. If there was an approach to testing the AGP version that didn't require using exceptions for flow control that could also work.

**Additional context**
Although on a much smaller scale, I reproduced the issue with this project: https://github.com/sdkotlin/sd-kotlin-talks/tree/362c4d3c319b66422f229582c24273a2ebae2318.
 
<img width="1534" alt="2022-08-14 - Dependency Analysis Plugin - JMC Exception Analysis" src="https://user-images.githubusercontent.com/709570/185013697-81c633bd-e39a-4e21-bd91-936fec92bd64.png">

**Comment by autonomousapps** [comment]
Thank you for the issue. I agree that it seems like a good idea to optimize this in some way.

**Comment by ianbrandt** [comment]
Thanks for the work on this. Is it possible to have an Android project be a subproject in a larger Gradle project? For example, a mono-repo like setup where you have server-side and Android app distributions all under a single umbrella root project. If so, I'm wondering whether the merged commit would work for that, as perhaps the Android plugin would only be applied to the subproject.

Also, I'm not at the point of optimizing my project to this level (yet), but it still might be nice to consider a configuration option that would eliminate even the single exception for flow control on the root project.

Just some thoughts for the sake of feedback. This change as is will help my project significantly.

**Comment by ianbrandt** [comment]
Just FYI, it looks like this made it into 1.14.0, but the Milestone value on this issue still says "next".

Thanks for the fix and release.

**Comment by autonomousapps** [comment]
> Just FYI, it looks like this made it into 1.14.0, but the Milestone value on this issue still says "next".

I play real fast and loose with milestones here 😅 They really just help me prioritize work, they have no relation to released versions.
