### ISSUE TITLE
Advice should include more explanations about dependency changes.

### ISSUE THREAD

**Issue by stephanenicolas** [autonomousapps/dependency-analysis-android-gradle-plugin#77]
In 0.24.0 and below, the plugin is working well, but there is a gap between developers workflow and the plugin advises: 

* devs are working in one module, they will do changes one module at a time.
* the plugin has a more holistic view of the changes.

This difference makes it so that changes in a single module are breaking because they suppose that other changes are applied in other modules. Devs cannot fix a module in isolation, test to see if this module compiles and move on. Applying the advises will create situations where compilation or annotation processing fails and the errors and stack traces they provide are very hard to make sense of.

Here is an example:
```
A impl -> C impl
A impl -> B impl -> C.
```

The plugin can say that `C` is not used by `A` and should be removed, it takes into account that `B` should be modified to : `B api -> C`.
But devs, just by looking at the advises for `A` will have no understanding of the changes required in `B` before they proceed to cleaning `A`. 

If they apply the advises to `A` only and try to compile it, they can have dramatic errors that are completely unclear, and the issues are very hard to solve with the provided information. 

Very often the problems they will face will be inside the class loading mechanisms of `kapt/apt/javac/kotlinc` and these tools don't provide fine grained info in these cases.

Ideally the plugin should be able to explain something like
```
dependency to C should be removed in A as it should be provided by B which requires B should have a dependency on C in the api configuration.
```

A workaround would be to explain devs that they should clean up modules in the topological order of modules which is not an easy notion to get, it would require assistance to do so as well.

**Comment by autonomousapps** [comment]
@stephanenicolas I have made an improvement related to this a few weeks ago. The `Advice` model now includes used-transitive dependencies and parent dependencies (that supply _this_ dependency transitively). Careful inspection of the advice json will tell an end-user whether a particular advice is "safe" to follow in isolation. I'm going to close this issue for now, but feel free to re-open if you think more should be done here.
