### ISSUE TITLE
`graphViewDebug` fails with exception `graph.ElementOrder`

### ISSUE THREAD

**Issue by fmatosqg** [autonomousapps/dependency-analysis-android-gradle-plugin#796]
Many tasks fail with `graphViewDebug` which generates exception com.google.common.graph.ElementOrder com.google.common.graph.ElementOrder.stable()

Unfortunately it's a private project which I can't share.

**Plugin version**
1.13.1, but also can be reproduced with 1.0.0-rc01 even when `dependency.analysis.old.model=true`.

Does not happen on 0.80.0.

**Gradle version**
7.5.1, but also 7.3 and 7.0.0

**(Optional) Android Gradle Plugin (AGP) version**
7.3.1

though I suspect this is not related to Android since I can reproduce the error in a pure java library.
 
**Describe the bug**
```
> ./gradlew analytics:projectHeal
Configuration on demand is an incubating feature.
Disabling remote cache because it is set to false

. . .

> Task :analytics:graphViewMain FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':analytics:graphViewMain'.
> 'com.google.common.graph.ElementOrder com.google.common.graph.ElementOrder.stable()'

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 684ms
43 actionable tasks: 1 executed, 42 up-to-date

```

**To Reproduce**
`./gradlew buildHealth` or `./gradlew base:projectHealth` or `./gradlew base:reason --id foobar`

Where `base` is an android library.

or `./gradlew analytics:projectHeal --no-daemon`

where `analytics` is a jvm library

**Comment by autonomousapps** [comment]
@fmatosqg can you provide a stacktrace? A reproducer would also be very helpful.

**Comment by fmatosqg** [comment]
found the problem!

while looking at the stack trace, realized that this is crashing on a Guava class. And android builds tend to have problems with guava, so I looked further, and found out that the method `stable` was introduced in a newer version of guava than we're using. 

Upgrading it to 31.0 made the crash go away.

**Comment by autonomousapps** [comment]
Thanks for letting me know! Guava's a real pain (because it's so popular). I have considered shading it for this reason, but it's so huge and I don't want to bloat the plugin binary.
