### ISSUE TITLE
`compileKotlin` is reexecuted after update or add the plugin

### ISSUE THREAD

**Issue by BraisGabin** [autonomousapps/dependency-analysis-android-gradle-plugin#809]
**Plugin version**
1.14.1

**Gradle version**
7.5.1

**(Optional) Android Gradle Plugin (AGP) version**
7.2.1

**Describe the bug**
When I update this plugin the tasks `compileKotlin` or `kaptKotlin` are executed for all my modules. Same happens when I add this plugin to a project that doesn't have it. I'm not sure if this is the expected behaviour but it would be great if that could be avoided.

**To Reproduce**
1. `./gradlew buildHealth`
2. Update (or downgrade) the plugin.
3. `./gradlew buildHealth`. Check that a lot of tasks are re-executed

**Expected behavior**
I would expect that the plugin would be able to use the outputs of the previous runs. I assume that the plugin tasks should be re-executed but not `compileKotlin`and similar tasks.

**Context**
I'm using this plugin to fix lots of issues on our dependencies. But I have this plugin on my branch. Each time that I fix some issues I create a branch with only those fixes and commit it to `main`. Each time that I sync my branch with `main` I get a lot of misses from our remote cache.

**Comment by autonomousapps** [comment]
It is probably due to how you've added the plugin to your build. If you change the buildscript classpath, then Gradle might think a lot of tasks have changed inputs, since the buildscript classpath is an input to tasks in many cases. In other words, I have high confidence the plugin is not at fault.

Tangential, but why not commit the plugin itself to your main branch?

**Comment by BraisGabin** [comment]
I could reproduce this with a sample project (It's just what AS creates): https://github.com/BraisGabin/daagp-example

What I did to reproduce it:
- Run `./gradlew build` before adding the plugin (https://github.com/BraisGabin/daagp-example/commit/3634060f533e5290108e8e1d4f9f9903fb84f53b)
  - Scan: https://scans.gradle.com/s/hf2xnqnx526qa/timeline?details=2chf6gzwe2r6w
- Run `./gradlew buildHealth` after adding the plugin version `1.13.1`(https://github.com/BraisGabin/daagp-example/commit/cce0d97ed0d162e33ee8f9b2ad06f2dd40319603)
  - Scan: https://scans.gradle.com/s/zy3dewotlwqiu/timeline?details=2chf6gzwe2r6w
- Run `./gradlew buildHelath` after updating the plugin to `1.14.1` (https://github.com/BraisGabin/daagp-example/commit/47abd710c856cb1ff8000eff02aaeab53162f544)
  - Scan: https://scans.gradle.com/s/endtpiv5kzwes/timeline?details=2chf6gzwe2r6w

You can check that the task `:app:compileReleaseKotlin` is executed *every* time. I was shocked that there was not a single task `UP-TO-DATE` between each other.

---

I just checked and it seems that adding a plugin to the `root` of your project invalidates *ALL* the project. Because I added the [gradle versions plugin](https://github.com/ben-manes/gradle-versions-plugin) and I got the same behaviour: https://scans.gradle.com/s/c2q77ldrbhxra/timeline?details=2chf6gzwe2r6w

🤷‍♂️ I don't fully understand why this behaviour but I'm going to assume they are "gradle things". Because I think that I'm not adding the plugins in any "fancy" way.

Closing as this is clearly not related with this plugin.

**Comment by autonomousapps** [comment]
Adding a plugin to the root project changes the classpath of all projects, because of gradle's classloader hierarchy. I talk about that a bit [here](https://dev.to/autonomousapps/abusing-gradle-s-class-loader-hierarchy-for-fun-and-profit-oca).
