### ISSUE TITLE
Eager task creation by JavaSources/KotlinSources

### ISSUE THREAD

**Issue by daanschipper** [autonomousapps/dependency-analysis-android-gradle-plugin#815]
**Build scan link**
Can't share private scan :(.

**Plugin version**
`1.13.1`, however nothing changed regarding `main` and `v1.13.1` in `JavaSources` or `KotlinSources`

**Gradle version**
`7.4.2`

**(Optional) Android Gradle Plugin (AGP) version**
Not applicable.

**`reason` output for bugs relating to incorrect advice**
Not applicable. 

**Describe the bug**
`JavaSources` and `KotlinSources` eagerly create tasks during configuration time when a sourceset uses the output of a task as source directory.
```
var fooTask = project.getTasks().register(..);
javaPluginExtension.getSourceSets().create("foo", sourceSet -> {
    sourceSet.java(files -> {
        files.srcDir("src/feature/java");
        files.srcDir(generateFeatureSourcesTask);
    });
});
```

Specifically the usage of `findByName` and `SourceSetContainer.flatMap {}` cause this.

**To Reproduce**
1. Add the above snippet to a project
2. See tasks being eagerly created during configuration in the build scan under Performance -> Configuration -> "Created during configuration"

**Expected behavior**
Tasks not eagerly being created during configuration time.

**Additional context**
A pull request is already in the making to fix this issue

**Comment by autonomousapps** [comment]
Thanks!
