### ISSUE TITLE
Excluded annotations removes annotated class completely form the ABI, not the annotation itself.

### ISSUE THREAD

**Issue by Breus** [autonomousapps/dependency-analysis-android-gradle-plugin#831]
**Build scan link**
Private, can't share unfortunately.

**Plugin version**
v1.17.0

**Gradle version**
7.4.2

We had some issues with excluded annotations:

**What we expected:**
To have only the excluded annotations excluded from the API (hence they can be implementation instead of api).

**What happened instead:**
Whenever a class A had some excluded annotations, the entire class was considered excluded (not just the annotations itself). This caused quite weird behavior and doesn't seem likely to be intended.

**Comment by Breus** [comment]
@autonomousapps I noticed you've added `enhancement` label on this issue. Are you sure this isn't a big? Isn't the intended behaviour to exclude annotations and not the full class that contains the annotation?

**Comment by autonomousapps** [comment]
@Breus can you provide a more complete example? I don't think I really understand what you're saying.

**Comment by Breus** [comment]
@autonomousapps So in [the merge request](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/pull/830/commits/6922f8172e0c360a5262999b53255d9945b61905) I've submitted in `AbiExclusionsProject.groovy:142` the class `SomeAPI` is annotated with `@DaggerGenerated`.

Now I want to exclude this annotation from my ABI with the `excludeAnnotation` feature. However, instead of just that annotation being removed from the ABI of that class, the entire `SomeApi` class is excluded from the ABI. This downgrades the dependency from `api` to `implementation` resulting in compilation errors for modules using classes which are annotated with the specified excluded annotation.

This doesn't actually seem like the intended behaviour of the feature, but instead, I think the idea was to remove the annotation from the ABI because this one only needs to be there compile time whenever actually being read from the class.

For example, JAX-RS or Spring annotations don't need to be there compile-time for classes depending on a class from a different module that have those annotations: only the JAX-RS or Spring framework needs them compile-time.

In my MR I have the fix for this (what seems to be a bug) so instead of removing the entire annotated class, it actually removes the annotation from the ABI.

**Comment by autonomousapps** [comment]
@Breus your analysis is incorrect. It is in fact the intention that `excludeAnnotations()` excludes _annotated classes_ from the ABI. This discussion does suggest that the name of the method is sub-optimal. Maybe it should be `excludedClassesWithAnnotations()` instead.

Regarding your desire to actually exclude some annotations, I suppose that could be considered a missing feature. As a workaround, you could annotate your annotations, and then use this existing feature 🙃 I also wonder if you could use `excludeClasses()` and list your annotations there.

**Comment by autonomousapps** [comment]
Is it possible to use `excludeClasses()`?

> Would this be a feature that would be included if I wrote an implementation for it?

To ensure I understand the implications of this, I will restate in my own words. You want to list some annotations (external in this case, but I presume they could also be internal), and have those annotations be _not_ considered as part of your project's ABI? And therefore this plugin would not suggest dependencies containing those annotations be `api`? Is that roughly it?

**Comment by Breus** [comment]
> You want to list some annotations (external in this case, but I presume they could also be internal), and have those annotations be not considered as part of your project's ABI? And therefore this plugin would not suggest dependencies containing those annotations be api? Is that roughly it?

Yes, that's exactly right @autonomousapps!  

The code that needs to be aware of those dependencies (of the annotations) during compile time generally already knows about the annotations so no need to add compile time dependencies everywhere where they probably won't be used anyways.

**Comment by autonomousapps** [comment]
Can you use `excludeClasses()` to exclude those annotation classes?
