### ISSUE TITLE
fixDependencies gives up on files containing platform() declarations

### ISSUE THREAD

**Issue by pikzen** [autonomousapps/dependency-analysis-android-gradle-plugin#832]
**Build scan link**
No build scan unfortunately, based on a private project.

**Plugin version**
1.17.0

**Gradle version**
7.5.1

**(Optional) Android Gradle Plugin (AGP) version**
7.3.1

**`reason` output for bugs relating to incorrect advice**
> Task :externallibraries:performance:google:fixDependencies
line 14:27 extraneous input '(' expecting {'}', ID}
Can't fix dependencies for ':externallibraries:performance:google': 1: extraneous input '(' expecting {'}', ID}

**Describe the bug**
Dependencies fixes choke when encountering a platform() dependency declaration. Our build.gradle.kts contains the following line: `implementation(platform(libs.firebase.bom))`, which clearly isn't liked. It doesn't cause a crash and is a simple warning.

**To Reproduce**
Use a `platform()` declaration in your build file.

**Expected behavior**
Either detect usage of libraries contained within a BOM properly (although it feels weird. A BOM is here because you explicitly want a set of versions that you know works together.), or simply ignoring such lines and continuing on happily with trying to fix the dependencies (which would probably need to detect which libraries are coming from the BOM, not fix them, etc ?)

**Comment by autonomousapps** [comment]
Thanks for the issue. I think I have a fix for this in another project and need to port it over.

**Comment by sanggggg** [comment]
Are there any updates on this issue? I'm having a similar problem too

**Comment by jloskin** [comment]
implementation project(path: ':some_project')

also "path:"

**Comment by jloskin** [comment]
Escape character in gradle files
as example
buildConfigField "String", "someField", "\"someValue\""
