### ISSUE TITLE
Incorrect advice when using a dependency with a capability

### ISSUE THREAD

**Issue by daanschipper** [autonomousapps/dependency-analysis-android-gradle-plugin#836]
**Build scan link**
Private :/

**Plugin version**
`1.17.1-SNAPSHOT`

**Gradle version**
`7.4.2`

**(Optional) Android Gradle Plugin (AGP) version**
Not applicable.

**`reason` output for bugs relating to incorrect advice**

```
dependencies {
    implementation(project(":bar")) {
        capabilities {
            requireCapability("com.foo:bar-<capability>")
        }
    }
}
```

```
> Transitively used dependencies that should be declared directly as indicated:
    implementation project(':bar')
```

**Describe the bug**
When computing the advice in `StandardTransform#computeAdvice` the `usages` are compared to the `declarations` and based on what is incorrect some advice is given. However the set of `declarations` have filtering applied to `special dependencies like test fixtures or platforms`, but this filtering does not happen for the `usages`. This result in incorrect advice where a dependency on a 'special dependency' is used and declared, the declaration is filtered out when computing the advice and then the plugin advises to declare the dependency. Unfortunately the advice prints the advice also incorrectly as the capability of the dependency is not taken into account.

**To Reproduce**
https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/commit/35ebb6bb20d1aab8e8bbae6eacec9ea4f57e5b0d

**Expected behavior**
Either
* Ignore the usage of the 'special' dependency with a capability
* Include the capability in the dependency
```
> Transitively used dependencies that should be declared directly as indicated:
    implementation(project(':bar')) { capabilities { requireCapability("com.foo:bar-<capability>") }
```

**Additional context**
This relates to #298, but it's slightly different as 'special' dependencies are not supported and should be filtered out.

I've managed to trace this back to `com.autonomousapps.internal.utils.GradleStringsKt#toCoordinates(org.gradle.api.artifacts.result.ResolvedDependencyResult)` where the `ResolvedDependencyResult` is converted to the internal model `Coordinates`. The `ResolvedDependencyResult` might also have `requested.requestedCapabilities`, but this information is not saved to `Coordinates`. Something like the following could be added to determine whether a capability needs to be saved to the `Coordinates`. 
```
val requestedCapability = requested.requestedCapabilities.firstOrNull()
  val selectedCapability = selected.variants.firstOrNull()?.capabilities?.firstOrNull()
  if (requestedCapability == selectedCapability) {
    capability = selectedCapability?.name
  }
```

**Comment by autonomousapps** [comment]
Thanks for filing this issue.
