### ISSUE TITLE
private_to_this not considered in ABI analysis

### ISSUE THREAD

**Issue by ZacSweers** [autonomousapps/dependency-analysis-android-gradle-plugin#84]
**Plugin version**
0.26.1

**Gradle version**
6.3

**Android Gradle Plugin (AGP) version**
Irrelevant

**Describe the bug**
Kotlin visibility has a notion of "private to this", which is present in metadata. I don't think this is currently accounted for.

**To Reproduce**

```kotlin
private class Foo

class Bar {
  private val foo = Foo()
}
```

**Expected behavior**

**Additional context**

Example of reading the flag from metadata: https://github.com/square/kotlinpoet/blob/master/kotlinpoet-metadata/src/main/kotlin/com/squareup/kotlinpoet/metadata/Flags.kt#L46

**Comment by autonomousapps** [comment]
Are you sure? I just created a project with the only source file like this:
```kotlin
class Library {
    fun someLibraryMethod(): Boolean {
        val p = PrivateToThis()
        return true
    }
}

private class PrivateToThis
```
(most of this was auto-generated by `gradle init`)

I then ran `./gradlew abiAnalysisMain`, which produced a file `build/reports/dependency-analysis/main/abi-dump.txt`, whose contents is
```
public final class abi/example/Library {
        public fun <init> ()V
        public final fun someLibraryMethod ()Z
}
```
(as expected)

The companion `build/reports/dependency-analysis/main/abi.json` file is empty.

nb, I'm not even allowed to compile something like this:
```kotlin
class Library {
    fun someLibraryMethod(): PrivateToThis {
        return PrivateToThis()
    }
}

private class PrivateToThis
```

**Comment by ZacSweers** [comment]
That case might not hit it exactly then. Maybe a private top level function?

**Comment by autonomousapps** [comment]
@ZacSweers are you seeing such PrivateToThis members showing up in an ABI report?

**Comment by ZacSweers** [comment]
Haven't seen any yet. Can close this out for now I think and just deal with it if it comes up
