### ISSUE TITLE
Running `fixDependencies` doesn't run tasks from nested projects

### ISSUE THREAD

**Issue by eygraber** [autonomousapps/dependency-analysis-android-gradle-plugin#843]
**Build scan link**
Private project

**Plugin version**
1.18.0

**Gradle version**
7.6

**(Optional) Android Gradle Plugin (AGP) version**
8.0.0-alpha10

**Describe the bug**
Running `gradle fixDependencies` only runs tasks from top level projects. If I have a project nested under another directory, its `fixDependencies` is not executed.

**Expected behavior**
If I run `gradle fixDependencies` then the task is executed for all subprojects.

**Additional context**
The `fixDependencies` task exists on the nested project, and I can run it targeting them directly, e.g, `gradle :foo:bar:fixDependencies`

**Comment by autonomousapps** [comment]
Thanks for the issue. Could you provide a minimal reproducer? I can't see no reason why the task wouldn't run from "nested projects." I'm not quite sure what that means. Do you mean an included build?

**Comment by eygraber** [comment]
Must have been an ephemeral issue. It is working fine now.
