### ISSUE TITLE
Support Gradle 8

### ISSUE THREAD

**Issue by fmatosqg** [autonomousapps/dependency-analysis-android-gradle-plugin#851]
Need to collect more data. Overview in screenshot
![image](https://user-images.githubusercontent.com/5360753/215366435-a8d2ba03-5170-41c8-aa00-1f960ba74171.png)

**Comment by ychescale9** [comment]
Here's the text format 😄 We'll investigate further and provide more info.

- `findDeclaredProcsDebug` failure: https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/845
- Task ':analytics:explodeCodeSourceMain' uses this output of task ':analytics:analyticsGenerator' without declaring an explicit or implicit dependency - https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/685
- Execution failed for task ':coredesignsystem:graphViewDebug'. lateinit property compileClasspath has not been initialized

**Comment by autonomousapps** [comment]
Thanks for the report. This will be a fairly high priority once I have some time. Also open to community contributions.
