### ISSUE TITLE
Update `dependencyAnalysis` configuration to allow for sourceset selection for all projects

### ISSUE THREAD

**Issue by TimvdLippe** [autonomousapps/dependency-analysis-android-gradle-plugin#901]
**Is your feature request related to a problem? Please describe.**
We want to roll out the upgrade to the latest version of the dependency analysis plugin to all of our sourcesets. However, the amount of pre-existing issues is substantial enough that a rollout needs to be gradual. Not just on a project/sourceset level, but also on an individual configuration level. The latest version of the plugin does include the `ignoreSourceset` feature, which is what we requested and close to what we needed. However, for a full gradual rollout, we need it to be more flexible to allow configuration of other dependencies.

**Describe the solution you'd like**
Just like we have configuration to apply to all or specific projects (as documented on https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/wiki/Customizing-plugin-behavior#failure-conditions-and-filtering), we would like to see the same on sourcesets. In other words, currently we have a configuration such as:

```groovy
dependencyAnalysis {
  all {
    onAny {
      severity('fail')
    }
    ignoreSourceSet('myCustomSourcset')
    onUnusedDependencies {
      exclude(
        'my.open.source:package',
      )
    }
  }
}
```

We would like to see the project configuration mirrored to sourceset configuration, such that the following is possible:

```groovy
dependencyAnalysis {
  all {
    onAny {
      severity('fail')
    }
    onUnusedDependencies {
      exclude(
        'my.open.source:package',
      )
    }
    // We have not enabled analysis yet for `myCustomSourceset`, so let's ignore all of it
    sourceset('myCustomSourceset') {
      onAny {
        severity('ignore')
      }
    }
    // We successfully enabled analysis for `mySecondSourceset` for all issues, but we are ignoring unused transitive dependencies
    // while we work on resolving the last blockers in some of our projects
    sourceset('mySecondSourceset') {
      onAny {
        severity('fail')
      }
      onUsedTransitiveDependencies {
        severity('ignore')
      }
    }
  }
}
```

**Describe alternatives you've considered**
The configuration can also be done per project in the current form, but this introduces a lot of duplication. As such, it is more difficult to keep track of which sourcesets are cleaned up and which aren't. Additionally, new modules that use the same sourcesets (since it is configured by a plugin) that have not been cleaned up, will now require updating the configuration before they can be added. This adds significant overhead to adding new modules with sourcesets that we don't want to block engineers on.

Example current form configuration that creates friction:

```groovy
dependencyAnalysis {
  all {
    onAny {
      severity('fail')
    }
    onUnusedDependencies {
      exclude(
        'my.open.source:package',
      )
    }
    // We have not enabled analysis yet for `myCustomSourceset`, so let's ignore all of it
    sourceset('myCustomSourceset') {
      onAny {
        severity('ignore')
      }
    }
  }
  // Both lib1 and lib2 apply plugin X that configures the sourceset `mySourcesetConfiguredByPlugin`, but now need
  // separate configuration to ignore each of them.
  project(':my-lib1') {
    onAny {
      severity('fail')
    }
    ignoreSourceset('mySourcesetConfiguredByPlugin')
  }
  project(':my-lib2') {
    onAny {
      severity('fail')
    }
    ignoreSourceset('mySourcesetConfiguredByPlugin')
  }
}
```

**Additional context**
The `ignoreSourceset` feature was introduced in #882 by @jjohannes after the implementation of #854

**Comment by rezastallone** [comment]
I have a question, in this 'ignoreSourceSet' can be used to ignore certain buildTypes and Flavor ?

https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/945
