### ISSUE TITLE
Fail Build if Feature Module Foo depends on Feature Module Bar

### ISSUE THREAD

**Issue by joelromanpr** [autonomousapps/dependency-analysis-android-gradle-plugin#902]
**Is your feature request related to a problem? Please describe.**

When a feature module depends on another feature module all hell breaks loose (aka circular dependencies)

**Describe the solution you'd like**

It will be great to have a way to define a list of patterns in which given a :feature:foo ensure :feature:bar cannot depend on each other. This could also be simplify if there was a "metadata" file or something in the module that indicates its a feature module etc so the task can evaluate in more simpler way things.

**Describe alternatives you've considered**

Create a build step that checks the modules dependencies and if a given module's name begins with the pattern in question fail the build. 

**Additional context**

**Comment by autonomousapps** [comment]
Thanks for the issue. I don't think this is a feature I want to support at this time. I think there are other plugins, as well, as Gradle core features, that support this use-case.
