### ISSUE TITLE
Provide option to disable pretty-formatted output files

### ISSUE THREAD

**Issue by TimvdLippe** [autonomousapps/dependency-analysis-android-gradle-plugin#903]
**Is your feature request related to a problem? Please describe.**
Currently, the plugin generates both prettified and non-prettified files. The prettified output files are human-readable, but are unused by the plugin itself (as far as I know). While the human-readable format is good for local development, on CI there is no need for it.

**Describe the solution you'd like**
Provide an option (preferably by default `false`) that enables generation of prettified output files. Users can then choose whether they want prettified files or not.

**Describe alternatives you've considered**
Stop prettifying files altogether, but there are probably users out there that use it. Still, most editors are able to format JSON files, so I am not sure to what extent this feature is used.

**Additional context**
Example prettified files:

`reports/dependency-analysis/main/intermediates/all-declared-dependencies-pretty.json`
`reports/dependency-analysis/main/intermediates/procs-declared-pretty.json`

**Comment by autonomousapps** [comment]
I mostly used that output early in the plugin's development to make "debugging" easier. I agree that there's not much need for it given that it's fairly easy to configure a text editor to format json, and IDEA also has at least one plugin that does it.

**Comment by autonomousapps** [comment]
Fixed via https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/pull/917
