### ISSUE TITLE
执行失败

### ISSUE THREAD

**Issue by wxy2016** [autonomousapps/dependency-analysis-android-gradle-plugin#906]
Unable to find method 'kotlin.jvm.internal.PropertyReference1Impl.<init>(Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;I)V'
kotlin.jvm.internal.PropertyReference1Impl.<init>(Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;I)V

**Comment by autonomousapps** [comment]
Closing as non-actionable. Feel free to reopen if you have a stacktrace and minimal reproducer.
