### ISSUE TITLE
Automate closing and releasing from maven staging repo

### ISSUE THREAD

**Issue by autonomousapps** [autonomousapps/dependency-analysis-android-gradle-plugin#91]
Borrow some code from https://github.com/vanniktech/gradle-maven-publish-plugin

**Comment by vlsi** [comment]
init/close/release is automated in https://github.com/vlsi/vlsi-release-plugins/tree/master/plugins/stage-vote-release-plugin

**Comment by autonomousapps** [comment]
This is now complete and on master.
