### ISSUE TITLE
Plugin does not report unused dependencies from source-containing root projects

### ISSUE THREAD

**Issue by pioterj** [autonomousapps/dependency-analysis-android-gradle-plugin#92]
**Plugin version**
0.32.0

**Gradle version**
6.3

**Android Gradle Plugin (AGP) version**
None - plain Java project

**Describe the bug**
Unused dependencies are not reported

**To Reproduce**
1. Bootstrap a java-library with gradle init (selected options: Java library, Java production code, Kotlin DSL, JUnit Jupiter)
2. Add some unused dependencies to the build script
3. Run ./gradlew buildHealth
4. "There were no dependency issues. Congrats!" is displayed

**Expected behavior**
Unused dependencies are reported.

**Additional context**
I also tried adding and I still couldn't get the plugin to report unused dependencies.  
```
dependencyAnalysis {
    issues {
        onUnusedDependencies { fail() }
    }
}
```

**Comment by autonomousapps** [comment]
This is due to a current limitation of the plugin, which is that it does no analysis in the root project. It treats that project as a convenient place to aggregate reports from subprojects. This is not a fundamental limitation and will only require prioritization and attention.

I may work on it soon. Thank you for the report!

**Comment by autonomousapps** [comment]
Working on adding support for this and I noticed this output:
```
> Task :adviceMain
Unused dependencies which should be removed:
- implementation("com.google.guava:guava:28.2-jre")
- api("org.apache.commons:commons-math3:3.6.1")

Existing dependencies which should be modified to be as indicated:
- implementation("org.apache.commons:commons-math3:3.6.1") // was api
```
note that it is suggesting to both remove the commons-math module _and_ change it from api to implementation. It should not contain the latter advice. Looks like a separate bug.
