### ISSUE TITLE
Detailed logs

### ISSUE THREAD

**Issue by ankitgoyal1009** [autonomousapps/dependency-analysis-android-gradle-plugin#925]
**Is your feature request related to a problem? Please describe.**
My android app has more then 50 teams and I am building a tooling about dependencies which 
1. Can fail the PR if there is any new unused dependencies being added.
2. Create a dashboard which will show which team needs to fix what kind of dependency issues.

**Describe the solution you'd like**
If I can get a report in json/xml format with module info in it, I will build the reporting for it.

**Describe alternatives you've considered**
Dump the console logs into a text file and then write a file parser which will look for text  "unused dependencies which should be removed" for each module.

**Additional context**
we get ~200 different PRs everyday and adding a new file processing will negatively impact our productivity.

**Comment by autonomousapps** [comment]
PTAL at https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/wiki/Post-processing, which should have what you need.

Going to close this issue as already-implemented, but feel free to reopen if you think there's something missing from the existing feature set.
