### ISSUE TITLE
Getting Unsupported class file major version 61 when including the Jackson library 2.15.+

### ISSUE THREAD

**Issue by rcolombo** [autonomousapps/dependency-analysis-android-gradle-plugin#927]
**Build scan link**
n/a

**Plugin version**
0.77.0

I am using this version because I need a Java8-compatible version. Please let me know if this is incorrect.
**Gradle version**
7.5

**(Optional) Android Gradle Plugin (AGP) version**
n/a

**`reason` output for bugs relating to incorrect advice**
n/a

**Describe the bug**
When running `./gradlew analyzeJarMain`, while including `implementation "com.fasterxml.jackson.core:jackson-databind:2.15.2" ` it fails with the below error:
```
> Task :analyzeJarMain FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':analyzeJarMain'.
> Unsupported class file major version 61
```

If I downgrade to `implementation "com.fasterxml.jackson.core:jackson-databind:2.14.+"`, everything works properly. This is strange because Jackson 2.15+ is compatible with Java8, but "Unsupported class file major version 61" suggests a Java17 compilation

**To Reproduce**
use version 0.77.0 of the plugin
add `implementation "com.fasterxml.jackson.core:jackson-databind:2.15.2"`
run `./gradlew analyzeJarMain`

**Expected behavior**
A normal report without failure

**Additional context**
I realize I am using an older version of the plugin, but this is for Java8 purposes. If there is a way to use a newer version while still being on Java8, please let me know.

**Comment by autonomousapps** [comment]
Thanks for the issue. Unfortunately, I don't have the bandwidth to work on older versions of the plugin. If your company is willing to sponsor work, that might change.
