### ISSUE TITLE
Improve output: `should be removed: implementation("[Ljava.lang.Object;@2f5626cb")`

### ISSUE THREAD

**Issue by yogurtearl** [autonomousapps/dependency-analysis-android-gradle-plugin#950]
**Plugin version**
1.21.0

**Gradle version**
8.3

**(Optional) Android Gradle Plugin (AGP) version**
8.1.0

**Describe the bug**
if you have: 
```kotlin
dependencies {
    implementation(files("libs/some-local.jar"))
}
```

`buildHealth` output contains:

```
Unused dependencies which should be removed:
  implementation("[Ljava.lang.Object;@2f5626cb")
```

It could probably print something more useful than `Ljava.lang.Object;@2f5626cb`. :) 

Also, the jar IS in use, but is reported as "unused"

**Comment by autonomousapps** [comment]
Thanks for the issue. This used to work 🤔

**Comment by autonomousapps** [comment]
I wonder if this is specific to Kotlin DSL? I wrote a quick test and the output was as expected (using Groovy DSL):
```> Task :buildHealth
Advice for :proj
Existing dependencies which should be modified to be as indicated:
  api 'external.jar' (was implementation)```
  
  Do you have a minimal reproducer?

**Comment by autonomousapps** [comment]
I was able to reproduce using the Kotlin DSL:
```Unused dependencies which should be removed:
  implementation("[Ljava.lang.Object;@22588437")```

**Comment by autonomousapps** [comment]
Well that's hilarious.

![Screenshot 2023-09-07 at 1 56 41 PM](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/assets/5402301/d2b9def9-645c-424c-80d4-fb3cfc41cd6e)
![Screenshot 2023-09-07 at 1 56 49 PM](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/assets/5402301/1846bb1f-bf67-4e3e-a10d-76f13f9d0729)

**Comment by yogurtearl** [comment]
Related: https://github.com/detekt/detekt/issues/6305

**Comment by yogurtearl** [comment]
Not sure if this actually works, but is `firstOrNull()` a problem? 

```
dependencies {
    implementation(files("libs/some-local.jar", "libs/some-other-local.jar"))
}
```

What about the rest of the stuff in the array?

**Comment by autonomousapps** [comment]
It's a Gradle bug: https://github.com/gradle/gradle/pull/26317

**Comment by autonomousapps** [comment]
And yes, you're right that the plugin ignores everything but the first file. It's a known deficiency. The best thing for users to do is simply not include multiple flat jars in that way (it's arguably a bad practice anyway).

**Comment by autonomousapps** [comment]
> Related -> [detekt/detekt#6305](https://github.com/detekt/detekt/issues/6305)

The issue here, if I'm understanding you, is that the type I'm getting from Gradle is `Any?`. So I can't know at compile-time that I'm dealing with an array.

**Comment by yogurtearl** [comment]
> The issue here, if I'm understanding you, is that the type I'm getting from Gradle is Any?. So I can't know at compile-time that I'm dealing with an array

Upon further reflection,  https://github.com/detekt/detekt/issues/6305 is only very tangentially related, in that it points that kotlin delegates to the underlying platform for `toString()` on arrays. 

The problem is shown in the gradle bug you linked. 

Something like this should do handle the various cases? (although, this is a cryptic way to do it)  
```kotlin
from.firstOrNull()?.let { (it as? Array<*>)?.firstOrNull() ?: it }
```

**Comment by yogurtearl** [comment]
> And yes, you're right that the plugin ignores everything but the first file. It's a known deficiency. The best thing for users to do is simply not include multiple flat jars in that way (it's arguably a bad practice anyway).

Maybe print some "advice" on that? 😅

```
advice: 
This is not support by this plugin
      implementation(files("libs/some-local.jar", "libs/some-other-local.jar")) 
Do this instead: 
      implementation(files("libs/some-local.jar"))
      implementation(files("libs/some-other-local.jar"))
```

**Comment by autonomousapps** [comment]
Please file an issue if this is a use case for you!
