### ISSUE TITLE
Bundles don't work with projects anymore

### ISSUE THREAD

**Issue by BraisGabin** [autonomousapps/dependency-analysis-android-gradle-plugin#952]
**Plugin version**
0.21.0

**Gradle version**
8.3

**(Optional) Android Gradle Plugin (AGP) version**
8.1.1

**Describe the bug**
After I update from 0.20.0 to 0.21.0 the `includeDependency` inside `bundle` that has this form: `:mymodule` aren't honored.

**To Reproduce**
I created this project to show it: https://github.com/BraisGabin/dagp-952

If you run `./gradlew buildHealth` gives these advices:
```
Advice for :app
Unused dependencies which should be removed:
  implementation(project(":a"))

These transitive dependencies should be declared directly:
  implementation(project(":b"))
```

But if you downgrade the plugin to `1.20.0` these advice are gone. And that have sense because I have this configuration:

```kotlin
dependencyAnalysis {
    dependencies {
        bundle("foo") {
            includeDependency(":a")
            includeDependency(":b")
        }
    }
}
```

**Expected behavior**
The `includeDependency` shouldn't be ignored

**Comment by autonomousapps** [comment]
@jjohannes this probably relates to the included build stuff? I guess another area where test coverage was lacking 😞

**Comment by jjohannes** [comment]
Looks very much like it. But hopefully it'll be a straight forward fix. I can have a look.

**Comment by autonomousapps** [comment]
@jjohannes I'm taking a look at this. I'm at the point where I have a failing test: https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/pull/959
