### ISSUE TITLE
Transitive dependency warning for dependencies used in generated code

### ISSUE THREAD

**Issue by Vichy97** [autonomousapps/dependency-analysis-android-gradle-plugin#958]
**Plugin version**
1.21.0

**Gradle version**
8.3

**(Optional) Android Gradle Plugin (AGP) version**
8.3.0-alpha01

**`reason` output for bugs relating to incorrect advice**
`reason --id androidx.sqlite:sqlite`

```
* Uses 8 classes, 5 of which are shown: androidx.sqlite.db.SupportSQLiteDatabase, androidx.sqlite.db.SupportSQLiteOpenHelper, androidx.sqlite.db.SupportSQLiteOpenHelper$Callback, androidx.sqlite.db.SupportSQLiteOpenHelper$Configuration, androidx.sqlite.db.SupportSQLiteOpenHelper$Configuration$Builder (implies implementation).
```

**Describe the bug**
It's possible this is actually expected behavior and the correct way to declare dependencies. If so, just feel free to close this issue out.

`buildHealth` is telling me to add some dependencies (namely `androidx.collection:collection` and `androidx.sqlite:sqlite`) that are only used within code generated by Room. It seems odd that I would declare these dependencies as the code generated is not used anywhere in my codebase directly. Should generated code be excluded by the plugin, or should I manually exclude these dependencies? 

**To Reproduce**
Use Jetpack Room library. Even a very minimal setup with a single simple dao will generate some classes that use the above libraries.

**Comment by autonomousapps** [comment]
This is expected behavior. That said, you could declare a [bundle](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/wiki/Customizing-plugin-behavior#logical-dependency-groups-aka-dependency-bundles) of dependencies around Room so that the plugin considers them all as one logical whole.
